ooni/probe-cli

Gopkg.lock, Gopkg.toml, Makefile, Readme.md, internal/bindata/bindata.go, internal/cli/run/run.go, internal/database/database.go, internal/database/models.go, nettests/groups/groups.go, nettests/nettests.go, nettests/performance/dash.go, ooni.go
I am opening a PR to make it easier to answer comments.
=> Will's WIP branch

internal/database/models.go, ooni.go, utils/geoip.go, utils/paths.go
As per suggestion by @willscott in: https://github.com/OpenObservatory/gooni/pull/9#discussion_r176759891
=> Move all directory related functionality into paths utils

build.sh
=> build.sh: produce same release as before

version/version.go
Needed for: https://github.com/ooni/probe-desktop/pull/74
=> Bump to 3.0.0-rc.1

config/parser.go, config/parser_test.go, config/settings.go, config/testdata/config-v0.json, config/testdata/valid-config.json, data/default-config.json, nettests/websites/web_connectivity.go, ooni.go, testdata/testing-config.json
To focus on a very minimal MVP.
This also fixes: https://github.com/ooni/probe-cli/issues/25.
What I still need to do in this branch is handle the migration from a beta user and a stable release user.
I suggest how we handle the migration is simply zapping the old configuration and starting fresh when we notice the presence of `_is_beta: true`. We should maybe also consider how to handle config file migrations in the future.
=> Remove all settings which are not implemented

config/testdata/config-v0.json, config/testdata/valid-config.json, data/default-config.json, testdata/testing-config.json
This fixes: https://github.com/ooni/probe/issues/946
=> Remove help link from the default config

internal/cli/run/run.go
=> Interrupt the nettestGroup loop early on termination

config/parser_test.go, config/settings.go, internal/cli/onboard/onboard.go, internal/cli/run/run.go
Fixes: https://github.com/ooni/probe/issues/1183
=> Always include the country code and drop include_probe_cc setting

go.mod, go.sum, version/version.go
Part of https://github.com/ooni/probe-engine/issues/728
=> Release v3.0.3

go.mod, go.sum, version/version.go
Part of https://github.com/ooni/probe-engine/issues/828
=> Release v3.0.6

config/parser.go
Spotted while reading the code.
=> fix(config/parser.go): correct unlocking on error paths

nettests/nettests.go
See https://github.com/ooni/probe/issues/1238
=> fix(nettests/nettests.go): make sure we emit progress

go.mod, go.sum, version/version.go
This beta release incorporates recent fixes in ooni/probe-engine that we
would like to test and ship relatively soon.
I'm doing this as part of https://github.com/ooni/explorer/issues/495
=> Start testing v3.0.8-beta

.github/workflows/linux-debian-packages.yml
See https://github.com/ooni/backend/issues/452
=> fix(debian pkg): only package the master branch

internal/cli/onboard/onboard.go, internal/cli/root/root.go, internal/cli/run/run.go, internal/nettests/nettests.go, internal/nettests/nettests_test.go, internal/nettests/web_connectivity.go, internal/ooni/ooni.go, internal/ooni/ooni_test.go
Closes https://github.com/ooni/probe/issues/939
=> refactor(internal/ooni): Context => Probe

internal/nettests/nettests.go
Part of https://github.com/ooni/probe/issues/1283
=> cleanup(nettests): remove unused OnDataUsage

internal/cli/run/run.go, internal/nettests/run.go
Part of https://github.com/ooni/probe/issues/1289
=> refactor: move code to run group in nettests package

internal/database/actions.go
Closes https://github.com/ooni/probe/issues/1326
=> fix(show): make sure we quote URL/query

internal/log/handlers/cli/results.go
=> Fixup the rightpad on the list command

build.sh
See https://github.com/ooni/probe/issues/807#issuecomment-766941585
=> fix(build.sh): clarify for what Linux archs we build

cmd/ooniprobe/internal/cli/onboard/onboard.go
Refactor the copy for the publishing of results setting
=> Drop the include_ip & include_network settings

.github/workflows/debian.yml, cmd/ooniprobe/internal/version/version.go, debian/ooniprobe-cli.templates
Basically: fix the debian package and make sure its template is not broken.
=> Release 3.5.1

cmd/ooniprobe/internal/cli/app/app.go, cmd/ooniprobe/internal/cli/root/root.go, cmd/ooniprobe/internal/cli/version/version.go, internal/cmd/apitool/main.go, internal/cmd/jafar/uncensored/uncensored.go, internal/cmd/oohelper/internal/client.go, internal/cmd/oohelper/oohelper.go, internal/cmd/oohelperd/internal/internal.go, internal/engine/experiment.go, internal/engine/experiment/dnscheck/dnscheck.go, internal/engine/experiment/run/urlgetter.go, internal/engine/experiment/tlstool/tlstool.go, internal/engine/experiment/tor/tor.go, internal/engine/experiment/urlgetter/runner.go, internal/engine/experiment/whatsapp/whatsapp.go, internal/engine/geolocate/geolocate.go, internal/engine/internal/mockable/mockable.go, internal/engine/internal/psiphonx/psiphonx_test.go, internal/engine/internal/sessionresolver/sessionresolver.go, internal/engine/legacy/netx/handlers/handlers.go, internal/engine/legacy/oonitemplates/oonitemplates.go, internal/engine/netx/netx.go, internal/engine/netx/resolver/bogon.go, internal/engine/session.go, internal/engine/session_integration_test.go, internal/engine/version/version.go, internal/libminiooni/libminiooni.go, internal/version/version.go, pkg/oonimkall/internal/tasks/runner.go, pkg/oonimkall/session.go
See https://github.com/ooni/probe-engine/issues/1181
While there, run `go fmt ./...`
=> fix: always use probe-cli version (and make it alpha)

cmd/ooniprobe/internal/autorun/autorun_darwin.go, cmd/ooniprobe/internal/utils/homedir/homedir.go, internal/cmd/e2epostprocess/main.go, internal/cmd/jafar/iptables/iptables_integration_test.go, internal/cmd/jafar/main.go, internal/engine/shellx/shellx.go
Closes https://github.com/ooni/probe-engine/issues/1195
=> fix: use golang.org/x/sys/execabs

pkg/oonimkall/session.go, pkg/oonimkall/session_integration_test.go
Implementing https://github.com/ooni/probe/issues/1331
=> oonimkall: add wrappers for /test-list/urls

cmd/ooniprobe/internal/nettests/groups.go, cmd/ooniprobe/internal/nettests/signal.go, internal/engine/allexperiments.go, internal/engine/experiment/riseupvpn/riseupvpn.go, internal/engine/experiment/signal/signal.go, internal/engine/experiment/signal/signal_test.go, internal/engine/experiment/sniblocking/sniblocking.go, internal/engine/experiment/stunreachability/stunreachability_test.go, internal/engine/experiment/telegram/telegram.go, internal/engine/experiment/webconnectivity/summary.go, internal/engine/inputloader.go, internal/engine/netx/netx.go, pkg/oonimkall/task_integration_test.go
Basic implementation of a Signal app test
Reference issue: https://github.com/ooni/probe-engine/issues/278
=> MVP of a signal messenger test

internal/engine/experiment/telegram/telegram.go
Based on: https://github.com/telegramdesktop/tdesktop/blob/65ba81f50409d10f2d592a1594477525d436a3df/Telegram/SourceFiles/mtproto/mtproto_dc_options.cpp
Part of https://github.com/ooni/probe-engine/issues/999
=> Add new telegram DC endpoint

Readme.md, debian/changelog, debian/ooniprobe-cli.service
Set version 3.5.2 ; few other changes
Cherry-picked from #231
=> Debian package updates

cmd/ooniprobe/internal/autorun/autorun_darwin.go
Fixes: https://github.com/ooni/probe/issues/1368
=> Create the LaunchAgents directory if it does not exist

internal/engine/experiment/webconnectivity/control.go, internal/engine/experiment/webconnectivity/dnslookup.go, internal/engine/experiment/webconnectivity/httpget.go, internal/engine/experiment/webconnectivity/httpget_test.go, internal/engine/experiment/webconnectivity/webconnectivity.go, internal/engine/experiment/webconnectivity/webconnectivity_test.go, internal/engine/netx/netx.go, internal/engine/netx/netx_test.go
See https://github.com/ooni/probe/issues/1376
=> fix(webconnectivity): allow measuring https://1.1.1.1

.github/workflows/android.yml, build-android.bash
See https://github.com/ooni/probe-engine/issues/1179
=> fix(android): remove pin to specific NDK version

internal/libminiooni/libminiooni.go
See https://github.com/ooni/probe/issues/1380
=> feat(libminiooni): implement --version and --limit

cmd/ooniprobe/internal/nettests/stunreachability.go, internal/engine/allexperiments.go, internal/engine/experiment/stunreachability/stunreachability.go, internal/engine/experiment/stunreachability/stunreachability_test.go
See https://github.com/ooni/probe/issues/1394
Ok @hellais @FedericoCeratto
=> chore: rename stun_reachability => stunreachability

internal/engine/experimentbuilder.go, internal/engine/probeservices/benchselect.go
Preliminary work done as part of https://github.com/ooni/probe/issues/1299
=> fix: apply staticcheck suggestions

cmd/ooniprobe/internal/nettests/web_connectivity.go, internal/engine/allexperiments.go, internal/engine/experiment_integration_test.go, internal/engine/experimentbuilder.go, internal/engine/inputloader.go, internal/engine/inputloader_integration_test.go, internal/engine/inputloader_test.go, internal/engine/internal/sessionresolver/resolvermaker.go, pkg/oonimkall/internal/tasks/runner.go
Work done as part of https://github.com/ooni/probe/issues/1299.
=> refactor(inputloader): better docs and naming

cmd/ooniprobe/internal/nettests/web_connectivity.go, internal/cmd/miniooni/libminiooni.go, internal/engine/inputloader.go, internal/engine/inputloader_network_test.go, internal/engine/inputloader_test.go
Part of https://github.com/ooni/probe/issues/1299.
=> refactor(inputloader): remove unnecessary javisms

internal/cmd/miniooni/libminiooni.go, internal/engine/inputprocessor.go, internal/engine/inputprocessor_test.go
Part of https://github.com/ooni/probe/issues/1299
=> fix(miniooni): replace --limit with --max-runtime

internal/engine/experiment/riseupvpn/riseupvpn.go, internal/engine/experiment/riseupvpn/riseupvpn_test.go
part of  https://github.com/ooni/probe/issues/1354
=> riseupvpn: reduce false positives

cmd/ooniprobe/internal/cli/run/run.go, cmd/ooniprobe/internal/nettests/nettests.go
See https://github.com/ooni/probe/issues/1299
=> fix(ooniprobe): consistent progress with maxRuntime

internal/cmd/oohelper/oohelper.go, internal/cmd/oohelper/oohelper_test.go
Hopefully this helps with https://github.com/ooni/probe/issues/1409.
Part of https://github.com/ooni/probe/issues/1369
=> fix(oohelper): make sure the CI is green

internal/engine/experiment/urlgetter/getter.go, internal/engine/session.go, internal/engine/tunnel/integration_test.go, internal/engine/tunnel/tunnel.go, internal/engine/tunnel/tunnel_test.go
=> refactor(tunnel): pass the config as a pointer

internal/engine/tunnel/psiphon.go
=> fix(tunnel/psiphon): don't overwrite config.WorkDir

internal/engine/session.go, internal/engine/tunnel/tunnel.go
=> refactor(tunnel): remove dependecy from logger

go.mod, go.sum, internal/engine/session.go, internal/engine/tunnel/config.go, internal/engine/tunnel/fake.go, internal/engine/tunnel/fake_integration_test.go, internal/engine/tunnel/fake_test.go, internal/engine/tunnel/tunnel.go
This functionality should be helpful to test that the general
interface of the tunnel package is okay from the engine package.
=> feat(tunnel): implement the fake tunnel

internal/engine/session_integration_test.go, internal/engine/session_internal_test.go, internal/engine/session_nopsiphon.go, internal/engine/session_nopsiphon_test.go
=> fix(session): make sure tunnel code is tested

MOBILE/ios/.gitignore, MOBILE/template.podspec, MOBILE/template.pom, build-ios.bash
Part of https://github.com/ooni/probe/issues/1437
=> feat(ios): adapt build to post bintray world

internal/version/version.go
Part of https://github.com/ooni/probe/issues/1440
=> chore: we're now at 3.10.0-alpha.1

.github/workflows/ios.yml, internal/version/version.go, make
* fix the way in which we generate the iOS build
* bump version number to v3.10.0-beta.1
=> Release v3.10.0-beta.1

internal/engine/experiment/riseupvpn/riseupvpn.go, pkg/oonimkall/internal/tasks/runner.go, pkg/oonimkall/session.go
=> chore: link new TODOs with the relevant issues

make
The previous composition strategy was such that it was difficult
to compose functions returning a value.
This new composition strategy is better because it allows us to
return values, which is definitely going to help us.
Part of https://github.com/ooni/probe/issues/1466.
=> fix(make): compose runner and dry runner directly

make
Further simplifies working with the environment.
Part of https://github.com/ooni/probe/issues/1466.
=> refactor(make): easier unified environment management

.gitignore, .vscode/settings.json, CLI/darwin/amd64/.gitignore, CLI/darwin/arm64/.gitignore, CLI/linux/386/.gitignore, CLI/linux/amd64/.gitignore, CLI/linux/arm/.gitignore, CLI/linux/arm64/.gitignore, CLI/windows/386/.gitignore, CLI/windows/amd64/.gitignore, make
While there, fix an annoying bug where the context manager
was suppressing exceptions that occurred.
Work part of https://github.com/ooni/probe/issues/1466.
=> feat(make): sign more generated binaries 

make
See https://github.com/ooni/probe/issues/1466
=> refactor(make): simplify the implementation of backticks

make
Cleanup after https://github.com/ooni/probe/issues/1466
=> refactor(./make): better way to discover deps

make
More cleanup after https://github.com/ooni/probe/issues/1466
=> fix(./make): chdir before signing for Android

mk
See https://github.com/ooni/probe/issues/1468
=> fix(mk): ios must depend on copying the psiphon config

mk
Part of https://github.com/ooni/probe/issues/1468
=> feat(mk): package/sign cli builds

.github/workflows/debianrepo.yml, E2E/debian.sh
We want to be sure it's working for all the supported archs.
See https://github.com/ooni/probe/issues/1484
=> feat: make sure our debian repo is WAI

internal/engine/experiment/riseupvpn/riseupvpn.go, internal/engine/experiment/signal/signal.go, internal/engine/experiment/urlgetter/configurer.go, internal/engine/experiment/urlgetter/configurer_test.go, internal/engine/netx/netx.go, internal/engine/netx/netx_test.go
=> refactor(netx): remove forwarders for tlsx

internal/ptx/snowflake.go
This work concludes https://github.com/ooni/probe/issues/1605.
The follow-up issue is https://github.com/ooni/probe/issues/1681.
=> chore(snowflake.go): this TODO comment is now an issue

go.mod, go.sum, internal/engine/netx/netx.go, internal/engine/netx/quicdialer/dns_test.go, internal/engine/netx/quicdialer/errorwrapper_test.go, internal/engine/netx/quicdialer/saver_test.go, internal/engine/netx/quicdialer/system_test.go
Closes https://github.com/ooni/probe/issues/1682
=> quic: use RFC9000 version

internal/ptx/snowflake.go
See https://github.com/ooni/probe-cli/pull/373#discussion_r651080925
=> fix(snowflake.go): default maxSnowflakes() to 1

internal/engine/experiment/tor/tor.go, internal/engine/netx/errorx/errorx.go, internal/scrubber/scrubber.go, internal/scrubber/scrubber_test.go
Also part of https://github.com/ooni/probe/issues/1687
=> refactor: move scrubber into its own package

internal/cmd/oohelperd/internal/internal_test.go, internal/engine/experiment/ndt7/dial.go, internal/engine/legacy/netx/dialer.go, internal/engine/legacy/netx/resolver.go, internal/engine/netx/netx.go, internal/engine/netx/netx_test.go, internal/engine/netx/resolver/chain_test.go, internal/engine/netx/resolver/integration_test.go, internal/engine/netx/tlsdialer/integration_test.go, internal/engine/netx/tlsdialer/saver_test.go, internal/engine/netx/tlsdialer/tls.go, internal/engine/netx/tlsdialer/tls_test.go, internal/netxlite/resolver.go, internal/netxlite/tlshandshaker.go, internal/netxlite/tlshandshaker_test.go
=> refactor: move tls handshaker to netxlite

internal/engine/netx/netx.go, internal/engine/netx/quicdialer/dns_test.go, internal/engine/netx/quicdialer/errorwrapper_test.go, internal/engine/netx/quicdialer/saver_test.go, internal/engine/netx/quicdialer/system.go, internal/engine/netx/quicdialer/system_test.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go, internal/netxmocks/quic.go, internal/netxmocks/quic_test.go
=> refactor: move quicdialing base functionality to netxlite

internal/netxlite/quic.go, internal/netxlite/quic_test.go, internal/netxmocks/quic.go, internal/netxmocks/quic_test.go, internal/netxmocks/tlsconn_test.go
=> feat(netxlite): add QUICDialerLogger

internal/ptx/obfs4.go, internal/ptx/obfs4_test.go
See discussion at https://github.com/ooni/probe-cli/pull/413#issuecomment-871552943.
=> fix(ptx): use another obfs4 bridge

internal/engine/netx/dialer/dialer.go, internal/engine/netx/dialer/dialer_test.go, internal/errorsx/dialer.go, internal/errorsx/dialer_test.go
=> refactor: move dialer's errorwrapper in i/errorsx

internal/engine/netx/quicdialer/connectionstate.go, internal/engine/netx/quicdialer/quicdialer.go, internal/engine/netx/quicdialer/saver.go, internal/engine/netx/quicdialer/system.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go, internal/netxmocks/quic.go, internal/netxmocks/quic_test.go, internal/quicx/quicx.go
Also part of https://github.com/ooni/probe/issues/1505
=> refactor: cleaner way of passing a UDPConn around

internal/engine/netx/netx.go, internal/errorsx/errorsx.go, internal/errorsx/quic.go, internal/errorsx/quic_test.go, internal/netxmocks/conn.go, internal/netxmocks/quic.go, internal/netxmocks/quic_test.go
=> feat(errorsx): add error wrapper for quic

internal/errorsx/dialer.go, internal/errorsx/errorsx.go, internal/errorsx/errorsx_test.go, internal/errorsx/failures.go, internal/errorsx/operations.go, internal/errorsx/quic.go, internal/errorsx/resolver.go, internal/errorsx/tls.go
=> refactor(errorsx): start hiding private details and moving around stuff

go.mod, internal/netxlite/tlshandshaker.go, internal/netxlite/tlshandshaker_test.go
This is the ground work for https://github.com/ooni/probe/issues/1424.
=> netxlite: utls for TLS parroting

internal/cmd/oohelperd/internal/webconnectivity/dns.go, internal/cmd/oohelperd/internal/webconnectivity/fake_test.go, internal/cmd/oohelperd/internal/webconnectivity/http.go, internal/cmd/oohelperd/internal/webconnectivity/http_test.go, internal/cmd/oohelperd/internal/webconnectivity/measure.go, internal/cmd/oohelperd/internal/webconnectivity/tcpconnect.go, internal/cmd/oohelperd/internal/webconnectivity/webconnectivity.go, internal/cmd/oohelperd/internal/webconnectivity/webconnectivity_test.go, internal/cmd/oohelperd/internal/websteps/explore.go, internal/cmd/oohelperd/internal/websteps/explore_test.go, internal/cmd/oohelperd/internal/websteps/factory.go, internal/cmd/oohelperd/internal/websteps/generate.go, internal/cmd/oohelperd/internal/websteps/generate_test.go, internal/cmd/oohelperd/internal/websteps/h3.go, internal/cmd/oohelperd/internal/websteps/h3_test.go, internal/cmd/oohelperd/internal/websteps/initialchecks.go, internal/cmd/oohelperd/internal/websteps/initialchecks_test.go, internal/cmd/oohelperd/internal/websteps/measure.go, internal/cmd/oohelperd/internal/websteps/measure_test.go, internal/cmd/oohelperd/internal/websteps/model.go, internal/cmd/oohelperd/internal/websteps/websteps.go, internal/cmd/oohelperd/internal/websteps/websteps_test.go, internal/cmd/oohelperd/oohelperd.go
Part of https://github.com/ooni/probe/issues/1733
=> refactor(oohelperd): better distinguish different helpers

internal/cmd/oohelperd/internal/websteps/generate.go, internal/cmd/oohelperd/internal/websteps/generate_test.go, internal/cmd/oohelperd/internal/websteps/measure.go, internal/cmd/oohelperd/internal/websteps/measure_test.go, internal/cmd/oohelperd/internal/websteps/model.go, internal/engine/experiment/websteps/control.go, internal/engine/experiment/websteps/model.go, internal/engine/experiment/websteps/websteps.go
Work part of: https://github.com/ooni/probe/issues/1733
Spec draft: https://github.com/ooni/spec/pull/219
=> refactor: sync messages with spec draft

internal/cmd/oohelperd/internal/websteps/websteps.go, internal/engine/experiment/websteps/websteps.go
See https://github.com/ooni/probe/issues/1729
=> doc: mention the test helper spec we're using

PULL_REQUEST_TEMPLATE.md
My main concern here is to remind contributors (_including myself_) about the documents they should have read and that every change may entail also changes in ooni/spec. This work counts as a cleanup before closing https://github.com/ooni/probe/issues/1729.
=> doc: sketch out pull request template

go.mod, go.sum
Updating x/sys so that this supports go 1.17. Once this is in here we will need to cut a new release.
More context: https://github.com/Homebrew/homebrew-core/pull/83413
=> Update x/sys for go 1.17

PULL_REQUEST_TEMPLATE.md
Specifically, don't say the description is optional and make sure
there is a handy link to the issue tracker.
=> fix: improve the pull request template

.github/workflows/coverage.yml
This is part of the migration from go1.16 go go1.17.
Reference issue: https://github.com/ooni/probe/issues/1738
=> coverage: start using also go1.17

Readme.md
This PR improves Readme.md by applying minor changes, including referring to the ooni/spec repo.
=> doc(Readme.md): minor refactoring

internal/platform/platform.go, internal/platform/platform_test.go
=> fix(internal/platform): support freebsd

.github/workflows/coverage.yml, .github/workflows/debianrepo.yml, internal/ptx/obfs4_test.go
This PR includes three small diffs to make the development leaner until we reach a release and ensure we are reducing the number of errors when running routine tests during pull requests and merges to `master`.
=> ci: master only runs coverage and only with go1.17 (+ fix flaky test)

internal/netxlite/resolver.go, internal/netxlite/resolver_test.go
We will use this in a moment when we will add support for the
dnstransports that currently are in engine/netx.
=> fix(netxlite): resolver _always_ short circuits IP addrs

internal/netxlite/legacy.go, internal/netxlite/tls.go, internal/netxlite/tls_test.go, internal/netxlite/utls.go, internal/netxlite/utls_test.go
=> refactor(netxlite): add factories to create TLS handshakers

internal/netxlite/utls.go, internal/netxlite/utls_test.go
See https://github.com/ooni/probe/issues/1770
=> fix(netxlite): gracefully handle utls panics

internal/netxlite/http.go, internal/netxlite/http_test.go
=> feat(netxlite): integrate websteps code to use ooni/oohttp

internal/netxlite/dialer.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go
=> feat(netxlite): write factories for quic code

internal/netxlite/iox/iox_test.go
=> refactor(netxlite/iox): group tests and avoid races

internal/netxlite/certifi_test.go, internal/netxlite/dialer.go, internal/netxlite/dialer_test.go, internal/netxlite/legacy.go, internal/netxlite/tls.go, internal/netxlite/tls_test.go
While there, add one more test checking for whether the internal
CA bundle we use can actually be loaded.
=> refactor(netxlite): restructure dialer tests

internal/netxlite/http3.go, internal/netxlite/http3_test.go, internal/netxlite/http_test.go, internal/netxlite/integration_test.go, internal/netxlite/mocks/http3.go, internal/netxlite/mocks/http3_test.go
=> refactor(netxlite): improve tests for http and http3

internal/netxlite/integration_test.go, internal/netxlite/legacy_test.go, internal/netxlite/quic_test.go, internal/netxlite/quirks_test.go, internal/netxlite/resolver_test.go, internal/netxlite/tls_test.go, internal/netxlite/utls_test.go
They are now more readable. I'll do another pass and start
separating integration testing from unit testing.
I think we need to have some always on integration testing
for netxlite that runs on macOS, linux, and windows.
=> refactor(netxlite): finish grouping tests

internal/netxlite/dialer.go, internal/netxlite/dialer_test.go, internal/netxlite/tls.go, internal/netxlite/tls_test.go
=> feat(netxlite): introduce null dialers

internal/netxlite/tls.go
=> doc(netxlite/tls.go): explain what the handshake returns

internal/netxlite/certifi_test.go, internal/netxlite/dialer.go, internal/netxlite/dialer_test.go, internal/netxlite/errorsx/errwrapper.go, internal/netxlite/errorsx/errwrapper_test.go, internal/netxlite/mocks/logger.go, internal/netxlite/mocks/logger_test.go, internal/netxlite/quic.go, internal/netxlite/quirks.go, internal/netxlite/quirks_test.go, internal/netxlite/resolver.go, internal/netxlite/tls.go
* better documentation
* more strict testing of dialer (especially make sure we
document the quirk in https://github.com/ooni/probe/issues/1779
and we have tests to guarantee we don't screw up here)
* introduce NewErrWrapper factory for creating errors so we
have confidence we are creating them correctly
=> netxlite: improve docs, tests, and code quality

internal/netxlite/dialer.go, internal/netxlite/doc.go, internal/netxlite/http.go, internal/netxlite/http3_test.go, internal/netxlite/http_test.go, internal/netxlite/integration_test.go, internal/netxlite/legacy.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go, internal/netxlite/quirks_test.go, internal/netxlite/resolver.go, internal/netxlite/resolver_test.go, internal/netxlite/tls.go, internal/netxlite/tls_test.go, internal/netxlite/utls.go
=> netxlite: code quality, improve tests, docs

internal/cmd/oohelperd/internal/websteps/measure.go, internal/cmd/oohelperd/internal/websteps/websteps.go
=> doc(oohelper): tweak documentation

internal/engine/experiment/urlgetter/configurer_test.go, internal/engine/netx/netx_test.go, internal/engine/netx/resolver/decoder.go, internal/engine/netx/resolver/decoder_test.go, internal/engine/netx/resolver/encoder.go, internal/engine/netx/resolver/encoder_test.go, internal/engine/netx/resolver/serial.go
While there, generally convert more code to internal testing
and to using pointer receivers as well.
=> refactor(resolver): add CloseIdleConnections to SerialResolver

internal/cmd/oohelperd/internal/webconnectivity/dns.go, internal/cmd/oohelperd/internal/webconnectivity/http.go, internal/cmd/oohelperd/oohelperd.go
This PR contains changes that reduce the difference in behaviour between the old and the new test helper.
=> fix(oohelperd): reduce differences with legacy helper

internal/netxlite/dialer.go, internal/netxlite/http.go, internal/netxlite/resolver.go
This diff has been extracted from https://github.com/ooni/probe-cli/pull/506.
In it, we introduce wrapping constructors for types and we
update the docs. These new constructures are used by the code
in https://github.com/ooni/probe-cli/pull/506.
=> feat(netxlite): introduce wrapping constructors

internal/netxlite/http_test.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go
While there, make sure netxlite has 100% coverage.
Part of https://github.com/ooni/probe/issues/1733 and diff has been extracted from https://github.com/ooni/probe-cli/pull/506.
=> fix(netxlite/quic): wrap Close

internal/netxlite/errorsx/errwrapper.go, internal/netxlite/errorsx/errwrapper_test.go
Part of https://github.com/ooni/probe/issues/1733 and diff has been
extracted from https://github.com/ooni/probe-cli/pull/506.
=> feat(errorsx): introduce NewTopLevelGenericErrWrapper

internal/netxlite/dnsx/decoder.go, internal/netxlite/dnsx/decoder_test.go, internal/netxlite/dnsx/mocks/decoder.go, internal/netxlite/dnsx/mocks/decoder_test.go, internal/netxlite/dnsx/model/model.go, internal/netxlite/dnsx/serial.go, internal/netxlite/dnsx/serial_test.go, internal/netxlite/legacy.go, internal/netxlite/legacy_test.go, internal/netxlite/mocks/resolver.go, internal/netxlite/mocks/resolver_test.go, internal/netxlite/resolver.go, internal/netxlite/resolver_test.go
This new API call performs DNS lookups for HTTPS records.
=> feat(netxlite): implement LookupHTTPS

internal/engine/netx/resolver/legacy.go, internal/netxlite/dnsx/dnsdecoder.go, internal/netxlite/dnsx/dnsdecoder_test.go, internal/netxlite/dnsx/dnsencoder.go, internal/netxlite/dnsx/dnsencoder_test.go, internal/netxlite/dnsx/dnsoverhttps.go, internal/netxlite/dnsx/dnsovertcp.go, internal/netxlite/dnsx/dnsoverudp.go, internal/netxlite/dnsx/dnstransport.go, internal/netxlite/dnsx/mocks/dnsdecoder.go, internal/netxlite/dnsx/mocks/dnsdecoder_test.go, internal/netxlite/dnsx/mocks/dnsencoder.go, internal/netxlite/dnsx/mocks/dnsencoder_test.go, internal/netxlite/dnsx/mocks/dnstransport.go, internal/netxlite/dnsx/mocks/dnstransport_test.go, internal/netxlite/dnsx/serialresolver.go, internal/netxlite/dnsx/serialresolver_test.go
Part of https://github.com/ooni/probe/issues/1591.
=> refactor(dnsx): prepare for merging with netxlite

internal/netxlite/dnsx/dnsdecoder_test.go, internal/netxlite/dnsx/dnsencoder_test.go, internal/netxlite/dnsx/dnsoverhttps_test.go, internal/netxlite/dnsx/dnsovertcp_test.go, internal/netxlite/dnsx/dnsoverudp_test.go, internal/netxlite/dnsx/serialresolver.go, internal/netxlite/dnsx/serialresolver_test.go
=> refactor(dnsx): group tests together

internal/netxlite/resolver.go, internal/netxlite/resolver_test.go, internal/tutorial/generator/main.go, internal/tutorial/netxlite/README.md, internal/tutorial/netxlite/chapter01/README.md, internal/tutorial/netxlite/chapter01/main.go, internal/tutorial/netxlite/chapter02/README.md, internal/tutorial/netxlite/chapter02/main.go, internal/tutorial/netxlite/chapter03/README.md, internal/tutorial/netxlite/chapter03/main.go, internal/tutorial/netxlite/chapter04/README.md, internal/tutorial/netxlite/chapter04/main.go, internal/tutorial/netxlite/chapter05/README.md, internal/tutorial/netxlite/chapter05/main.go, internal/tutorial/netxlite/chapter06/README.md, internal/tutorial/netxlite/chapter06/main.go, internal/tutorial/netxlite/chapter07/README.md, internal/tutorial/netxlite/chapter07/main.go, internal/tutorial/netxlite/chapter08/README.md, internal/tutorial/netxlite/chapter08/main.go
The main tutorial will be the one at #506, but
it's useful to also document the primitives used by measurex.
So, here's the companion tutorial, which explains how to use the
features in netxlite to perform measurements.
This work is part of ooni/ooni.org#361.
=> doc: add tutorial on how to use netxlite

internal/netxlite/resolver_test.go
Should fix https://github.com/ooni/probe-cli/pull/523#issuecomment-930430124.
Work part of https://github.com/ooni/probe-cli/pull/506.
=> fix(resolver_test.go): remove race and make deterministic

internal/netxlite/quic.go
Closes https://github.com/ooni/probe/issues/1794
=> fix(netxlite/quic): close udp conn after failed handshake

internal/engine/experiment.go, internal/engine/experiment/webstepsx/measurer.go, internal/engine/model/experiment.go
Closes https://github.com/ooni/probe/issues/1798
=> fix(websteps): use correct input for each URL measurement

internal/engine/experiment/webconnectivity/webconnectivity.go, internal/engine/experiment/webconnectivity/webconnectivity_test.go
See https://github.com/ooni/probe/issues/1797.
=> feat(webconnectivity): collect timing information

internal/tutorial/measurex/chapter03/README.md, internal/tutorial/measurex/chapter03/main.go, internal/tutorial/measurex/chapter04/README.md, internal/tutorial/measurex/chapter04/main.go, internal/tutorial/measurex/chapter05/README.md, internal/tutorial/measurex/chapter05/main.go, internal/tutorial/measurex/chapter06/README.md, internal/tutorial/measurex/chapter06/main.go, internal/tutorial/measurex/chapter08/README.md, internal/tutorial/measurex/chapter08/main.go, internal/tutorial/measurex/chapter11/README.md, internal/tutorial/measurex/chapter11/main.go, internal/tutorial/measurex/chapter14/README.md, internal/tutorial/measurex/chapter14/main.go
I will use this branch to track changes for edits to be made on the measurex tutorial. After the review is finished I need to remember to re-run the generation code
=> Edits to the measurex tutorial

internal/netxlite/dialer.go, internal/netxlite/dialer_test.go, internal/netxlite/quic.go, internal/netxlite/resolver.go, internal/netxlite/tproxy.go
=> feat(netxlite): implement hooks for transparent proxy

internal/netxlite/filtering/dns.go
Without this change, it takes too much to serve a single query and
we cannot properly use this code for QA.
See https://github.com/ooni/probe/issues/1803#issuecomment-957323297
=> fix(filtering/dns.go): serve requests in parallel

internal/netxlite/filtering/dns_test.go, internal/netxlite/filtering/http.go, internal/netxlite/filtering/http_test.go, internal/netxlite/filtering/tls.go, internal/netxlite/filtering/tls_test.go
Needed to finish the design at https://github.com/ooni/probe/issues/1803#issuecomment-957323297
=> feat(filtering): implement HTTP filtering proxy

internal/measurex/measurer.go
Closes https://github.com/ooni/probe/issues/1859
=> fix(measurex): avoid data race with HTTP request headers

internal/engine/httpheader/acceptlanguage.go
Closes https://github.com/ooni/probe/issues/1792
=> fix(httpheader): use same Accept-Language as Brave

internal/engine/experiment/webstepsx/measurer.go
Closes https://github.com/ooni/probe/issues/1807
While there, bump the experiment version number, because we have
applied changes since the last alpha release.
=> fix(websteps): use a single Do53 resolver

internal/engine/experiment/webstepsx/measurer.go, internal/engine/experiment/webstepsx/th.go, internal/measurex/measurer.go, internal/tutorial/measurex/chapter09/README.md, internal/tutorial/measurex/chapter09/main.go, internal/tutorial/measurex/chapter10/README.md, internal/tutorial/measurex/chapter10/main.go, internal/tutorial/measurex/chapter11/README.md, internal/tutorial/measurex/chapter11/main.go, internal/tutorial/measurex/chapter12/README.md, internal/tutorial/measurex/chapter12/main.go
=> fix(measurex): allow API user to choose parallelism

internal/tutorial/README.md
Each tutorial provides you a piece of knowledge. Add some text in
the main readme file explaining the big picture to the reader.
Closes https://github.com/ooni/probe/issues/1819
=> doc(tutorial): explain the big picture

internal/engine/geolocate/resolverlookup.go
=> fix(geolocate): use powerdns.org whoami service

.github/workflows/miniooni.yml, CLI/.gitignore, mk
This is the miniooni related part of https://github.com/ooni/probe/issues/1879.
This diff will require backport to the release/3.11 branch.
=> feat: publish miniooni binaries into releases

internal/measurex/archival.go, internal/measurex/measurement.go
This case happens when the TH fails.
=> fix(measurex): handle case where TH is nil

internal/engine/experiment/webconnectivity/control.go
=> fix(webconnectivity): send specific user agent

pkg/oonimkall/runner.go, pkg/oonimkall/runner_internal_test.go, pkg/oonimkall/taskmocks_test.go, pkg/oonimkall/taskmodel.go, pkg/oonimkall/tasksession.go, pkg/oonimkall/tasksession_test.go
See https://github.com/ooni/probe/issues/1903
=> refactor(oonimkall): make the runner unit-testable

pkg/oonimkall/runner.go, pkg/oonimkall/runner_internal_test.go, pkg/oonimkall/taskmocks_test.go, pkg/oonimkall/taskmodel.go, pkg/oonimkall/tasksession.go, pkg/oonimkall/tasksession_test.go
I still need to write more assertions for each emitted event
but the code we've here is already a great starting point.
See https://github.com/ooni/probe/issues/1903
=> feat(oonimkall): write unit tests for the runner component

Readme.md
See https://github.com/ooni/probe-cli/pull/446#issuecomment-995226707
=> fix(Readme.md): add explicit SPDX identifier

cmd/ooniprobe/internal/cli/onboard/onboard.go, cmd/ooniprobe/internal/cli/rm/rm.go, go.mod, go.sum
Part of https://github.com/ooni/probe/issues/1894
=> chore: upgrade to survey v2.3.2

internal/netxlite/dnsovertcp_test.go, internal/netxlite/http3_test.go, internal/netxlite/http_test.go, internal/netxlite/quirks.go, internal/netxlite/quirks_test.go
See https://github.com/ooni/probe/issues/1985 for context.
While there, ensure nextlite has 100% of coverage.
=> fix(reduceErrors): return error when given an empty list

cmd/ooniprobe/internal/nettests/groups.go
Closes https://github.com/ooni/probe/issues/2000
Closes https://github.com/ooni/probe/issues/2001
=> fix: disable riseupvpn experiment

internal/version/version.go
We've just branched off the release/3.14 branch for finalizing
the release of 3.14.0, hence let's declare that from now on we're
3.15.0-alpha to avoid any confusion.
=> chore: start hacking on 3.15.0-alpha

internal/cmd/jafar/README.md
=> jafar(README.md): fix typo

internal/engine/allexperiments.go, internal/engine/experiment/simplequicping/simplequicping.go, internal/engine/experiment/simplequicping/simplequicping_test.go, internal/engine/experiment/tlsping/tlsping.go
See https://github.com/ooni/probe/issues/2091 (issue) and https://github.com/ooni/spec/pull/237 (spec).
=> feat: introduce the simplequicping experiment

internal/engine/experiment/ndt7/upload.go
I have added a goroutine with this PR that spawn in background, reads and discards all incoming websockets messages.
=> fix(ndt7):  should read and discard messages during upload

.github/workflows/checks.yml, .github/workflows/coverage.yml, .github/workflows/netxlite.yml
This commit uses a build cache for the coverage github action.
=> chore(ci): start saving/restoring go build cache

internal/netxlite/bogon.go, internal/netxlite/bogon_test.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go, internal/netxlite/resolver.go
This diff imports improved bogons handling code from websteps
winter 2022 edition's repository.
See https://github.com/ooni/probe/issues/2095
See https://github.com/bassosimone/websteps-illustrated/blob/a65f3e8579b59565789a1f38c468b0a9646783cd/internal/netxlite/bogon.go
=> chore: import improved bogons handling code

internal/netxlite/quic.go, internal/netxlite/quic_test.go
This diff has been extracted from https://github.com/bassosimone/websteps-illustrated/commit/c2f7ccab0ec971d5c084ea4c571b76f7530b28ee
See https://github.com/ooni/probe/issues/2096
=> netxlite: factor common code for parsing UDPAddr

internal/cmd/apitool/main_test.go, internal/engine/probeservices/checkreportid_test.go, internal/ooapi/integration_test.go
See https://github.com/ooni/probe/issues/2098
=> fix: re-enable previosuly disabled tests

cmd/ooniprobe/internal/nettests/run.go, go.mod
This could be a function later if we need to re-use it. 
For example, when re-upload is implemened and we might want to remove the directory after upload.
=> fix(ooniprobe): remove empty measurements directories

.github/workflows/alltests.yml, .github/workflows/android.yml, .github/workflows/coverage.yml, .github/workflows/generate.yml, .github/workflows/ios.yml, .github/workflows/jafar.yml, .github/workflows/macos.yml, .github/workflows/miniooni.yml, .github/workflows/netxlite.yml, .github/workflows/oohelperd.yml, .github/workflows/qafbmessenger.yml, .github/workflows/qahhfm.yml, .github/workflows/qahirl.yml, .github/workflows/qatelegram.yml, .github/workflows/qawebconnectivity.yml, .github/workflows/qawhatsapp.yml, .github/workflows/tarball.yml, .github/workflows/windows.yml, go.mod, go.sum, mk
See https://github.com/ooni/probe/issues/2100
=> chore: use go1.17.10

mk
See https://github.com/ooni/probe/issues/2100
=> chore(mk): update the version of the tools we use

internal/engine/httpheader/useragent.go
See https://github.com/ooni/probe/issues/2100
=> chore: update the user-agent used for measuring

internal/version/version.go
See https://github.com/ooni/probe/issues/2100
=> chore: we're now hacking on v3.16.0-alpha

.github/workflows/gosec.yml
Enable `gosec` tests on the pipeline. They are disabled by default (157 issues), and they tend to be a little noisy (will take some time to either address the issues or add reasoned ignores in the codebase). At the very least, `gosec` points at a bunch of unhandled errors. It also warns about possible vectors for file inclusion/code execution coming from unsanitized input that we might want to review further.
=> add gosec step

internal/netxlite/getaddrinfo_cgo.go, internal/netxlite/http.go, internal/netxlite/http_test.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go, internal/netxlite/resolverparallel.go, internal/netxlite/resolverserial.go, internal/tracex/event_test.go, internal/tracex/quic_test.go, internal/tracex/resolver_test.go, internal/tracex/tls_test.go
This diff improves testing and increases coverage inside the
./internal/netxlite and ./internal/tracex packages.
See https://github.com/ooni/probe/issues/2121
=> chore: improve testing and increase coverage

internal/engine/internal/sessionresolver/childresolver.go, internal/engine/internal/sessionresolver/childresolver_test.go
See https://github.com/ooni/probe/issues/2135#issuecomment-1149840579
=> hotfix(sessionresolver): prevent data race inside http3

internal/cmd/oohelper/oohelper.go, internal/cmd/oohelperd/oohelperd.go, internal/engine/session.go, internal/netxlite/dnsoverhttps.go, internal/netxlite/dnsoverhttps_test.go, internal/netxlite/http.go, internal/netxlite/http3.go, internal/netxlite/http3_test.go, internal/netxlite/http_test.go
These factories will soon be useful to finish with
https://github.com/ooni/probe/issues/2135.
=> refactor(netxlite): expose useful HTTPTransport/DNSTransport factories

docs/design/dd-003-step-by-step.md, internal/engine/experiment/README.md, internal/model/README.md, internal/model/measurement.go
A few edits attempting to make the document more palatable.
=> doc(step-by-step): readability improvements 

.github/workflows/alltests.yml, .github/workflows/android.yml, .github/workflows/coverage.yml, .github/workflows/generate.yml, .github/workflows/ios.yml, .github/workflows/jafar.yml, .github/workflows/macos.yml, .github/workflows/miniooni.yml, .github/workflows/netxlite.yml, .github/workflows/oohelperd.yml, .github/workflows/qafbmessenger.yml, .github/workflows/qahhfm.yml, .github/workflows/qahirl.yml, .github/workflows/qatelegram.yml, .github/workflows/qawebconnectivity.yml, .github/workflows/qawhatsapp.yml, .github/workflows/tarball.yml, .github/workflows/windows.yml, mk
This work is functional to land a 3.15.2 release
containing https://github.com/ooni/probe/issues/2173.
=> chore: use go1.17.11

mk
I just completed a successful local build, so I'm assuming
everything is fine with this updated version.
This work is functional to land a 3.15.2 release
containing https://github.com/ooni/probe/issues/2173.
=> chore(mk): update the Android NDK version we use

.github/workflows/ios.yml
This work is functional to land a 3.15.2 release
containing https://github.com/ooni/probe/issues/2173.
=> chore(ios): use setup-xcode to select Xcode version

internal/cmd/miniooni/libminiooni.go, internal/cmd/miniooni/main.go, internal/oonirun/doc.go, internal/oonirun/experiment.go, internal/oonirun/experiment_test.go, internal/oonirun/session.go
This diff refactors the ./internal/cmd/miniooni pkg and moves the code
for running experiments inside of the ./internal/oonirun pkg.
It's the first concrete step towards https://github.com/ooni/probe/issues/2184.
=> feat: start sketching out the oonirun package

internal/engine/experiment/simplequicping/simplequicping.go, internal/engine/experiment/simplequicping/simplequicping_test.go, internal/measurexlite/conn.go, internal/measurexlite/conn_test.go, internal/measurexlite/quic.go, internal/measurexlite/quic_test.go, internal/measurexlite/tls.go, internal/measurexlite/tls_test.go, internal/measurexlite/trace.go, internal/measurexlite/trace_test.go, internal/model/archival.go, internal/model/mocks/trace.go, internal/model/mocks/trace_test.go, internal/model/netx.go, internal/netxlite/quic.go, internal/netxlite/trace.go
This diff refactors the `simplequicping` experiment to use the step-by-step measurement style
=> feat: simplequicping using step-by-step

internal/engine/experiment/dnsping/dnsping.go, internal/engine/experiment/dnsping/dnsping_test.go, internal/engine/experiment/dnsping/testkeys.go
=> feat: record delayed DNS responses in dnsping

internal/cmd/oohelperd/http.go, internal/engine/experiment/webconnectivity/httpanalysis.go, internal/experiment/webconnectivity/analysishttpdiff.go, internal/measurexlite/web.go, internal/measurexlite/web_test.go
Part of https://github.com/ooni/probe/issues/2240
=> refactor: move WebGetTitle inside measurexlite

internal/cmd/oohelperd/main.go
See the explanatory newly-added comment for more information.
Closes https://github.com/ooni/probe/issues/2064
=> fix(oohelperd): refuse to measure bogons

internal/version/version.go
Just a chore commit to increase the version given that we just tagged v3.16.0-alpha
=> chore: we're now hacking on v3.16.0-alpha.1

internal/version/version.go
Just a chore commit to increase the version given that we just tagged v3.16.0-alpha.1
=> chore: we're now hacking on v3.16.0-alpha.2

internal/cmd/oohelperd/handler.go, internal/cmd/oohelperd/metrics.go
This diff updates the metrics according to https://github.com/ooni/probe/issues/2183#issuecomment-1230327725
=> fix(oohelperd): metrics improvements after design review

docs/design/dd-004-minioonirunv2.md, internal/oonirun/doc.go
Closes https://github.com/ooni/probe/issues/2184
=> doc: document the minioonirunv2 experiment

internal/engine/experiment/dnscheck/dnscheck.go
Closes https://github.com/ooni/probe/issues/2234
=> fix(dnscheck): lower the default timeouts

.github/workflows/android.yml, .github/workflows/ios.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/oohelperd.yml, .github/workflows/tarball.yml, .github/workflows/windows.yml
Part of https://github.com/ooni/probe/issues/2249
=> feat(rolling): build fresh binaries every night

internal/tracex/http.go
This issue was mentioned in https://github.com/ooni/probe/issues/2137.
I double checked the spec and this field is not mentioned. We will
update it when we do https://github.com/ooni/probe/issues/2238.
=> fix(tracex): use HTTP transaction end time for `t`

.github/workflows/ghpublish.yml, .gitignore, script/ghpublish-branch.out.txt, script/ghpublish-pr.out.txt, script/ghpublish-prerelease.out.txt, script/ghpublish-release.out.txt, script/ghpublish.bash, script/ghpublish_test.bash, script/maketarball.bash
While there, include integration testing to make sure the script
is working as intended before using it.
=> feat(ghpublish): choose (pre)release depending on tag

internal/model/http.go
Part of https://github.com/ooni/probe/issues/2130
=> chore: upgrade user-agent used for measuring

internal/measurexlite/dialer.go, internal/measurexlite/dialer_test.go
See https://github.com/ooni/probe/issues/2254
=> fix(measurexlite): expose TCP connect event

internal/measurexlite/trace.go, internal/measurexlite/trace_test.go, internal/measurexlite/utls.go, internal/measurexlite/utls_test.go
This diff adds support for `uTLS` in `measurexlite`
=> feat: add uTLS support in measurexlite

go.mod, go.sum
See https://github.com/ooni/probe/issues/2262
=> chore: upgrade obfs4 to v0.0.14

go.mod, go.sum
Part of https://github.com/ooni/probe/issues/2130
=> chore: more dependencies updates

internal/measurexlite/dns.go, internal/measurexlite/dns_test.go
Part of https://github.com/ooni/probe/issues/2238
=> fix(measurexlite): emit resolve_start and resolve_done

internal/experiment/webconnectivity/cleartextflow.go, internal/experiment/webconnectivity/control.go, internal/experiment/webconnectivity/dnsresolvers.go, internal/experiment/webconnectivity/measurer.go, internal/experiment/webconnectivity/priority.go, internal/experiment/webconnectivity/secureflow.go, internal/experiment/webconnectivity/testkeys.go, internal/measurexlite/logger.go
Implements https://github.com/ooni/probe/issues/2276 and supersedes https://github.com/ooni/probe-cli/pull/949.
=> feat(webconnectivity@v0.5): get a webpage whenever possible

internal/engine/experiment.go, internal/model/measurement.go, internal/model/measurement_test.go
Part of https://github.com/ooni/probe/issues/2297
=> refactor(engine): scrub the whole measurement

internal/experiment/webconnectivity/analysiscore.go, internal/experiment/webconnectivity/measurer.go
See https://github.com/ooni/probe/issues/2300.
=> feat(webconnectivity@v0.5): detect TLS misconfig for probe and TH

internal/experiment/webconnectivity/cleartextflow.go, internal/experiment/webconnectivity/iox.go, internal/experiment/webconnectivity/measurer.go, internal/experiment/webconnectivity/secureflow.go, internal/netxlite/iox.go
Reference issue: https://github.com/ooni/probe/issues/2295
=> feat(webconnectivity@v0.5): stream the response body

internal/experiment/webconnectivity/analysiscore.go, internal/experiment/webconnectivity/measurer.go
See https://github.com/ooni/probe/issues/2308
=> feat(webconnectivity): detect residual DNS censorship

internal/model/measurement.go
See https://github.com/ooni/probe/issues/2319
=> cleanup: remove unneded annotation

internal/experiment/webconnectivity/cleartextflow.go, internal/experiment/webconnectivity/dnsresolvers.go, internal/experiment/webconnectivity/measurer.go, internal/experiment/webconnectivity/redirects.go, internal/experiment/webconnectivity/secureflow.go
Part of https://github.com/ooni/probe/issues/2237
=> fix(web_connectivity@v0.5): limit number of redirects

E2E/miniooni.bash, internal/cmd/apitool/main.go, internal/cmd/e2epostprocess/main.go, internal/engine/session.go
Closes https://github.com/ooni/probe/issues/2336
=> fix(E2E): ensure miniooni.bash is WAI

cmd/ooniprobe/internal/cli/list/list.go, cmd/ooniprobe/internal/cli/reset/reset.go, cmd/ooniprobe/internal/cli/rm/rm.go, cmd/ooniprobe/internal/cli/show/show.go, cmd/ooniprobe/internal/nettests/dnscheck.go, cmd/ooniprobe/internal/nettests/nettests.go, cmd/ooniprobe/internal/nettests/nettests_test.go, cmd/ooniprobe/internal/nettests/run.go, cmd/ooniprobe/internal/nettests/stunreachability.go, cmd/ooniprobe/internal/nettests/web_connectivity.go, cmd/ooniprobe/internal/ooni/ooni.go, cmd/ooniprobe/internal/oonitest/oonitest.go, internal/database/actions.go, internal/database/actions_test.go
This diff introduces a `Database` type struct which allows us to consolidate database behavior and abstract to an interface easily. It should also allows us to introduce a `NullDatabase` in the future.
=> feat: introduce database type 

internal/engine/inputloader.go, internal/model/ooapi.go
Part of https://github.com/ooni/probe/issues/2372
=> refactor(model): improve ooapi.go documentation

internal/runtimex/runtimex_test.go
Just a minor refactor for consistency with other packages. No functional change.
=> refactor(runtimex): use internal testing

internal/scrubber/scrubber.go, internal/scrubber/scrubber_test.go
See https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/merge_requests/113
=> scrubber: sync with snowflake's upstream

internal/engine/checkincache.go, internal/engine/checkincache_test.go, internal/engine/session.go, internal/engine/session_internal_test.go, internal/model/ooapi.go, internal/registry/factory.go
See https://github.com/ooni/probe/issues/2396
=> feat: enable A/B testing using check-in API

cmd/ooniprobe/internal/autorun/autorun_darwin.go, cmd/ooniprobe/internal/utils/paths.go, internal/cmd/miniooni/consent.go, internal/cmd/miniooni/utils.go, internal/cmd/oonireport/oonireport.go, internal/cmd/oonireport/oonireport_test.go, internal/fsx/fsx.go, internal/fsx/fsx_test.go
Part of https://github.com/ooni/probe/issues/2401
=> refactor: factor common code to check whether file exists

Makefile, internal/cmd/buildtool/android.go, internal/cmd/buildtool/android_test.go, internal/cmd/buildtool/builddeps.go, internal/cmd/buildtool/cdeps.go, internal/cmd/buildtool/cdepslibevent.go, internal/cmd/buildtool/cdepsopenssl.go, internal/cmd/buildtool/cdepstor.go, internal/cmd/buildtool/golang.go, internal/cmd/buildtool/gomobile.go, internal/cmd/buildtool/internal/buildtoolmodel/buildtoolmodel.go, internal/cmd/buildtool/internal/buildtooltest/buildtooltest.go, internal/cmd/buildtool/linuxdocker.go, internal/cmd/buildtool/main.go, internal/fsx/fsx.go, internal/fsx/fsx_test.go
See https://github.com/ooni/probe/issues/2401
=> feat: rewrite the android build in Go

internal/cmd/buildtool/android.go, internal/cmd/buildtool/android_test.go, internal/cmd/buildtool/internal/buildtooltest/buildtooltest.go
See https://github.com/ooni/probe/issues/2365
=> feat(buildtool): add unit tests for android builds

.github/workflows/android.yml, Makefile, internal/cmd/buildtool/android.go, internal/cmd/buildtool/android_test.go, internal/cmd/buildtool/gomobile.go, internal/cmd/buildtool/ios_test.go, internal/cmd/ghgen/android.go, internal/libtor/enabled.go, internal/tunnel/torembed.go, internal/tunnel/tormobile.go
Part of https://github.com/ooni/probe/issues/2365
=> feat: use internal/libtor for android builds

internal/cmd/buildtool/android.go, internal/cmd/buildtool/builddeps.go, internal/cmd/buildtool/cdepslibevent.go, internal/cmd/buildtool/cdepsopenssl.go, internal/cmd/buildtool/cdepstor.go, internal/cmd/buildtool/cdepszlib.go, internal/cmd/buildtool/linuxdocker.go, internal/cmd/buildtool/linuxstatic.go, internal/cmd/buildtool/main.go, internal/cmd/buildtool/product.go, internal/cmd/buildtool/windows.go
Part of https://github.com/ooni/probe/issues/2273
=> doc(buildtool): explain ANDROID_NDK_HOME for android gomobile

internal/netxlite/getaddrinfo_cgo.go
Closes https://github.com/ooni/probe/issues/2293
=> fix(getaddrinfo): canonicalize the CNAME

internal/tunnel/torembed.go, internal/tunnel/tormobile.go
See https://github.com/ooni/probe/issues/2405#issuecomment-1416088377
=> fix(torembed): use embedded control conn 

internal/model/ooapi.go
Part of https://github.com/ooni/probe/issues/2372
=> fix(model): get TH info from check-in API

internal/mlablocatev2/mlablocatev2.go, internal/mlablocatev2/mlablocatev2_test.go
Part of https://github.com/ooni/probe/issues/2398
=> feat(mlablocatev2): add support for dash

internal/experiment/dash/collect.go, internal/experiment/dash/download.go, internal/experiment/dash/fake_test.go, internal/experiment/dash/negotiate.go, internal/experiment/dash/runner.go
Yak shaving for https://github.com/ooni/probe/issues/2398
=> cleanup(dash): use http.NewRequestWithContext

internal/experiment/dash/collect.go, internal/experiment/dash/collect_test.go, internal/experiment/dash/download.go, internal/experiment/dash/download_test.go, internal/experiment/dash/locate.go, internal/experiment/dash/negotiate.go, internal/experiment/dash/negotiate_test.go, internal/experiment/dash/runner.go, internal/experiment/dash/runner_test.go
See https://github.com/ooni/probe/issues/2398
Closes https://github.com/ooni/probe-cli/pull/1084
=> feat(dash): use @m-lab locate API v2

internal/experiment/dash/measurer.go, internal/experiment/dash/runner.go, internal/experiment/dash/runner_test.go
The new name is cleaner.
Part of https://github.com/ooni/probe/issues/2398
=> refactor(dash): runner -> runnerConfig

internal/cmd/oohelperd/dns.go, internal/cmd/oohelperd/dns_test.go
Part of https://github.com/ooni/probe/issues/2413
=> fix(oohelperd): better unit tests for dnsDo

internal/cmd/oohelperd/main.go
I also added an endpoint for obtaining execution traces.
See https://github.com/ooni/probe/issues/2413
=> feat(oohelperd): serve CPU profiles using HTTP

internal/cmd/miniooni/main.go
Noticed while testing https://github.com/ooni/probe/issues/2411
=> fix(miniooni): report current time in UTC

internal/netxlite/classify.go, internal/netxlite/classify_test.go, internal/netxlite/integration_test.go
Closes https://github.com/ooni/probe/issues/2419
=> fix(netxlite): handle "tls: unrecognized name" alert

internal/experiment/webconnectivitylte/iox.go, internal/experiment/webconnectivitylte/measurer.go
Closes https://github.com/ooni/probe/issues/2434
=> fix(webconnectivitylte): avoid data race

.github/workflows/alltests.yml, .github/workflows/android.yml, .github/workflows/checks.yml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yml, .github/workflows/debianrepo.yml, .github/workflows/generate.yml, .github/workflows/ghpublish.yml, .github/workflows/gosec.yml, .github/workflows/ios.yml, .github/workflows/jafar.yml, .github/workflows/libtorlinux.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/netxlite.yml, .github/workflows/oohelperd.yml, .github/workflows/qa.yml, .github/workflows/tarball.yml, .github/workflows/windows.yml, internal/cmd/ghgen/config.go, internal/cmd/ghgen/utils.go
This diff updates the github actions and os versions used for workflows.
=> update github actions to latest version

internal/dslx/httpcore.go, internal/dslx/integration_test.go, internal/throttling/throttling_test.go
Part of https://github.com/ooni/probe/issues/2493
=> feat(dslx): collect speed samples

MONOREPO/README.md, MONOREPO/w/build-android-stable.bash
Useful to implement https://github.com/ooni/probe/issues/2504
=> feat(MONOREPO): script to build stable android release 

go.mod, go.sum, internal/experiment/webconnectivitylte/analysiscore.go, internal/experiment/webconnectivitylte/analysisdns.go, internal/experiment/webconnectivitylte/analysisdns_test.go, internal/experiment/webconnectivitylte/measurer.go, internal/experiment/webconnectivitylte/testdata/20230706183840.201925_PK_webconnectivity_19f5e0d803cbaea7.jsonc, internal/mocks/geoip.go, internal/mocks/geoip_test.go, internal/model/geoip.go, internal/model/geoip_test.go, internal/model/location.go, pkg/oonimkall/xoonirun_test.go
This commit introduces a test case that illustrates https://github.com/ooni/probe/issues/2517.
While there, fix an `xoonimkall_test.go` that was broken after we updated the data model.
=> webconnectivitylte: add test case for ooni/probe#2517

internal/experiment/webconnectivity/qa_test.go, internal/experiment/webconnectivityqa/session.go, internal/experiment/webconnectivityqa/session_test.go, internal/experiment/webconnectivityqa/tlsblocking.go
Part of https://github.com/ooni/probe/issues/2525
=> feat(webconnectivity): add webconnectivityqa-based tests

internal/netemx/example_test.go, internal/netemx/scenario.go
This diff takes advantage of all the refactoring performed so far to expose Do53 (aka DNS-over-UDP) along with DoH (DNS-over-HTTPS).
Additionally, we extend the test suite to verify we're always exposing the two protocols side by side for public, well-known DNS resolvers.
=> feat(netemx): instantiate Do53 along with DoH

QA/webconnectivity.py, go.mod, go.sum, internal/experiment/webconnectivity/qa_test.go, internal/experiment/webconnectivitylte/qa_test.go, internal/experiment/webconnectivityqa/redirect.go, internal/experiment/webconnectivityqa/redirect_test.go, internal/experiment/webconnectivityqa/testcase.go, internal/experiment/webconnectivityqa/tlsblocking.go, internal/experiment/webconnectivityqa/tlsblocking_test.go
This diff moves test cases from QA/webconnectivity.py to the ./internal/webconnectivityqa package.
=> feat(webconnectivityqa): convert more jafar test cases

QA/webconnectivity.py, internal/experiment/webconnectivityqa/httpdiff.go, internal/experiment/webconnectivityqa/httpdiff_test.go, internal/experiment/webconnectivityqa/testcase.go, internal/netemx/example_test.go, internal/netemx/oohelperd_test.go, internal/netemx/web.go
This diff ports jafar's http-diff test cases to webconnectivityqa.
=> feat(webconnectivityqa): port jafar's http-diff test cases

internal/testingx/closeverify.go, internal/testingx/closeverify_test.go
This feature will be useful for extra tests I would like to write for https://github.com/ooni/probe/issues/2531.
=> feat(testingx): add code to ensure we close all conns

internal/enginenetx/httpsdialerstatic.go, internal/enginenetx/httpsdialerstatic_test.go, internal/enginenetx/network.go, internal/enginenetx/network_test.go
While there, change the file name to ensure it's clear this policy is static and we are not going to use stats to modify it.
=> feat(enginenetx): honor user-provided policy

internal/model/archival_test.go
I am about to modify this structure to unconditionally use ArchivalBinaryData rather than ArchivalMaybeBinaryData, following the plan that I explained in https://github.com/ooni/probe-cli/pull/1319.
Before doing that, I want MORE test coverage for ArchivalTLSOrQUICHandshakeResult.
=> chore(model): add tests for ArchivalTLSOrQUICHandshakeResult

internal/version/version.go
Part of https://github.com/ooni/probe/issues/2524
=> chore: we're now hacking on v3.20.0-alpha

internal/experiment/webconnectivitylte/analysishttpcore.go
See https://github.com/ooni/probe/issues/2641
=> doc(webconnectivitylte): document "orig" HTTP analysis bug

internal/version/version.go
Part of https://github.com/ooni/probe/issues/2556
=> chore: we're now hacking on v3.21.0-alpha

internal/cmd/minipipeline/main.go, internal/cmd/qatool/main.go, internal/experiment/webconnectivitylte/analysisclassic.go, internal/minipipeline/analysis.go, internal/minipipeline/qa_test.go
This is yak shaving for https://github.com/ooni/probe/issues/2640.
=> refactor(minipipeline): allow avoiding linear analysis

internal/cmd/minipipeline/main.go, internal/cmd/qatool/main.go, internal/experiment/webconnectivitylte/analysisclassic.go, internal/experiment/webconnectivitylte/analysisclassic_test.go, internal/experiment/webconnectivitylte/analysisext.go, internal/minipipeline/analysis.go, internal/minipipeline/dnsdiff.go, internal/minipipeline/observation.go, internal/minipipeline/observation_test.go, internal/minipipeline/qa_test.go, internal/minipipeline/utils.go
This diff ensures that we do not lose any comment or test that we removed in https://github.com/ooni/probe-cli/pull/1455 and rather aims to ensure we have equivalent tests and comments.
Part of https://github.com/ooni/probe/issues/2652.
=> feat(webconnectivitylte): add more tests and comments

internal/bytecounter/context.go, internal/bytecounter/dialer.go, internal/bytecounter/resolver.go, internal/bytecounter/resolver_test.go, internal/measurexlite/bytecounting_test.go, internal/measurexlite/dialer.go, internal/measurexlite/dns.go, internal/measurexlite/dns_test.go, internal/measurexlite/quic.go
Closes https://github.com/ooni/probe/issues/2655
=> fix(webconnectivitylte): count bytes sent and received

internal/engineresolver/resolvermaker.go
Closes https://github.com/ooni/probe/issues/2532
=> feat(engineresolver): add wikimedia DNS

internal/experiment/webconnectivitylte/measurer.go, internal/webconnectivityqa/checker.go, internal/webconnectivityqa/checker_test.go, internal/webconnectivityqa/success.go
Closes https://github.com/ooni/probe/issues/2676
=> fix(webconnectivitylte): include client_resolver

.github/workflows/gobash.yml
See https://github.com/ooni/probe/issues/2690
=> doc(gobash.yml): explain what to do during releases

internal/experiment/torsf/integration_test.go
See https://github.com/ooni/probe/issues/2692
=> fix(torsf): disable integration tests

internal/version/version.go
See https://github.com/ooni/probe/issues/2690
=> chore: we're now hacking on v3.22.0-alpha

internal/cmd/miniooni/javascript.go, internal/cmd/miniooni/main.go, internal/cmd/miniooni/main_test.go, internal/cmd/miniooni/session.go
Closes https://github.com/ooni/probe/issues/2691
=> feat(miniooni): add --software-name and --software-version

internal/experiment/quicping/quic.go
=> fix obvious typo in quicping experiment

internal/cmd/oohelper/internal/client.go, internal/netemx/ooapi.go, internal/netemx/oohelperd_test.go, internal/oohelperd/handler.go, internal/oohelperd/handler_test.go, internal/oohelperd/measure.go, internal/oohelperd/qa_test.go
Closes https://github.com/ooni/probe/issues/2706.
=> fix(oohelperd): disable QUIC by default

internal/version/version.go
See https://github.com/ooni/probe/issues/2722
=> chore: we're now hacking on v3.23.0-alpha

docs/design/dd-008-richer-input.md
I noticed the document has not been updated to mention that @DecFox serviced several reviews for it.
=> dd-008-richer-input: mention @DecFox reviews

CODEOWNERS
I am stepping down from my position at OONI and so it is the proper time to remove myself from this file.
No functional change.
=> CODEOWNERS: remove @bassosimone

internal/cmd/buildtool/android_test.go, internal/cmd/buildtool/cdepsopenssl.go, internal/cmd/buildtool/cdepstor.go, internal/cmd/buildtool/ios_test.go, internal/cmd/buildtool/linuxcdeps_test.go
This diff updates the engine C dependencies.
=> chore: update C dependencies

internal/version/version.go
We are now hacking on `v3.24.0-alpha`
=> chore: update internal version to v3.24.0-alpha

internal/cmd/buildtool/cdepsopenssl.go, internal/cmd/buildtool/cdepstor.go, internal/cmd/buildtool/linuxcdeps_test.go
This diff updates the engine C dependencies.
=> chore: upgrade C dependencies

internal/version/version.go
we are now hacking on `v3.25.0-alpha`
=> chore: we are now hacking on 3.25.0-alpha

.github/ISSUE_TEMPLATE/routine-sprint-releases.md
=> Add issue template for releases of the engine

internal/model/http.go
This diff updates the user-agent to the most widely used agent as of 2025-02-09
=> chore: update user-agent

internal/registry/factory_test.go
This diff address go report card comments.
=> chore: address go report card comments

go.mod
This diff updates the go toolchain to `1.22.3`
=> chore: update toolchain to go1.22.3

go.mod, go.sum
This upgrades probe-assets to the latest version (`v0.27.0`).
=> chore: upgrade probe-assets to v0.27.0

pkg/oonimkall/taskmodel.go, pkg/oonimkall/taskrunner.go
This should fix the gofmt errors we see in the go report card
=> fix: go fmt errors
