.travis.yml
There is a trade off between correctness and wasting one's time.
We have already determined that we want to rewrite all of the OONI
engine in Go because maintaining a C++ codebase across all these
systems and platforms is a burden. This is a policy decision that
we have taken and it should inform our subsequent choices.
We are already spending time rewriting the engine because that is
what will make our future burden smaller.
In this vein, wrestling with the Travis CI macOS build that does
not build because there are many moving parts everywhere is a
challanging task and possibly also a waste of our time.
Both @hellais and @bassosimone use macOS as their main development
environment. So, if things are spectacularly wrong on macOS they
are going to notice, quite likely.
For both of them, …
=> travis: remove macOS from the build

internal/cli/list/list.go, internal/cli/show/show.go, internal/database/actions.go, internal/util/util.go
1. the description of the command and the helper function are
clear hints that the command is intended to show a single JSON
measurement at a time (also the use case seems clear) [*]
2. the function used to read lines was failing for all my
measurements that take input. Since that was not the optimal
pattern anyway, use a better pattern to fix it.
3. some changes are automatically applied by my editor (VSCode
with the Go plugin) and I am fine with them.
4. while reading code, I also applied my preferred pattern
wrt whitespaces, i.e.: no whitespace inside functions, if a
function feels too long in this way, just break it.
Closes #57
[*] Even if we want to show many measurements at a time, which
does not seem needed, given the UI patterns, this functionality
won't be P0. What is P0 is to …
=> Make sure `ooniprobe show <id>` is WAI

internal/log/handlers/cli/cli.go, internal/output/output.go, nettests/nettests.go
This is needed by the desktop app which currently uses a hardcoded 60 second default for the ETA.
=> Add support for calculating the estimate time remaining

build.sh
* don't include psiphon until we need it
* strip the binaries
=> build.sh: produce smaller binaries

build.sh
To test this, I'll create a fake release locally and make sure
the resulting binary is much larger. If you see this commit landing
on a PR, then it means I successfully run this check.
Closes #79
=> build.sh: re-enable psiphon

internal/cli/run/run.go, nettests/nettests.go, ooni.go
=> Handle the SIGINT and SIGTERM signals to support stopping a test cleanly

internal/cli/root/root.go, nettests/nettests_test.go, ooni.go, ooni_test.go
In turn, this allows us to identify as ooniprobe-cli v3.0.0-rc.5.
Closes #41.
=> Allow to specify custom software name and version

internal/log/handlers/cli/results.go, nettests/psiphon.go
This add support for exposing additional metadata in the psiphon test results.
See:
=> Improve the output and extraction of psiphon metrics

internal/cli/run/run.go
Tentative fix for: https://github.com/ooni/probe/issues/1005
=> Explicitly handle SIGINT

nettests/nettests.go
Closes https://github.com/ooni/probe-engine/issues/316
Rationale: a measurement may fail for a bunch of reasons including
buts in the code. The original determination was that we won't
return an error from the measurement in case of anomaly. But doing
that is error prone, and indeed the Psiphon experiment was not
following this pattern. I claim that this pattern was wrong, and
it's much more in our interest to submit and store on disk anything
that we get from a measurement. This data can be useful to look
into bugs, as well as to discover novel anomalies we didnt' anticipate.
=> nettests.go: don't stop when measurement is failed

internal/cli/run/run.go, ooni.go
On Unix, Node.js allows us to gracefully kill a process. On Windows
this is more compex. You certainly cannot rely on the default `kill()`
function, which calls `TerminateProcess`.
There is a bunch of C/C++ extensions that in principle allow you to
attempt to gracefully shutdown a Windows process.
But, hey, here's a reality check. Node.js controls our stdin. Node.js
does IPC easy. Controlling uv_spawn flags and using the right not well maintained
C/C++ Node.js extension to kill a process is fragile.
So, treat EOF and any other error on stdin as equivalent to SIGTERM.
However, systemd.
The sane thing to do with systemd is `StandardInput=null`. With such
configuration, stdin immediately returns EOF.
Then, introduce the `OONI_STDIN_EOF_IMPLIES_SIGTERM` environment
variable. When it is …
=> Optionally treat EOF on stdin just like SIGTERM

ooni.go
Using a 64 bit counter has pitfalls. See Go documentation.
I don't want a refactoring or whatever to let these pitfalls
emerge in the future.
We just need one bit to signal we're done.
So use 32 bit, which shall be safe everywhere.
See https://golang.org/pkg/sync/atomic/#pkg-note-BUG.
Proactively triggered by https://github.com/ooni/probe-engine/issues/399.
=> ooni.go: use 32 bit counter to signal interruption

build.sh
When I was trying to build the cli for the very first time I typed build.sh --help and the output was confusing on the first glance
```
+ git describe --tags
+ v=v3.0.8-2-g10c806b
+ echo Usage: ./build.sh darwin|linux|macos|windows|release
Usage: ./build.sh darwin|linux|macos|windows|release
+ echo 
+ echo You need a C compiler and Go >= 1.14. The C compiler must be a
You need a C compiler and Go >= 1.14. The C compiler must be a
+ echo UNIX like compiler like GCC, Clang, Mingw-w64.
UNIX like compiler like GCC, Clang, Mingw-w64.
+ echo 
+ echo To build a static Linux binary, we use Docker and Alpine.
To build a static Linux binary, we use Docker and Alpine.
+ echo 
+ echo You can cross compile for Windows from macOS or Linux. You can
You can cross compile for Windows from macOS or Linux. …
```
=> turn off printing of each command in the help section

internal/log/handlers/cli/results.go
Comes up when there are no results to show.
```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Results                  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━┛
No results
Try running:
ooni run websites
```
=> Replace ooni with ooniprobe in example usage

go.mod, go.sum, internal/version/version.go
I need to bless 3.0.11 now to pin to ooni/probe-engine v0.20.2.
=> chore: set version to 3.0.12-alpha

internal/cli/geoip/geoip.go, internal/cli/geoip/geoip_test.go, internal/cli/info/info.go, internal/cli/info/info_test.go, internal/cli/list/list.go, internal/cli/onboard/onboard.go, internal/cli/reset/reset.go, internal/cli/rm/rm.go, internal/cli/root/root.go, internal/cli/run/run.go, internal/cli/show/show.go, internal/nettests/nettests.go, internal/nettests/nettests_test.go, internal/nettests/web_connectivity.go, internal/ooni/ooni.go, internal/oonitest/oonitest.go
This diff starts increasing the code coverage in some parts of the codebase. The general approach is that of adding some extra abstraction that allows us to mock what's happening in all internal/cli packages. Until this refactoring for testability process is complete, we will have a bit of duplication. Yet, doing everything in a single step requires us to write a too large diff and seems not the right approach here. This work is part of https://github.com/ooni/probe/issues/948.
There are two reasons why I'm starting to refactor the code base now. The first is that the code is now settled for quite some time and it's more or less clear what are our needs, so the time seems ripe to add tests to ensure we WAI. The second is that I am planning on further integrating probe-cli and …
=> Start increasing testing and code coverage

internal/cli/onboard/onboard.go, internal/output/output.go
When the input is /dev/null, every read returns EOF. In general, it
may also happen that read doesn't work as intended. So, the robust thing
to do here is to ensure that we check the return values. By doing that
we notice of io.EOF errors and we don't proceed with the onboarding.
This diff fixes the issue described by https://github.com/ooni/probe/issues/1281
however it may be that we also want (in the near or not-so-near future)
to stop onboarding if the input terminal is not a tty. This is however a
possible future evolution that should not prevent us for committing and
merging this simple fix that unblocks creating a Debian package.
=> fix(onboard): fail if input is /dev/null

go.mod, go.sum, internal/nettests/web_connectivity.go
This diff pins to ooni/probe-engine@3049779878bf6858def6514119b392c19f09d985
and starts using the recently introduced probe-engine APIs.
Namely, here, we use the InputLoader for loading URLs.
I've confirmed manually everything is still working as intended.
Part of https://github.com/ooni/probe/issues/1283.
(In particular, the InputLoader is the abstraction allowing us to load
input from several sources, including command line flags and external
files.)
=> refactor(webconnectivity): use engine.InputLoader

internal/cli/run/run.go, internal/nettests/nettests.go, internal/nettests/web_connectivity.go
This diff introduces the possibility of specifying --input-file file
multiple times to force ooniprobe to read inputs from file.
Like we do for miniooni, the file shall contain a single entry per
line and this entry should be a URL for websites.
Likewise, one can specify --input URL multiple times.
This implementation is a very simple, initial implementation and there
is a bunch of changes I'd like to add on top of it.
And also perhaps a bunch of cleanups.
I've chosen to expose these flag _only_ for websites for now.
Part of https://github.com/ooni/probe/issues/1283.
=> feat(cli/run): read inputs from file/cmdline

cmd/ooniprobe/main.go, internal/cli/root/root.go, internal/log/handlers/syslog/syslog.c, internal/log/handlers/syslog/syslog.go
With this functionality in tree, macOS users could easily access ooniprobe logs by filtering by process name in the console app. See https://github.com/ooni/probe-cli/pull/181#issuecomment-736508139 for a nice screenshot.
Part of https://github.com/ooni/probe/issues/1289
=> feat: implement syslog logging

internal/cli/run/run.go, internal/nettests/groups.go, internal/nettests/run.go
We don't want to run performance in the background because this
causes too much traffic towards m-lab servers.
When we'll have the check-in API, this will be the entry point we'll
use to contact such an API and get things to do.
Part of https://github.com/ooni/probe/issues/1289.
=> feat: implement the unattended group

internal/nettests/groups.go, internal/nettests/riseupvpn.go
* adds RiseupVPN to the circumvention suite
* depending on https://github.com/ooni/probe-engine/pull/1051
* ref issue: https://github.com/ooni/probe-engine/issues/1060
=> Exposed riseupvpn test

internal/version/version.go
This release only contains updates in debian packaging. All other platforms
could safely continue to use 3.2.0 or 3.3.0.
I didn't want to make a path release, though, because I didn't want to convey
the meaning that something was fixed.
Related to https://github.com/ooni/ooni.org/issues/677
=> chore: release 3.4.0

internal/engine/experiment/riseupvpn/riseupvpn_test.go
Part of https://github.com/ooni/probe/issues/1335.
Tracked also by https://github.com/ooni/probe/issues/1338.
=> fix(riseupvpn): skip currently failing tests

.github/workflows/cross.yml
Part of https://github.com/ooni/probe/issues/1335.
Motivation: we want all workflows to be green only when we are
approaching a release. It's fine if some less core tests are
failing during the development process. We have daily builds anyway
so we know of new breakages the day after, which is OK.
=> fix(cross.yml): only run on the release branch

internal/engine/experiment/riseupvpn/riseupvpn_test.go
This reverts commit 43f95e2c9a57e227dba35b3060fe56d6c56b0967.
We can now safely close https://github.com/ooni/probe/issues/1338,
since the upstream issue is gone. I think this issue we have seen is
also possibly related to https://github.com/ooni/probe/issues/1348.
Cc: @cyberta.
=> Revert "fix(riseupvpn): skip currently failing tests (#212)"

internal/engine/netx/httptransport/saver.go, internal/engine/netx/httptransport/saver_internal_test.go
See https://github.com/ooni/probe-engine/issues/1191
=> fix(http body saver): properly deal with EOF terminated bodies

internal/libminiooni/libminiooni.go
This is useful when someone is running manual measurements and is
sharing their measurements with us, because it means we don't need
manually keep track of this bit of information.
Closes https://github.com/ooni/probe-engine/issues/1194
=> chore(miniooni): print start time

Readme.md, internal/engine/experiment/riseupvpn/riseupvpn_test.go, internal/version/version.go
While there, make sure we don't always skip a currently failing
riseupvpn test, and slightly clarify the readme.
=> chore: set version to 3.7.0-alpha

cmd/ooniprobe/internal/cli/run/run.go
We already have a short run unattended on macOS and we wanna do
the same for Windows. See https://github.com/ooni/probe/issues/1377.
=> fix(run): run unattended short also on Windows

cmd/ooniprobe/internal/cli/run/run.go, cmd/ooniprobe/internal/log/handlers/cli/results.go, cmd/ooniprobe/internal/nettests/dnscheck.go, cmd/ooniprobe/internal/nettests/groups.go, cmd/ooniprobe/internal/nettests/signal.go, cmd/ooniprobe/internal/nettests/stunreachability.go
We move signal into the experimental nettests group. While there,
also start adding dnscheck and stunreachability as well.
It seems there's more work to be done to correctly represent
the results of dnscheck, but this is fine!
The experimental section is here exactly for this reason!
In terms of UI, the new command is `ooniprobe run experimental`.
We will most likely move signal out of experimental soon, since it's
already working quite well. We need to keep it here for one more
cycle because the desktop app is not ready for it.
See the following issues:
1. https://github.com/ooni/probe/issues/1378
2. https://github.com/ooni/probe/issues/1262
=> refactor: signal et al. are now experimental nettests

internal/version/version.go
This comes just a few days after 3.6.0. It contains small
improvements required by ooni/probe-desktop.
For this reason, I am going to skeep the normal release
process and I am just bumping the version number.
=> chore: release 3.7.0

internal/engine/internal/sessionresolver/resolvermaker.go, internal/engine/internal/sessionresolver/sessionresolver.go, internal/engine/internal/sessionresolver/sessionresolver_test.go, internal/engine/session.go
In reality, we are not going to use the sessionresolver when we're
using a proxy (I just tested). But, it nonetheless feels a lot more
robust to write a correct sessionresolver that handles the proxy
in the most correct way. That is, the sessionresolver will now skip
all the entries that cannot use a socks5 proxy (including among them
also the system resolver). What's more, it will construct a child
resolver that propagates the proxy.
We have confidence that this holds true because we have added a test
ensuring that we are really using the configured proxy.
See https://github.com/ooni/probe/issues/1381
=> fix(sessionresolver): honour the proxy

internal/engine/geolocate/geolocate.go, internal/engine/geolocate/geolocate_test.go, internal/engine/geolocate/iplookup.go, internal/engine/geolocate/iplookup_test.go, internal/engine/geolocate/stun.go, internal/engine/session.go
The use case of --proxy is that you cannot contact the OONI
backend otherwise. It is wrong, though, using the proxy when
discovering our IP address. The measurement won't use the
proxy anyway. Therefore, we need to use the IP address that
is performing the measurement. Not the one of the proxy.
What's more, stun is not using a proxy. Therefore, it does
not make much sense that http IP resolvers use a proxy. This
leads to inconsistencies. So, here's anothe reason why this
patch is a good thing (TM).
Finally, because knowing the IP address enables us to sanitize
the data, it's important we discover the correct IP.
Now, up until this point, the `--proxy` option has mostly
been a developers toy. But, users have asked us to have the
possibility of configuring a proxy.
This explains why I have …
=> fix(geolocate): no proxy when discovering our IP address

internal/engine/experiment/stunreachability/stunreachability.go
This fix addresses the bug described in issue https://github.com/ooni/probe/issues/1403.
=> fix(stunreachability): avoid goroutine spin and memleak

cmd/ooniprobe/internal/log/handlers/batch/batch.go, cmd/ooniprobe/internal/log/handlers/cli/cli.go
Rationale explained in detail in a documentation comment.
Reference issue: https://github.com/ooni/probe/issues/1384.
=> fix(ooniprobe): send batch output to stdout

internal/engine/inputloader_test.go, internal/engine/internal/mockable/mockable.go, internal/engine/model/experiment.go, pkg/oonimkall/task_integration_test.go
We use ExperimentOrchestraClient in several places to help us
calling probe-services APIs. We need to call CheckIn because we
want to use CheckIn in InputLoader.
(We also want to remove the URLs API, but that is not something
doable now, since the mobile app is still using this API via
the wrappers at pkg/oonimkall.)
Work part of https://github.com/ooni/probe/issues/1299.
=> feat(ExperimentOrchestraClient): add CheckIn

internal/engine/internal/sessionresolver/resolvermaker.go, internal/engine/internal/sessionresolver/sessionresolver.go, internal/engine/internal/sessionresolver/sessionresolver_test.go
There was a face-palming error in the implementation causing the proxy
check to be implemented also without a proxy.
This meant that we were ALWAYS skipping http3 and system resolvers.
The bug has been introduced in 3.8.0. So, the currently released
version of the probe, sadly, has this beheavior :-(.
Reference issue https://github.com/ooni/probe/issues/1426.
=> fix(sessionresolver): proxy check conditional on existing proxy

internal/engine/experiment.go, internal/engine/session.go, internal/engine/session_integration_test.go, internal/engine/session_internal_test.go, pkg/oonimkall/session.go, pkg/oonimkall/session_integration_test.go, pkg/oonimkall/task_integration_test.go
It seems to me the right thing to do is to query the CheckIn API
from the Session rather than querying it from InputLoader.
Then, InputLoader could just take a reference to a Session-like
interface that allows this functionality.
So, this diff exposes the Session.CheckIn method.
Doing that, in turn, required some refactoring to allow for
more and better unit tests.
While doing that, I also noticed that Session required a mutex
to be a well-behaving type, so I did that.
While doing that, I also tried to cover all the lines in session.go
and, as part of that, I have removed unused code.
Reference issue: https://github.com/ooni/probe/issues/1299.
=> feat(session): expose CheckIn method

internal/engine/inputloader.go, internal/engine/inputloader_test.go, internal/engine/internal/fsx/fsx.go, internal/engine/internal/fsx/fsx_test.go
Occurred to me while working on https://github.com/ooni/probe/issues/1299.
=> fix(internal/fsx): remove pre Go 1.16 definitions

cmd/ooniprobe/internal/config/settings.go, cmd/ooniprobe/internal/config/testdata/valid-config.json, cmd/ooniprobe/internal/nettests/nettests.go, cmd/ooniprobe/internal/nettests/run.go, cmd/ooniprobe/internal/nettests/web_connectivity.go, cmd/ooniprobe/internal/ooni/default-config.json, cmd/ooniprobe/testdata/testing-config.json, debian/ooniprobe.conf.disabled
We cannot control anymore the maximum number of URLs using the API
because now we are using check-in, that has no such limit.
We could theoretically clamp the number of URLs to measure after
the call to check-in, and still honour the setting.
Yet, the right thing to do seems to introduce a max runtime variable
because that is what desktop and mobile do.
Thus, introduce code that warns the user about the change in the
settings, should they have set the URL limit to nonzero.
We are going to do a best effort conversion from the URL limit to
the maximum runtime for the rest of 2021.
Since then, we will silently ignore the URL limit.
This work is part of https://github.com/ooni/probe/issues/1299.
=> feat(ooniprobe): introduce websites_max_runtime

cmd/ooniprobe/internal/cli/run/run.go, cmd/ooniprobe/internal/nettests/nettests.go, cmd/ooniprobe/internal/nettests/run.go, cmd/ooniprobe/internal/nettests/web_connectivity.go
This diff propagates the RunType CheckIn hint such that we run
using less URLs when running in the background.
Part of https://github.com/ooni/probe/issues/1299.
=> feat(ooniprobe): propagate the RunType CheckIn hint

cmd/ooniprobe/internal/nettests/nettests.go
Part of https://github.com/ooni/probe/issues/1299
=> fix(ooniprobe): disable maxRuntime when in the background

cmd/ooniprobe/internal/utils/utils.go, internal/engine/experiment/riseupvpn/riseupvpn_test.go, internal/engine/experiment/tlstool/internal/splitter.go, internal/engine/inputloader.go, internal/engine/legacy/netx/dialer_test.go, internal/engine/legacy/netx/modelx/modelx_test.go, internal/engine/netx/errorx/errorx_test.go, pkg/oonimkall/session_integration_test.go
This basically means going over the Go report card at https://goreportcard.com/report/github.com/ooni/probe-cli and reducing the number of warnings that are listed there. This work is part of the check list at https://github.com/ooni/probe/issues/1369.
=> release 3.9.0 process: reduce warnings

internal/engine/experiment/tor/tor.go, internal/engine/experiment/tor/tor_test.go, internal/engine/internal/mockable/mockable.go, internal/engine/internal/psiphonx/psiphonx.go, internal/engine/internal/psiphonx/psiphonx_test.go, internal/engine/internal/sessionresolver/childresolver_test.go, internal/engine/internal/sessionresolver/integration_test.go, internal/engine/model/experiment.go, internal/engine/netx/archival/archival_test.go, internal/engine/session.go, internal/engine/session_integration_test.go, internal/engine/session_internal_test.go
The main idea of this pull request is to refactor the way with which we fetch Psiphon configuration, so that we can introduce a private, optional package containing the Psiphon config. The easiest way to achieve this goal is to reduce the coupling between our Psiphpon wrappers and the probeservices package, by letting the Session make more work. Once this code has been written, I figured out it was generally a good idea to get rid of ExperimentOrchestraClient entirely and use the Session interface as the, well, interface between what experiment needs and what the probeservices package provides. This change is also instrumental to enable our future plan of further restructuring such a package. On the way, I also checked whether I could improve existing tests and generally increase our code …
=> refactor: remove model.ExperimentOrchestraClient

go.mod, go.sum, internal/engine/.gitignore, internal/engine/session.go, internal/engine/session_nopsiphon.go, internal/engine/session_psiphon.go, internal/engine/session_psiphon_test.go
We use an optional build tag to hide this configuration. When you
choose this configuration, you need to provide the encrypted config
as well as the corresponding decryption key.
This is not the final design. This is an interim design to start
working and experimenting with this functionality. The general
idea here is to support psiphon in the binaries we build without
committing the psiphon config to the repository itself.
=> feat: support embedding encrypted psiphon config

internal/engine/tunnel/config.go, internal/engine/tunnel/psiphon.go, internal/engine/tunnel/psiphon_test.go, internal/engine/tunnel/tunnel.go
Simplify interaction within the package by avoiding to have
a psiphon specific config. Use a Config instead.
Part of https://github.com/ooni/probe/issues/985.
=> refactor(tunnel): simplify psiphon implementation

internal/engine/tunnel/config.go, internal/engine/tunnel/psiphon.go, internal/engine/tunnel/psiphon_test.go, internal/engine/tunnel/tor.go, internal/engine/tunnel/tor_test.go, internal/engine/tunnel/tunnel.go
Simplify interaction within the package by avoiding to have
a tor specific config. Use a Config instead.
Part of https://github.com/ooni/probe/issues/985.
=> refactor(tunnel): simplify tor implementation

internal/engine/experiment/urlgetter/getter.go, internal/engine/session.go, internal/engine/tunnel/config.go, internal/engine/tunnel/tor.go, internal/engine/tunnel/tunnel.go
We're trying to remove a circular dependency between the measurement
Session and the tunnel package. To this end, continue to reduce the
dependency scope by providing TorArgs and TorBinary directly.
=> refactor(tunnel): provide TorArgs and TorBinary directly

internal/cmd/miniooni/main.go, internal/engine/session.go, internal/engine/session_nopsiphon.go, internal/engine/session_psiphon.go, internal/engine/tunnel/config.go
This diff breaks the circular dependency between session and
tunnel, by introducing the concept of early session.
An early session is a session that is able to fetch the psiphon
configuration file _only_ if it's embedded in the binary.
This breaks `miniooni --tunnel=psiphon` for users who have
access to the OONI backend. They are not the users we are
writing this feature for, though, so I think this is reasonable.
At the same time, this opens up the possibility of creating
a psiphon tunnel when constructing a session, which is the
approach I was following in https://github.com/ooni/probe-cli/pull/286.
This work is part of https://github.com/ooni/probe/issues/985.
Once this diff is in, I can land https://github.com/ooni/probe-cli/pull/286.
=> fix(engine): break circular dep betwen session and tunnel

internal/engine/tunnel/config.go, internal/engine/tunnel/psiphon.go, internal/engine/tunnel/psiphon_test.go, internal/engine/tunnel/tor.go, internal/engine/tunnel/tor_test.go, internal/engine/tunnel/tunnel.go, internal/engine/tunnel/tunnel_test.go
This code was originally introduced because a tunnel could be
nil in session.go. I have verified that every invocation of
tunnel.Start is careful to ensure that we have a tunnel name
and that we don't manipulate a nil tunnel.
For this reason, I'd rather remove this tricky bit of code and
further simplify the tunnel code.
=> refactor(tunnel): remove nil tunnels hack

internal/engine/session.go, internal/engine/tunnel/tor.go, internal/engine/tunnel/tor_test.go
This diff ensures that we don't keep the log file growing and
we also remove the temporary files created by the library we
are currently using for running tor from golang.
=> fix(tunnel/tor): keep tunneldir clean

cmd/ooniprobe/internal/nettests/nettests.go
This commit cherry-picks https://github.com/ooni/probe-cli/commit/6306c09963c3e05f5a1eb1a48ae226baa40ff3a1
See https://github.com/ooni/probe/issues/1433
Conflicts:
internal/version/version.go
=> fix: disable maxRuntime when not WebConnectivity

cmd/ooniprobe/internal/nettests/nettests.go, cmd/ooniprobe/internal/nettests/web_connectivity.go
When this happens, the user is expressing the intention of
explicitly testing all the input they provided.
So, disable maxRuntime in these cases.
Part of https://github.com/ooni/probe/issues/1436.
=> fix: disable maxRuntime with --input or --input-file

internal/engine/geolocate/geolocate.go, internal/engine/geolocate/geolocate_test.go, internal/engine/session.go
The use cases for using a proxy become more clear over time. When I
originally wrote the proxy code the idea was to use the proxy to proxy
both the communication with the backend and measurements.
It become increasingly clear that we _only_ want to proxy the
communication with the backends. Therefore, there's no point in
skipping the resolver lookup step when we use a proxy.
=> fix(geolocate): do resolver lookup with proxy

MOBILE/template.pom, build-android.bash
The main changes here are two. First, tweak some bits of the POM template
to make sure it's current, including referencing the correct repo. (We were
still referencing probe-engine in there, weirdly enough).
Second, change the android build script to create the same bundle that
mavan would build. What remains to do is uploading manually.
(Because it seems my PGP key is required, I guess this development rules
out automatically generating releases at GitHub. We will see about it
later on and possibly zap the publish-android.sh script.)
Reference issue: https://github.com/ooni/probe/issues/1437.
The release 2021.04.07-180801 has been created by me using this
diff from the v3.9.0 tag. I will update the release notes as soon
as this new release becomes available from Maven Central.
=> chore: adapt android scripts to use maven central

internal/engine/session.go, internal/engine/tunnel/config.go, internal/engine/tunnel/config_test.go, internal/engine/tunnel/tor.go, internal/engine/tunnel/tor_integration_test.go, internal/engine/tunnel/tor_test.go
It seems cretz/bine is not aware of https://blog.golang.org/path-security
for now. I am planning to send over a diff for that later today.
In the meanwhile, do the right thing here, and make sure that we obtain
the absolute path to the tor binary before we continue.
This work is part of https://github.com/ooni/probe-engine/issues/283.
=> fix(tunnel): pass /absolute/path/to/tor to cretz/bine

make
The previous fix allowed us to return values directly from
implementations of Engine. Here we take advantage of this
possibility by immediately refactoring how backticks work.
Part of https://github.com/ooni/probe/issues/1466.
=> refactor(make): backticks: return output directly

CLI/linux/arm64/.gitignore, CLI/linux/build, make
In https://github.com/ooni/probe/issues/1466, a user is asking
about arm64 builds for Debian. We already had some code for that
in https://github.com/ooni/probe-cli/pull/311. Let us adapt the
code to the `./make` script to have arm64 builds.
While there, also adapt the code for darwin and windows.
=> feat(make): build ooniprobe for darwin, windows, and linux

make
Just consistency. There was no clear semantic regarding why
sometimes I was using __name and sometimes _name.
So prefer _name everywhere.
Occurred to me while working on https://github.com/ooni/probe/issues/1466.
=> refactor(make): always use _name instead of __name

.github/workflows/macos.yml, .github/workflows/windows.yml
Like in the previous PR, here we make macos and windows builds only run when we're preparing a release. While there, migrate the code to use the `./make` script. Tested in https://github.com/ooni/probe-cli/pull/331.
Reference issue is https://github.com/ooni/probe/issues/1466
=> refactor(.github/workflows): macos, windows: use ./make, run less frequently

.github/workflows/linux.yml, make
While there, flush `print`s in `./make` to have more understandable logging.
Also part of https://github.com/ooni/probe/issues/1466
=> refactor(.github/workflows): linux: use ./make, run less frequently

CLI/linux/build, debian/.gitignore, debian/TODO, debian/ooniprobe-cli.service, debian/rules, make, smoketest.sh
This PR	groups misc cleanup and changes from #331.
* CLI/linux/build: add documentation
* debian/.gitignore: ignore generated files
* debian/TODO: unnecessary at this point
* debian/ooniprobe-cli.service: remove commented out lines
* debian/rules: remove unnecessary actions
* make: reindent and fix spelling
* smoketest.sh: don't run in verbose mode
Part of ooni/probe#1466
=> CLI, debian, make: misc cleanup and changes

CONTRIBUTING.md, cmd/ooniprobe/internal/autorun/autorun_darwin.go, internal/cmd/jafar/iptables/iptables_integration_test.go, internal/cmd/jafar/iptables/iptables_linux.go, internal/cmd/jafar/main.go, internal/cmd/jafar/main_test.go, internal/shellx/shellx.go, internal/shellx/shellx_test.go
We usually do not depend on `apex/log` directly for library-like code.
=> cleanup(shellx): do not directly depend on apex/log

internal/engine/geolocate/README.md, internal/engine/geolocate/geolocate.go, internal/engine/geolocate/geolocate_test.go, internal/engine/geolocate/ipconfig_test.go, internal/engine/geolocate/mmdblookup.go, internal/engine/model/model.go, internal/engine/session.go
1. remove unnecessary dependencies
2. NewTask never fails and we don't need Must
3. it seems https://github.com/ooni/probe/issues/1418 is no longer an issue so we can remove the previous mitigation (closes https://github.com/ooni/probe/issues/1418)
=> geolocate: first pass of code review and minor fixes

internal/engine/legacy/netx/dialer.go, internal/engine/legacy/netx/emitterdialer.go, internal/engine/legacy/netx/emitterdialer_test.go, internal/engine/netx/dialer/dns_test.go
I have verified that experiment/tor does not depend on this
functionality, therefore we can safely remove it.
Part of https://github.com/ooni/probe-engine/issues/897
=> refactor(netx): towards removing connid, dialid, etc

internal/engine/netx/dialer/dialer.go, internal/engine/netx/dialer/dns.go, internal/engine/netx/dialer/errorwrapper.go, internal/engine/netx/dialer/errorwrapper_test.go
Part of https://github.com/ooni/probe-engine/issues/897
=> refactor(netx): dialer does not use legacy/netx anymore

internal/engine/experiment/hhfm/hhfm.go, internal/engine/experiment/hhfm/hhfm_test.go, internal/engine/experiment/ndt7/dial.go, internal/engine/legacy/netx/dialer.go, internal/engine/netx/dialer/bytecounter.go, internal/engine/netx/dialer/bytecounter_test.go, internal/engine/netx/dialer/dialer.go, internal/engine/netx/dialer/dialer_test.go, internal/engine/netx/dialer/dns.go, internal/engine/netx/dialer/dns_test.go, internal/engine/netx/dialer/doc.go, internal/engine/netx/dialer/errorwrapper.go, internal/engine/netx/dialer/errorwrapper_test.go, internal/engine/netx/dialer/example_test.go, internal/engine/netx/dialer/integration_test.go, internal/engine/netx/dialer/logging.go, internal/engine/netx/dialer/logging_test.go, internal/engine/netx/dialer/proxy.go, internal/engine/netx/dialer/proxy_test.go, internal/engine/netx/dialer/saver.go, internal/engine/netx/dialer/saver_test.go, internal/engine/netx/dialer/shaping_disabled.go, internal/engine/netx/dialer/shaping_enabled.go, internal/engine/netx/dialer/shaping_test.go, internal/engine/netx/dialer/system.go, internal/engine/netx/dialer/system_test.go, internal/engine/netx/httptransport/http3transport_test.go, internal/engine/netx/netx.go, internal/engine/netx/netx_test.go, internal/engine/netx/tlsdialer/saver_test.go
This follows the blueprint of `module.Config` and `nodule.New`
described at https://github.com/ooni/probe/issues/1591.
=> refactor(netx/dialer): hide implementation complexity

cmd/ooniprobe/internal/autorun/autorun_darwin.go, cmd/ooniprobe/internal/config/parser.go, cmd/ooniprobe/internal/config/parser_test.go, cmd/ooniprobe/internal/database/actions.go, cmd/ooniprobe/internal/nettests/nettests_test.go, cmd/ooniprobe/internal/ooni/ooni.go, internal/cmd/e2epostprocess/main.go, internal/cmd/jafar/main.go, internal/cmd/miniooni/libminiooni.go, internal/engine/experiment/dash/collect_test.go, internal/engine/experiment/dash/dash_test.go, internal/engine/experiment/dash/download_test.go, internal/engine/experiment/dash/negotiate_test.go, internal/engine/experiment/hhfm/hhfm_test.go, internal/engine/experiment/urlgetter/runner.go, internal/engine/geolocate/ubuntu_test.go, internal/engine/legacy/netx/dialer.go, internal/engine/netx/dialer/bytecounter_test.go, internal/engine/netx/httptransport/bytecounter_test.go, internal/engine/netx/httptransport/logging_test.go, internal/engine/netx/httptransport/saver_test.go, internal/engine/netx/resolver/dnsoverhttps_test.go, internal/engine/probeservices/collector_test.go, internal/engine/session_integration_test.go, internal/tunnel/tor_test.go
Spotted while working on https://github.com/ooni/probe/issues/1417
See https://golang.org/pkg/io/ioutil/
=> cleanup(all): stop using deprecated ioutil functions

internal/engine/internal/mlablocate/mlablocate.go, internal/engine/internal/mlablocate/mlablocate_test.go
This is a very light refactoring of the mlablocate package where we do
the following things:
1. use interfaces rather depending on other pkgs where possible
2. only keep the fields we really need in the result struct
3. write more comprehensive docs (including todo-next comments)
While there, use `neubot/dash` rather than `ndt7` for the tests.
=> refactor(mlablocate): use interface, remove unused fields, add docs

internal/engine/internal/mlablocate/mlablocate_test.go, internal/engine/internal/mlablocatev2/mlablocatev2.go, internal/engine/internal/mlablocatev2/mlablocatev2_test.go
This is a very light refactoring of the mlablocatev2 package where we do
the following things:
1. use interfaces rather than depending on other pkgs where possible
2. add a missing test to the test suite
3. write more comprehensive docs (including todo-next comments)
=> refactor(mlablocatev2): use interfaces, add missing tests, add docs

.gitignore, internal/engine/allexperiments.go, internal/engine/experiment/torsf/integration_test.go, internal/engine/experiment/torsf/torsf.go, internal/engine/experiment/torsf/torsf_test.go, internal/engine/model/experiment.go
The current implementation assumes the user has already installed tor
on the current system. If tor is not present, the experiment fails.
This is meant to be the first version of this experiment.
We are going to add more functionality in subsequent revisions of
this experiment, once we've collected more feedback.
Reference issue: https://github.com/ooni/probe/issues/1565.
Here's the spec PR: https://github.com/ooni/spec/pull/218.
Here's the issue tracking future work: https://github.com/ooni/probe/issues/1686
=> feat(torsf): experiment that bootstraps tor using snowflake

internal/bytecounter/bytecounter.go, internal/bytecounter/bytecounter_test.go, internal/engine/experiment.go, internal/engine/internal/sessionresolver/resolvermaker.go, internal/engine/internal/sessionresolver/resolvermaker_test.go, internal/engine/internal/sessionresolver/sessionresolver.go, internal/engine/netx/dialer/bytecounter.go, internal/engine/netx/dialer/bytecounter_test.go, internal/engine/netx/httptransport/bytecounter.go, internal/engine/netx/httptransport/bytecounter_test.go, internal/engine/netx/integration_test.go, internal/engine/netx/netx.go, internal/engine/netx/netx_test.go, internal/engine/session.go
It's generic enough to live outside of engine/netx.
Occurred to me while working on https://github.com/ooni/probe/issues/1687.
=> refactor: move bytecounter to internal

internal/bytecounter/conn.go, internal/bytecounter/conn_test.go, internal/engine/netx/dialer/bytecounter.go, internal/engine/netx/dialer/bytecounter_test.go
This enables other pieces of code to request bytecounting without
depending on netx or on the perverse using-the-context-to-configure-
byte-counting mechanism.
Also occurred when working on https://github.com/ooni/probe/issues/1687
=> refactor: move bytecounting conn in bytecounter pkg

internal/engine/experiment/tor/tor.go, internal/engine/experiment/tor/tor_test.go, internal/engine/model/logger.go, internal/scrubber/logger.go, internal/scrubber/logger_test.go
We need it exported so we can use it in the new implementation.
Part of https://github.com/ooni/probe/issues/1687
=> refactor: move scrubbingLogger to the scrubber pkg

internal/bytecounter/conn_test.go, internal/engine/legacy/netx/emitterdialer_test.go, internal/engine/netx/dialer/bytecounter_test.go, internal/engine/netx/dialer/errorwrapper_test.go, internal/engine/netx/dialer/proxy_test.go, internal/engine/netx/dialer/saver_test.go, internal/engine/netx/mockablex/doc.go, internal/netxlite/dialer_test.go, internal/netxmocks/conn.go, internal/netxmocks/conn_test.go, internal/netxmocks/dialer.go, internal/netxmocks/dialer_test.go, internal/netxmocks/doc.go, internal/ptx/obfs4_test.go, internal/ptx/ptx_test.go, internal/ptx/snowflake_test.go
Needed to more easily do https://github.com/ooni/probe/issues/1505
=> refactor: rename i/e/n/mockablex => i/netxmocks

internal/engine/legacy/netx/emitterdialer_test.go, internal/engine/netx/dialer/bytecounter_test.go, internal/engine/netx/dialer/errorwrapper_test.go, internal/engine/netx/dialer/proxy_test.go, internal/engine/netx/dialer/saver_test.go, internal/netxlite/dialer_test.go, internal/netxmocks/dialer.go, internal/netxmocks/resolver.go, internal/netxmocks/resolver_test.go
While there, make sure we require using &netxmocks.Dialer.
Still part of https://github.com/ooni/probe/issues/1505
=> feat(netxmocks): implement mocks for netxlite.Resolver

internal/netxlite/dialer.go, internal/netxlite/dialer_test.go, internal/netxlite/legacy_test.go, internal/netxlite/resolver.go, internal/netxlite/resolver_test.go, internal/netxmocks/conn.go, internal/netxmocks/dialer.go, internal/netxmocks/resolver.go
While there, improve logging and make sure we test 100% of the
package with unit tests only. (We don't need to have integration
testing in this package because it's fairly simple/obvious.)
=> refactor(netxlite): make sure we always use netxmocks

internal/engine/netx/integration_test.go, internal/engine/netx/resolver/bogon.go, internal/engine/netx/resolver/bogon_test.go
The BogonResolver relied on its wrapper resolver to pass along the
list of addresses _and_ the error. But the idiomatic thing to do is
often to return `nil` when there is an error.
I broke this very fragile assumption in https://github.com/ooni/probe-cli/pull/399.
I could of course fix it, but this assumption is clearly wrong
and we should not allow such fragile code in the tree.
We are not using BogonIsError much in the tree. The only place in
which we're using it for measuring seems to be dnscheck.
It may be that this surprising behavior was what caused the issue at
https://github.com/ooni/probe/issues/1510 in the first place.
Regardless, let's remove fragile code and adjust the test that was
failing. Also that test is quick so it can run in `-short` mode.
Spotted while working on …
=> fix(netx): repair BogonResolver tests

internal/engine/netx/netx.go, internal/engine/netx/quicdialer/dns_test.go, internal/engine/netx/quicdialer/errorwrapper_test.go, internal/engine/netx/quicdialer/saver_test.go, internal/engine/netx/quicdialer/system.go, internal/engine/netx/quicdialer/system_test.go
With this change, we will soon be able to move the creation of
a QUIC session inside of the netxlite package.
Part of https://github.com/ooni/probe/issues/1505.
=> refactor(quicdialer): separate saving from listening

internal/engine/netx/quicdialer/system.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go
Noticed when working on https://github.com/ooni/probe/issues/1505.
Justification for this diff:
1. [DialEarlyContext calls dialContext with the last argument set to false](https://github.com/lucas-clemente/quic-go/blob/v0.21.1/client.go#L153);
2. [the semantics of the last argument is whether we own the connection](https://github.com/lucas-clemente/quic-go/blob/v0.21.1/client.go#L187);
3. [this value is propagated to the client data structure](https://github.com/lucas-clemente/quic-go/blob/v0.21.1/client.go#L269);
4. [client.dial](https://github.com/lucas-clemente/quic-go/blob/v0.21.1/client.go#L302) runs the session in a background goroutine and only destroys the `packetHandlers` when the connection is owned;
5. [packetHandlerMap.Destroy](https://github.com/lucas-clemente/quic-go/blob/v0. …
=> fix(netxlite): close quic packetconn

internal/engine/legacy/netx/dialer.go, internal/engine/netx/netx.go, internal/engine/netx/netx_test.go, internal/engine/netx/tlsdialer/integration_test.go, internal/engine/netx/tlsdialer/saver_test.go, internal/engine/netx/tlsdialer/tls_test.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go, internal/netxlite/tlsconn.go, internal/netxlite/tlsdialer.go, internal/netxlite/tlsdialer_test.go, internal/netxlite/tlshandshaker.go, internal/netxlite/tlshandshaker_test.go, internal/netxmocks/quic.go, internal/netxmocks/quic_test.go, internal/netxmocks/tlsconn.go
Auto-configure every relevant TLS field as close as possible to
where it's actually used.
As a side effect, add support for mocking the creation of a TLS
connection, which should possibly be useful for uTLS?
Refactoring as part of https://github.com/ooni/probe/issues/1505
=> fix(netxlite): improve TLS auto-configuration

internal/engine/netx/httptransport/http3transport.go, internal/engine/netx/httptransport/system.go, internal/netxlite/http.go, internal/netxlite/http3.go, internal/netxlite/http_test.go
With this factory, we want to construct ourselves the TLS dialer
so that we can use a dialer wrapper that always sets timeouts when
reading, addressing https://github.com/ooni/probe/issues/1609.
As a result, we cannot immediately replace the i/e/netx factory
for creating a new HTTP transport, since the functions signatures
are not directly compatible.
Refactoring is part of https://github.com/ooni/probe/issues/1505.
=> refactor: introduce factory for stdlib http transport

internal/engine/legacy/netx/dialer.go, internal/engine/netx/netx.go, internal/engine/netx/netx_test.go, internal/engine/netx/tlsdialer/tls.go, internal/engine/netx/tlsdialer/tls_test.go, internal/errorsx/tls.go, internal/errorsx/tls_test.go
=> refactor: move ErrorWrapperTLSHandshaker to errorsx

internal/errorsx/dialer.go, internal/errorsx/dialer_test.go, internal/errorsx/errorsx.go
The utility of SafeErrWrapperBuilder is low. Let us instead change the
code to always create ErrWrapper when we're in this package.
While there, also note some TODO-next items.
Part of https://github.com/ooni/probe/issues/1505.
=> refactor(errorsx): directly return ErrWrapper when needed

CONTRIBUTING.md
Reference issue: https://github.com/ooni/probe/issues/1670
The guidelines now refer to the ooni.org dev guidelines. As part of applying this change, I've re-read the whole file and fixed a bunch of places where actual development practices have diverged from the text.
=> CONTRIBUTING: ref org-wide guidelines + minor fixes

internal/engine/probeservices/urls_test.go, pkg/oonimkall/session_integration_test.go
The CI is failing. Those are integration tests. Let us figure out the issue when we approach release. Until we approach release, do not let those tests distracting us. Normal merges should only pass the `-short` tests.
=> fix: skip two integration tests in short mode

internal/cmd/oohelper/internal/client.go, internal/cmd/oohelper/internal/client_test.go
When a probe gets a local DNS failure, it will continue and nonetheless
query the test helper without any IP address, just an empty list.
This diff fixes the behavior of cmd/oohelper to do the same.
Work part of https://github.com/ooni/probe/issues/1707.
=> fix(oohelper): do not stop if DNS fails locally

internal/cmd/oohelperd/internal/websteps/explore.go, internal/engine/experiment/websteps/model.go, internal/engine/experiment/websteps/websteps.go
The quic-go library does not support it anymore. So, let us be consistent
and remove any reference to h3-29 from our codebase.
Closes https://github.com/ooni/probe/issues/1740.
=> fix: completely remove support for h3-29

internal/cmd/oohelperd/internal/websteps/explore.go, internal/cmd/oohelperd/internal/websteps/generate.go, internal/cmd/oohelperd/internal/websteps/initialchecks.go, internal/cmd/oohelperd/internal/websteps/measure.go, internal/engine/experiment/ndt7/dial.go, internal/engine/experiment/websteps/dns.go, internal/engine/experiment/websteps/factory.go, internal/engine/experiment/websteps/quic.go, internal/engine/experiment/websteps/tcp.go, internal/engine/netx/dialer/dialer.go, internal/engine/netx/netx.go, internal/engine/netx/netx_test.go, internal/engine/netx/resolver/integration_test.go, internal/netxlite/http3_test.go, internal/netxlite/http_test.go, internal/netxlite/legacy.go, internal/netxlite/legacy_test.go, internal/netxlite/mocks/resolver.go, internal/netxlite/mocks/resolver_test.go, internal/netxlite/quic_test.go, internal/netxlite/resolver.go, internal/netxlite/resolver_test.go
We would like to refactor the code so that a DoH resolver owns the
idle connections of its underlying HTTP client.
To do that, we need first to incorporate CloseIdleConnections
into the Resolver model. Then, we need to add the same function
to all netxlite types that wrap a Resolver type.
At the same time, we want the rest of the code for now to continue
with the simpler definition of a Resolver, now called ResolverLegacy.
We will eventually propagate this change to the rest of the tree
and simplify the way in which we manage Resolvers.
To make this possible, we introduce a new factory function that
adapts a ResolverLegacy to become a Resolver.
See https://github.com/ooni/probe/issues/1591.
=> refactor(netxlite): add more functions to resolver

internal/engine/experiment/ndt7/dial_test.go, internal/engine/experiment/ndt7/ndt7_test.go, internal/netxlite/resolver.go, internal/netxlite/resolver_test.go
Closes https://github.com/ooni/probe/issues/1726
=> fix(netxlite): make default resolver converge faster

internal/cmd/oohelperd/internal/websteps/generate.go, internal/engine/experiment/websteps/factory.go, internal/engine/experiment/websteps/tcp.go, internal/engine/legacy/netx/dialer.go, internal/engine/netx/dialer/dialer.go, internal/engine/netx/dialer/dialer_test.go, internal/engine/netx/netx.go, internal/engine/netx/netx_test.go, internal/engine/netx/tlsdialer/integration_test.go, internal/engine/netx/tlsdialer/saver_test.go, internal/netxlite/dialer.go, internal/netxlite/dialer_test.go, internal/netxlite/legacy.go, internal/netxlite/legacy_test.go, internal/netxlite/mocks/dialer.go, internal/netxlite/mocks/dialer_test.go, internal/netxlite/tls_test.go
Like we did before for the resolver, a dialer should propagate the
request to close idle connections to underlying types.
=> refactor(dialer): it should close idle connections

internal/netxlite/dialer.go, internal/netxlite/dialer_test.go, internal/netxlite/http3_test.go, internal/netxlite/http_test.go, internal/netxlite/quic_test.go, internal/netxlite/resolver.go, internal/netxlite/resolver_test.go
=> feat(netxlite): add dialer factory, simplify resolver factory

internal/netxlite/tls.go, internal/netxlite/tls_test.go
We are proceeding with this plan of every major type being able to
close idle connections, which will simplify making DNS resolvers.
See https://github.com/ooni/probe/issues/1591.
=> feat(netxlite): TLSDialer closes idle connections

internal/engine/experiment/websteps/factory.go, internal/engine/legacy/netx/dialer.go, internal/engine/netx/netx.go, internal/engine/netx/netx_test.go, internal/engine/netx/tlsdialer/integration_test.go, internal/engine/netx/tlsdialer/saver_test.go, internal/netxlite/dialer.go, internal/netxlite/dialer_test.go, internal/netxlite/http.go, internal/netxlite/legacy.go, internal/netxlite/tls.go, internal/netxlite/tls_test.go
This basically adapts already existing code inside websteps to
instead be into the netxlite package, where it belongs.
In the process, abstract the TLSDialer but keep a reference to the
previous name to avoid refactoring existing code (just for now).
While there, notice that the right name is CloseIdleConnections (i.e.,
plural not singular) and change the name.
While there, since we abstracted TLSDialer to be an interface, create
suitable factories for making a TLSDialer type from a Dialer and a
TLSHandshaker.
=> feat(netxlite): implement single use {,tls} dialer

internal/netxlite/http.go, internal/netxlite/http_test.go
To make this happen, we need to take as argument a TLSDialer rather than
a TLSHandshaker. Then, we need to arrange the code so that we always
enforce a timeout for both TCP and TLS connections.
Because a TLSDialer can be constructed with a custom TLSConfig, we cover
also the case where the users wants to provide such a config.
While there, make sure we have better unit tests of the HTTP code.
=> refactor(netxlite): let NewHTTPTransport work with single-use dialers

internal/netxlite/dialer.go, internal/netxlite/legacy.go, internal/netxlite/legacy_test.go, internal/netxlite/quic.go, internal/netxlite/quirks.go, internal/netxlite/quirks_test.go
This quirk really saddens me. It's a piece of tech debt we're
carrying over from the original netx implementation.
We cannot remove it _until_ we have legacy netx code around.
The second best thing we can do is to clearly move this code in
a place where it's clear it's a quirk and write and use some extra
code that makes sure the quirk's assumptions are always met.
Sigh.
=> fix(netxlite): clearly document quirk and make code robust

internal/engine/experiment/websteps/factory.go, internal/engine/netx/netx.go, internal/netxlite/legacy.go, internal/netxlite/legacy_test.go, internal/netxlite/mocks/legacy.go, internal/netxlite/mocks/legacy_test.go, internal/netxlite/mocks/quic.go, internal/netxlite/mocks/quic_test.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go
Like before, do not touch the rest of the tree. Rather create
compatibility types declared as legacy.
We will soon be able to close idle connections for an HTTP3
transport using any kind of resolvers more easily.
=> feat(netxlite): add CloseIdleConnections to quic dialer

internal/cmd/oohelperd/internal/websteps/explore.go, internal/engine/netx/httptransport/http3transport.go, internal/netxlite/http3.go, internal/netxlite/http3_test.go
With this change, we are now able to change more dependent code to simplify
the way in which we create and manage resolvers.
=> fix(netxlite): http3 propagates CloseIdleConnections to its dialer

internal/netxlite/dialer.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go
This is the last bit of functionality we need before rewriting a
chunk of websteps to use netxlite.
To rewrite most of it, we still need to move over:
1. dnstransport code
2. errorsx code
With both done, netxlite is a good library for websteps as well
as for most other operations we perform outside of the experiments.
=> refactor(netxlite): adapt single-use-quic-dialer from websteps

internal/errorsx/dialer.go, internal/errorsx/quic.go
For consistency and also because the SafeErrorWrapperBuilder seems
to be the building pattern than the original code assumed.
New code should not use it, but I'd rather keep legacy code consistent
formally and with its own original assumptions.
In particular, it matters that SafeErrorWrapperBuilder assigns the
most relevant operation that failed. We were not doing that when we
were manually creating a new ErrWrapper.
=> refactor(i/errorsx): always use the same error reporting pattern

internal/netxlite/dialer.go, internal/netxlite/dialer_test.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go, internal/netxlite/resolver.go, internal/netxlite/resolver_test.go, internal/netxlite/tls.go, internal/netxlite/tls_test.go, internal/netxlite/utls.go, internal/netxlite/utls_test.go
Copied and adapted code from legacy/errorsx without using the SafeErrWrapperBuilder
=> fix(netxlite): add error wrappers

internal/netxlite/errorsx/classify.go, internal/netxlite/errorsx/classify_test.go
Later we will try to write comprehensive integration tests for
the whole netxlite package. We want just unit tests here.
=> refactor(netxlite/errorsx): change all tests to be unit tests

internal/netxlite/errorsx/errwrapper.go, internal/netxlite/errorsx/errwrapper_test.go
This simplifies serializing errors to `*string`. It did not
occur to me before. It seems quite a nice improvement.
=> fix(netxlite/errorsx): serialize directly to JSON

internal/cmd/oohelperd/internal/websteps/explore.go, internal/engine/netx/httptransport/http3transport.go, internal/netxlite/http3.go, internal/netxlite/http3_test.go, internal/netxlite/integration_test.go
Adapt other places where it was not using a logger to either choose
a reasonable logger or disable logging for backwards compat.
=> fix(netxlite): http3 transport needs logging by default

internal/cmd/jafar/httpproxy/httpproxy.go, internal/cmd/jafar/resolver/resolver.go, internal/cmd/jafar/tlsproxy/tlsproxy.go, internal/cmd/jafar/tlsproxy/tlsproxy_test.go
There are a bunch of packages where we don't really need to depend on `netx` but we can use local definitions that describe what we are expecting from data structures we receive in input. This diff addresses one of such cases.
=> refactor(jafar): remove unnecessary dep on netx

internal/cmd/oohelper/internal/client.go
There are a bunch of packages where we don't really need to depend
on netx but we can use local definitions that describe what we are
expecting from data structures we receive in input. This diff
addresses one of such cases.
=> refactor(oohelper): remove unnecessary dep from netx

internal/engine/experiment/urlgetter/configurer_test.go, internal/engine/netx/netx_test.go, internal/engine/netx/resolver/dnsoverhttps.go, internal/engine/netx/resolver/dnsoverhttps_test.go, internal/engine/netx/resolver/dnsovertcp.go, internal/engine/netx/resolver/dnsovertcp_test.go, internal/engine/netx/resolver/dnsoverudp.go, internal/engine/netx/resolver/dnsoverudp_test.go, internal/engine/netx/resolver/emitter_test.go, internal/engine/netx/resolver/fake_test.go, internal/engine/netx/resolver/serial.go, internal/netxlite/mocks/http.go, internal/netxlite/mocks/http_test.go
While there, also change to pointer receiver and use internal
testing for what are clearly unit tests.
=> refactor(netx/resolver): add CloseIdleConnections to RoundTripper

internal/engine/netx/resolver/legacy.go, internal/netxlite/dnsx/decoder.go, internal/netxlite/dnsx/decoder_test.go, internal/netxlite/dnsx/dnsoverhttps.go, internal/netxlite/dnsx/dnsoverhttps_test.go, internal/netxlite/dnsx/dnsovertcp.go, internal/netxlite/dnsx/dnsovertcp_test.go, internal/netxlite/dnsx/dnsoverudp.go, internal/netxlite/dnsx/dnsoverudp_test.go, internal/netxlite/dnsx/encoder.go, internal/netxlite/dnsx/encoder_test.go, internal/netxlite/dnsx/mocks/decoder.go, internal/netxlite/dnsx/mocks/decoder_test.go, internal/netxlite/dnsx/mocks/doc.go, internal/netxlite/dnsx/mocks/encoder.go, internal/netxlite/dnsx/mocks/encoder_test.go, internal/netxlite/dnsx/mocks/roundtripper.go, internal/netxlite/dnsx/mocks/roundtripper_test.go, internal/netxlite/dnsx/roundtripper.go, internal/netxlite/dnsx/serial.go, internal/netxlite/dnsx/serial_test.go
While there, modernize the way in which we run tests to avoid
depending on the fake files scattered around the tree and to
use some well defined mock structures instead.
=> refactor(netx): move dns transports in netxlite/dnsx

internal/engine/legacy/netx/oldhttptransport/httptransport.go, internal/engine/netx/httptransport/saver.go, internal/engine/netx/httptransport/saver_test.go, internal/engine/netx/httptransport/useragent.go, internal/engine/netx/netx.go, internal/engine/netx/netx_test.go, internal/netxlite/http.go, internal/netxlite/http_test.go, internal/netxlite/legacy.go
I have recently seen a data race related our way of
mutating the outgoing request to set the host header.
Unfortunately, I've lost track of the race output,
because I rebooted my Linux box before saving it.
Though, after inspecting why and and where we're mutating
outgoing requets, I've found that:
1. we add the host header when logging to have it logged,
which is not a big deal since we already emit the URL
rather than just the URL path when logging a request, and
so we can safely zap this piece of code;
2. as a result, in measurements we may omit the host header
but again this is pretty much obvious from the URL itself
and so it should not be very important (nonetheless,
avoid surprises and keep the existing behavior);
3. when …
=> fix(http): do not mutate outgoing requests

pkg/oonimkall/internal/tasks/runner_internal_test.go
It seems ~difficult to reproduce the problem locally and I could not
see it after five runs of
```
go test -race -count 1 ./pkg/oonimkall/...
```
So, here's some diagnostic code that could help understanding the
reference issue https://github.com/ooni/probe/issues/1785.
Also, it seems the issue pops up much more frequently when running
CI anyway. So, I am going to leave this diff around and when it
appears again I have more context to fix the issue.
=> feat(oonimkall): instrument code to understand CI issue

internal/ooapi/swaggerdiff_test.go
At the moment ooapi is not used. It will eventually be used since
it's a better way of accessing the OONI backend API.
To fix these tests, we need to fix the swagger emitted by the
backend API, which is not a priority at the moment, since we are
working instead to integrate websteps in miniooni.
Issue https://github.com/ooni/probe/issues/1790 tracks the work
required to re-enabled the tests I'm skipping with this diff.
This work is part of https://github.com/ooni/probe/issues/1733.
=> fix(ooapi): disable tests we're not using

internal/netxlite/integration_test.go
The explanatory comment in the diff says it all.
Work done while I was converging with https://github.com/ooni/probe/issues/1733.
=> fix(netxlite): make test less flaky on macOS

internal/cmd/miniooni/libminiooni.go, internal/engine/doc.go, internal/engine/experiment.go, internal/engine/experiment_integration_test.go, internal/engine/inputprocessor.go, internal/engine/inputprocessor_test.go, internal/engine/model/experiment.go, pkg/oonimkall/internal/tasks/runner.go
This is required to implement websteps, which is currently tracked
by https://github.com/ooni/probe/issues/1733.
We introduce the concept of async runner. An async runner will
post measurements on a channel until it is done. When it is done,
it will close the channel to notify the reader about that.
This change causes sync experiments now to strictly return either
a non-nil measurement or a non-nil error.
While this is a pretty much obvious situation in golang, we had
some parts of the codebase that were not robust to this assumption
and attempted to submit a measurement after the measure call
returned an error.
Luckily, we had enough tests to catch this change in our assumption
and this is why there are extra docs and tests …
=> feat(engine): allow runner to return many measurements

internal/cmd/oohelper/oohelper.go, internal/cmd/oohelperd/oohelperd.go, internal/engine/allexperiments.go, internal/engine/experiment/webstepsx/doc.go, internal/engine/experiment/webstepsx/measurer.go, internal/engine/experiment/webstepsx/th.go
This diff adds the prototype websteps implementation that used
to live at https://github.com/ooni/probe-cli/pull/506.
The code is reasonably good already and it's pointing to a roaming
test helper that I've properly configured.
You can run websteps with:
```
./miniooni -n websteps
```
This will go over the test list for your country.
At this stage the mechanics of the experiment is set, but we
still need to have a conversation on the following topics:
1. whether we're okay with reusing the data format used by other
OONI experiments, or we would like to use a more compact data
format (which may either be a more compact JSON or we can choose
to always submit compressed measurements for websteps);
2. the extent to which we would …
=> feat(webstepsx): websteps using measurex

internal/measurex/measurer.go
This is the most immediate fix to the issue described by
https://github.com/ooni/probe/issues/1792.
So, the logic was actually miss the increment, which
would have been noticed with proper unit testing.
Anyway, I am not sure why the loop ensues in the first
time. By looking at the headers, it seems we're passing
the headers correctly.
So, even though this fix interrupts the loop, it still
remains the question of whether the loop is legit or
whether we're missing extra logic to properly redirect.
=> fix(measurex): make sure we don't redirect loop forever

internal/tutorial/README.md
Add missing reference to netxlite's tutorial.
=> fix: add missing reference to netxlite's tutorial

internal/cmd/oohelperd/internal/webconnectivity/http.go
Part of https://github.com/ooni/probe/issues/1707
=> fix(oohelperd): return HTTP headers as empty map on error

internal/cmd/oohelperd/internal/webconnectivity/dns.go, internal/cmd/oohelperd/internal/webconnectivity/dns_test.go, internal/cmd/oohelperd/internal/webconnectivity/http.go, internal/cmd/oohelperd/internal/webconnectivity/http_test.go, internal/cmd/oohelperd/internal/webconnectivity/tcpconnect.go, internal/cmd/oohelperd/internal/webconnectivity/tcpconnect_test.go
Reducing the errors is not done in a perfect way.
We have documented the most striking differences inside
https://github.com/ooni/probe/issues/1707#issuecomment-942283746 and
some attempts to improve the situation further inside
https://github.com/ooni/probe/issues/1707#issuecomment-942341255.
A better strategy for the future would be to introduce more
specific timeout errors, such as dns_timeout_error, etc.
More testing may be needed to further validate and compare the
old and the new TH, but this requires Jafar improvements to
more precisely simulate more complex censorship.
=> fix(oohelperd): reduce errors to what the old TH would emit

cmd/ooniprobe/internal/nettests/nettests.go
This diff addresses the most immediate issue but there is probably
extra work to do, including testing and making sure experiments
do not return an error when they should not.
=> fix(ooniprobe): Measure returns EITHER measurement OR error now

internal/cmd/oohelperd/internal/webconnectivity/measure.go
Matches the behavior that the legacy TH implements in this
situation and reduces slightly the differences.
See https://github.com/ooni/probe/issues/1707#issuecomment-944143329
=> fix(wcth): emit empty Addrs when input URL contains addr

internal/engine/netx/resolver/bogon.go, internal/engine/netx/resolver/bogon_test.go, internal/measurex/resolver.go, internal/netxlite/bogon.go, internal/netxlite/bogon_test.go
I develop this diff while working on https://github.com/ooni/probe/issues/1803#issuecomment-957323297.
While there, make sure we don't have duplicate bogon code
and always use the code inside netxlite.
=> cleanup: move bogon checking code in netxlite

internal/netxlite/filtering/dns.go, internal/netxlite/filtering/dns_test.go, internal/netxlite/filtering/tls.go, internal/netxlite/filtering/tls_test.go
This change will simplify follow-up work done as part of
https://github.com/ooni/probe/issues/1803#issuecomment-957323297 to
implement a comprehensive self-censoring solution.
While there, rename the "proxy" action to "pass" because what we
are effectively doing is passing traffic to the network (that's a
minor change but it seems a better analogy).
=> refactor(netxlite/filtering): use strings for blocking policies

internal/netxlite/filtering/dns_test.go, internal/netxlite/filtering/http_test.go, internal/netxlite/filtering/tls.go, internal/netxlite/filtering/tls_test.go, internal/netxlite/mocks/listener.go, internal/netxlite/mocks/listener_test.go
1. in normal code is better to always do if err != nil so that
the ifs only contain error code (this is ~coding policy)
2. in tests we want to ensure we narrow down the error to the
real error that happened, to have greater confidence
Written while working on https://github.com/ooni/probe/issues/1803#issuecomment-957323297
=> fix(filtering): avoid the if err == nil pattern

internal/netxlite/filtering/dns.go, internal/netxlite/filtering/dns_test.go, internal/netxlite/filtering/testdata/valid.json, internal/netxlite/filtering/tproxy.go, internal/netxlite/filtering/tproxy_test.go
When we're testing multiple endpoints, it's quite important to control
the order with which they are returned to the code.
This feature is especially relevant to Web Connectivity, which will
check the endpoints to connect to in order.
Therefore, we need to force deterministic results to ensure that we can
have deterministic tests when doing Web Connectivity QA.
This diff gives us the guarantee that we can have determinism.
Part of https://github.com/ooni/probe/issues/1803#issuecomment-957323297.
=> feat(filtering): introduce DNS cache

internal/netxlite/filtering/tproxy.go, internal/netxlite/filtering/tproxy_test.go
This is the policy we need to provoke certificate errors. We'll divert
from, say, `8.8.8.8:443/udp` to, say, `1.1.1.1:443/udp`.
We'll do something similar for `443/tcp`.
This will cause certificate validation errors.
With this change, we have now implemented the simple design described
by https://github.com/ooni/probe/issues/1803#issuecomment-957323297.
=> feat(filtering): implement the divert policy

internal/cmd/miniooni/libminiooni.go
This flag is similar to the previous --self-censor-spec and tells
miniooni what censorship to implement for itself.
This concludes the design at https://github.com/ooni/probe/issues/1803#issuecomment-957323297
=> feat(miniooni): add the --censor flag

cmd/ooniprobe/internal/cli/onboard/onboard.go, cmd/ooniprobe/internal/config/settings.go, cmd/ooniprobe/internal/config/testdata/valid-config.json, cmd/ooniprobe/internal/ooni/default-config.json, cmd/ooniprobe/testdata/testing-config.json, debian/ooniprobe.conf.disabled
Closes https://github.com/ooni/probe/issues/1766
=> cleanup(ooniprobe): remove unused send_crash_report option

internal/engine/experiment/webconnectivity/httpanalysis.go, internal/engine/experiment/webconnectivity/httpanalysis_test.go, internal/engine/experiment/webconnectivity/summary.go
This diff changes the algorithm used by webconnectivity's
httpanalysis.go to ignore any status code <= 0 rather
than just ignoring the == 0 case.
Make sure we add test cases for when the control's status
code is negative rather than being zero.
While there, simplify code where boolean checks could be
more compact according to staticcheck.
Closes https://github.com/ooni/probe/issues/1825
=> fix(webconnectivity): ignore any status code <= 0

internal/engine/experiment/webconnectivity/httpanalysis.go, internal/engine/experiment/webconnectivity/httpanalysis_test.go, internal/engine/experiment/webconnectivity/summary.go
This diff changes the algorithm used by webconnectivity's
httpanalysis.go to ignore any status code <= 0 rather
than just ignoring the == 0 case.
Make sure we add test cases for when the control's status
code is negative rather than being zero.
While there, simplify code where boolean checks could be
more compact according to staticcheck.
Closes https://github.com/ooni/probe/issues/1825
This backports 3b27780836714f8d9440633a9257e66a48c7f5f7 from `master`.
=> [backport] fix(webconnectivity): ignore any status code <= 0 (#579)

internal/measurex/http.go, internal/netxlite/classify.go, internal/netxlite/dnsoverhttps.go, internal/netxlite/errwrapper.go, internal/netxlite/errwrapper_test.go, internal/netxlite/http.go, internal/netxlite/http_test.go, internal/netxlite/iox.go, internal/netxlite/iox_test.go
1. introduce implementations of HTTPTransport and HTTPClient
that apply an error wrapping policy using the constructor
for a generic top-level error wrapper
2. make sure we use the implementations in point 1 when we
are constructing HTTPTransport and HTTPClient
3. make sure we apply error wrapping using the constructor for
a generic top-level error wrapper when reading bodies
4. acknowledge that error wrapping would be broken if we do
not return the same classification _and_ operation when we wrap
an already wrapped error, so fix the to code to do that
5. acknowledge that the classifiers already deal with preserving
the error string and explain why this is a quirk and why we
cannot remove it right now and what needs to happen to safely
remove this quirk from the codebase
Closes …
=> fix(netxlite): ensure HTTP errors are always wrapped

internal/netxlite/classify.go, internal/netxlite/dnsoverhttps.go, internal/netxlite/errwrapper.go, internal/netxlite/errwrapper_test.go, internal/netxlite/http.go, internal/netxlite/http_test.go, internal/netxlite/iox.go, internal/netxlite/iox_test.go
1. introduce implementations of HTTPTransport and HTTPClient
that apply an error wrapping policy using the constructor
for a generic top-level error wrapper
2. make sure we use the implementations in point 1 when we
are constructing HTTPTransport and HTTPClient
3. make sure we apply error wrapping using the constructor for
a generic top-level error wrapper when reading bodies
4. acknowledge that error wrapping would be broken if we do
not return the same classification _and_ operation when we wrap
an already wrapped error, so fix the to code to do that
5. acknowledge that the classifiers already deal with preserving
the error string and explain why this is a quirk and why we
cannot remove it right now and what needs to happen to safely
remove this quirk from the codebase
Closes …
=> [backport] fix(netxlite): ensure HTTP errors are always wrapped (#584)

.github/workflows/alltests.yml, .github/workflows/android.yml, .github/workflows/coverage.yml, .github/workflows/generate.yml, .github/workflows/ios.yml, .github/workflows/jafar.yml, .github/workflows/macos.yml, .github/workflows/miniooni.yml, .github/workflows/netxlite.yml, .github/workflows/oohelperd.yml, .github/workflows/qafbmessenger.yml, .github/workflows/qahhfm.yml, .github/workflows/qahirl.yml, .github/workflows/qatelegram.yml, .github/workflows/qawebconnectivity.yml, .github/workflows/qawhatsapp.yml, .github/workflows/windows.yml, go.mod, go.sum
This diff forward ports adcb0f9ae3b9e074c301d4f7f0e8f2d0ef6466b9.
- - -
- ensure we use go1.17.3 in workflows
- update to a version of ooni/oohttp that uses go1.17.3
This change WILL need to be forward ported to master.
Closes https://github.com/ooni/probe/issues/1861
=> [forwardport] chore: use go1.17.3 (#588)

mk
This diff forward ports abd212d014783cb96eaf821e9bb9a7b01039f837.
- - -
This diff upgrades `./mk` to use go1.17.3 rather than go1.16. While there, also update other Android build tools.
This diff WILL need a forwardport to master.
Closes https://github.com/ooni/probe/issues/1863.
=> [forwardport] mk: update ooni/go and Android build tools (#590)

internal/cmd/oohelperd/internal/websteps/explore_test.go, internal/cmd/oohelperd/internal/websteps/generate_test.go, internal/engine/internal/sessionresolver/resolvermaker.go, internal/engine/legacy/errorsx/integration_test.go, internal/engine/netx/quicdialer/saver_test.go, internal/engine/netx/quicdialer/system_test.go, internal/netxlite/integration_test.go, internal/netxlite/quictesting/quictesting.go, internal/netxlite/quictesting/quictesting_test.go
This diff changes code the release/3.11 branch to ensure we're not using dns.google and www.google.com over HTTP3. As documented in https://github.com/ooni/probe/issues/1873, since this morning (approx) these services do not support HTTP3 anymore. (I didn't bother with checking whether this issue affects _other_ Google services; I just limited my analysis to the services that we were using as part of testing.)
This patch WILL require forward porting to the master branch.
=> fix: avoid http3 for dns.google and www.google.com

internal/cmd/oohelperd/internal/websteps/explore_test.go, internal/cmd/oohelperd/internal/websteps/generate_test.go, internal/engine/internal/sessionresolver/resolvermaker.go, internal/engine/legacy/errorsx/integration_test.go, internal/engine/netx/quicdialer/saver_test.go, internal/engine/netx/quicdialer/system_test.go, internal/netxlite/integration_test.go, internal/netxlite/quictesting/quictesting.go, internal/netxlite/quictesting/quictesting_test.go
This commit forward ports dedd84fa7ecb09f718f6b1a9c83999cb37b34dfa.
- - -
This diff changes code the release/3.11 branch to ensure we're not using dns.google and www.google.com over HTTP3. As documented in https://github.com/ooni/probe/issues/1873, since this morning (approx) these services do not support HTTP3 anymore. (I didn't bother with checking whether this issue affects _other_ Google services; I just limited my analysis to the services that we were using as part of testing.)
This patch WILL require forward porting to the master branch.
=> [forwardport] fix: avoid http3 for dns.google and www.google.com (#593)

internal/engine/geolocate/resolverlookup.go
This diff backports 5a481b395aa06f5d1f542562920c0208b2f79fb1.
- - -
This diff needs to be backported to the release/3.11 branch.
Reference issue https://github.com/ooni/probe/issues/1865.
=> [backport] fix(geolocate): use powerdns.org whoami service (#592)

internal/engine/experiment/psiphon/psiphon.go, internal/engine/experiment/psiphon/psiphon_test.go
See: https://github.com/ooni/probe/issues/1856.
This diff will need to be backported to release/3.11.
=> fix(psiphon): increase the maximum runtime to 300s

internal/engine/experiment/psiphon/psiphon.go, internal/engine/experiment/psiphon/psiphon_test.go
This diff backports c527ca1f613ed60161a2fec712c092acecf861f7.
Here's the original commit message:
- - -
See: https://github.com/ooni/probe/issues/1856.
This diff will need to be backported to release/3.11.
=> [backport] fix(psiphon): increase the maximum runtime to 300s (#596)

internal/engine/experiment/signal/signal.go
This diff forwardports 3b1cc1b6afbc29fbc9ff8221d2cd84f34032df60.
- - -
See https://github.com/ooni/probe/issues/1858#issuecomment-970322363
This diff will need forward porting to master.
=> [forwardport] fix(signal): use the correct string to score a measurement (#602)

CONTRIBUTING.md
The text I've written here documents the current process as of
today. The only major change I've added today is the `miniooni-staging`
branch, which previously wasn't published and only lived in the
private machine I was using for building `miniooni`.
=> [ci skip] doc: explain staging branches and binary builds

.github/workflows/android.yml, .github/workflows/ios.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/miniooni.yml, .github/workflows/windows.yml, internal/cmd/miniooni/libminiooni.go, internal/engine/session_nopsiphon.go, internal/engine/session_nopsiphon_test.go, internal/engine/session_psiphon.go, internal/engine/session_psiphon_test.go, mk
This change allows for producing cloud builds using the psiphon
config files. We will add those files as build secrets. Only people
in the organization and collaborators with at least "write"
access could trigger builds containing such secrets.
Before this change, `./mk` unconditionally attempted to clone
github.com/ooni/probe-private. Now, it only checks whether
we need to clone _if_ files are not already there.
This allows us to use GitHub actions and secrets to copy the
files in there _without_ needing to clone a private repo.
Cloning a private repo would require us to include as repository
secret an access token with full `repo` scope, which is a very
broad scope. Instead, by using secrets to include psiphon config,
we are narrowing down the secrets required to make a release build. …
=> fix(mk): do nothing if we already have psiphon config 

.github/workflows/android.yml, .github/workflows/ios.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/miniooni.yml, .github/workflows/windows.yml, internal/cmd/miniooni/libminiooni.go, internal/engine/session_nopsiphon.go, internal/engine/session_nopsiphon_test.go, internal/engine/session_psiphon.go, internal/engine/session_psiphon_test.go, mk
This diff forward ports ea44e99451f345474738b9010ff791759a1f1367.
- - -
This change allows for producing cloud builds using the psiphon
config files. We will add those files as build secrets. Only people
in the organization and collaborators with at least "write"
access could trigger builds containing such secrets.
Before this change, `./mk` unconditionally attempted to clone
github.com/ooni/probe-private. Now, it only checks whether
we need to clone _if_ files are not already there.
This allows us to use GitHub actions and secrets to copy the
files in there _without_ needing to clone a private repo.
Cloning a private repo would require us to include as repository
secret an access token with full `repo` scope, which is a very
broad scope. Instead, by using secrets …
=> [forwardport] fix(mk): do nothing if we already have psiphon config (#605)

.github/workflows/miniooni.yml, CLI/.gitignore, mk
This diff backports 7f0fb5e6190492b5dff1aa6d1cedac7f14c450e9.
- - -
This is the miniooni related part of https://github.com/ooni/probe/issues/1879.
This diff will require backport to the release/3.11 branch.
Conflicts:
* .github/workflows/miniooni.yml
=> [backport] feat: publish miniooni binaries into releases (#607)

internal/engine/experiment/webconnectivity/control.go, internal/engine/experiment/webstepsx/measurer.go, internal/engine/experiment/webstepsx/th.go
(This diff includes a forwardport of b8c530388e66b2cc86abad26d077202782e4a823 from release/3.11)
=> fix(websteps, webconnectivity): send the correct user agent

pkg/oonimkall/eventemitter.go, pkg/oonimkall/task.go, pkg/oonimkall/task_integration_test.go, pkg/oonimkall/task_internal_test.go
If we close the channel to signal the end of a task we may panic
when some background goroutine tries to post on the channel.
This bug is rare but may happen.
See for example https://github.com/ooni/probe/issues/1438.
How can we improve?
First, let us add a timeout when sending to the channel. Given that
the channel is buffered and we have a generous timeout (1/4 of a
second), it's unlikely we will really block. But, in the event in
which a late message appears, we'll eventually _unblock_ when
sending with a timeout. So, now we don't have to worry anymore
about leaking forever a goroutine.
Then, let us change the protocol with which we signal that a task
is done. We used to close the channel. Now, instead we just
synchronously post a nil on the channel when done.
In turn, we interpret …
=> fix(oonimkall): don't close channel to signal end of task

pkg/oonimkall/eventemitter.go, pkg/oonimkall/task.go, pkg/oonimkall/task_integration_test.go, pkg/oonimkall/task_internal_test.go
This diff forward ports 90bf0629b957c912a5a6f3bb6c98ad3abb5a2ff6 to `master`.
If we close the channel to signal the end of a task we may panic
when some background goroutine tries to post on the channel.
This bug is rare but may happen.
See for example https://github.com/ooni/probe/issues/1438.
How can we improve?
First, let us add a timeout when sending to the channel. Given that
the channel is buffered and we have a generous timeout (1/4 of a
second), it's unlikely we will really block. But, in the event in
which a late message appears, we'll eventually _unblock_ when
sending with a timeout. So, now we don't have to worry anymore
about leaking forever a goroutine.
Then, let us change the protocol with which we signal that a task
is done. We used to close the channel. Now, instead we …
=> [forwardport] fix(oonimkall): don't close channel to signal end of task (#619)

pkg/oonimkall/eventemitter.go, pkg/oonimkall/eventemitter_test.go, pkg/oonimkall/runner.go, pkg/oonimkall/runner_internal_test.go, pkg/oonimkall/task.go, pkg/oonimkall/task_integration_test.go
1. add eof channel to event emitter and use this channel as signal
that we shouldn't be sending anymore instead of using a pattern where
we use a timer to decide sending has timed out (because we're using
a buffered channel, it is still possible for some evetns to end up
in the channel if there is space, but this is not a concern, because
the events will be deleted when the channel itself is gone);
2. refactor all tests where we assumed the output channel was closed
to actually use a parallel "eof" channel and use it as signal we
should not be sending anymore (not strictly required but still the
right thing to do in terms of using consistent patterns);
3. modify how we construct a runner so that it passes to the
event emitter an "eof" channel and closes this channel when the
main …
=> fix(oonimkall): improve channel management pattern

pkg/oonimkall/eventemitter.go, pkg/oonimkall/eventemitter_test.go, pkg/oonimkall/runner.go, pkg/oonimkall/runner_internal_test.go, pkg/oonimkall/task.go, pkg/oonimkall/task_integration_test.go
This diff backports 120f2b9fbfa663fb70643a2d82291247fece0504.
1. add eof channel to event emitter and use this channel as signal
that we shouldn't be sending anymore instead of using a pattern where
we use a timer to decide sending has timed out (because we're using
a buffered channel, it is still possible for some evetns to end up
in the channel if there is space, but this is not a concern, because
the events will be deleted when the channel itself is gone);
2. refactor all tests where we assumed the output channel was closed
to actually use a parallel "eof" channel and use it as signal we
should not be sending anymore (not strictly required but still the
right thing to do in terms of using consistent patterns);
3. modify how we construct a runner so that it passes to the
event emitter …
=> [backport] fix(oonimkall): improve channel management pattern (#621)

internal/ptx/snowflake.go, internal/stuninput/stuninput.go, internal/stuninput/stuninput_test.go
We want stunreachability to use the same STUN servers used by
snowflake, so let's start by making a common package holding the
servers. Let's also use this new package in Snowflake.
We're currently not using this package in stunreachability, but
I am going to apply this as a subsequent diff.
Reference issue: https://github.com/ooni/probe/issues/1814. This
issue is a bit complex to address in a single PR, so we are going
to proceed incremntally.
This diff was extracted from https://github.com/ooni/probe-cli/pull/539.
=> refactor: create common package for holding STUN input

internal/cmd/miniooni/libminiooni.go, internal/engine/allexperiments.go, internal/engine/experimentbuilder.go, internal/engine/inputloader.go, internal/engine/inputloader_test.go
This commit introduces a new `InputLoader` policy by which, if no
input is provided, we use a static default input list.
We also modify the code to use this policy for dnscheck and
stunreachability, with proper input.
We also modify `miniooni` to pass the new `ExperimentName` field to
the `InputLoader` to indicate which default input list to use.
This diff is part of a set of diffs aiming at fixing
https://github.com/ooni/probe/issues/1814 and has been
extracted from https://github.com/ooni/probe-cli/pull/539.
What remains to be done, after this diff has landed is to ensure
things also work for ooniprobe and oonimkall.
=> refactor: introduce and use InputOrStaticDefault

cmd/ooniprobe/internal/nettests/dnscheck.go, cmd/ooniprobe/internal/nettests/nettests.go, cmd/ooniprobe/internal/nettests/stunreachability.go, cmd/ooniprobe/internal/nettests/web_connectivity.go
This diff is part of https://github.com/ooni/probe/issues/1814 and
teaches `ooniprobe` to run dnscheck and stunreachability by using the
default static input feature of the `InputLoader`.
I've manually tested that we can still run `websites` like
we did before (including category filtering).
I've also manually tested that now we can run `experimental` and
get parseable results for dnscheck and stunreachability.
With this diff in, we have fixed the original problem highlighted in
the https://github.com/ooni/probe/issues/1814 issue.
Yet, because of the way in which I solved the problem, there is
more work to do. My changes have broken stunreachability for
mobile and now it's time I apply fixes to make it work again.
This diff was extracted from https://github.com/ooni/probe-cli/pull/539, …
=> fix(ooniprobe): dnscheck,stunreachability run w/ default input

internal/engine/inputloader.go, pkg/oonimkall/taskrunner.go, pkg/oonimkall/taskrunner_test.go
Previous work to make https://github.com/ooni/probe/issues/1814
possible has broken running stunreachability on mobile.
This diff repairs the blunder and allows to run any experiment
using InputOrStaticDefault with oonimkall.
Diff extracted from https://github.com/ooni/probe-cli/pull/539.
=> fix(oonimkall): run tests with InputOrStaticDefault policy

internal/version/version.go
As mentioned in https://github.com/ooni/probe/issues/1845#issuecomment-986540868,
I did a mistake and published an `-alpha` debian package, so I need to
bump master's version to 3.14 and create a 3.13 release train.
やれやれだぜ
=> chore: set master's version to 3.14.0-alpha

MOBILE/ios/template.podspec
This diff forward ports 21a9b977eef7a8c8a6107aec713b6202ba9e5d48
The template was still wrong and was referencing a .framework
while now we generate a .xcframework.
See, e.g., this failed build: https://github.com/ooni/probe-ios/runs/4444313406?check_suite_focus=true
Part of https://github.com/ooni/probe/issues/1843
=> [forwardport] fix(template.podspec): the correct suffix is xcframework (#639)

internal/engine/experiment/webstepsx/measurer.go, internal/engine/experiment/webstepsx/th.go, internal/measurex/http.go, internal/measurex/measurer.go, internal/mlablocate/mlablocate.go, internal/mlablocatev2/mlablocatev2.go, internal/ooapi/dependencies.go, internal/ooapi/fake_test.go, internal/ooapi/httpclient_test.go
This counts as a follow-up cleanup as part of doing
https://github.com/ooni/probe/issues/1885.
=> cleanup: remove redundant HTTPClient definition

internal/ptx/dependencies.go, internal/ptx/obfs4.go
We can just use model.SimpleDialer here.
See https://github.com/ooni/probe/issues/1885.
=> cleanup(ptx): remove redundant dialer definition

internal/measurex/http.go, internal/measurex/measurer.go, internal/measurex/tracing.go
This diff lightly refactors the code in measurex to allow a user
to configure all possible timeouts and the max-snapshot-size.
There is currently a little bit of tension between setting timeouts
inside of measurex and the watchdog timeouts inside of netxlite.
This tension has been documented.
Let us repeat the issue also in this commit message. If you are
using a masurex.Measurer configured with very large timeouts and
the underlying netxlite implementation uses shorter whatchdog
timeouts, then you are going to see shorter than expected timeouts.
Ideally, we would like to have just a single timeout but there is
no way to ask the context "hey, can you tell me if you already have
a configured timeout?".
It may be that the right solution is to modify netxlite to have
some sort of …
=> refactor(measurex): allow to configure timeouts and max-snapshot-size

internal/cmd/apitool/main.go, internal/engine/experiment/webconnectivity/control.go, internal/engine/experiment/websteps/control.go, internal/engine/geolocate/avast.go, internal/engine/geolocate/ipconfig.go, internal/engine/geolocate/ipinfo.go, internal/engine/geolocate/ubuntu.go, internal/engine/httpx/httpx.go, internal/engine/httpx/httpx_test.go, internal/engine/probeservices/bouncer.go, internal/engine/probeservices/checkin.go, internal/engine/probeservices/checkreportid.go, internal/engine/probeservices/checkreportid_test.go, internal/engine/probeservices/collector.go, internal/engine/probeservices/login.go, internal/engine/probeservices/measurementmeta.go, internal/engine/probeservices/measurementmeta_test.go, internal/engine/probeservices/probeservices.go, internal/engine/probeservices/psiphon.go, internal/engine/probeservices/register.go, internal/engine/probeservices/tor.go, internal/engine/probeservices/urls.go
As mentioned in https://github.com/ooni/probe/issues/1951, one of
the main issues I did see with httpx.APIClient is that in some cases
it's used in a very fragile way by probeservices.Client.
This happens in psiphon.go and tor.go, where we create a copy of
the APIClient and then modify it's Authorization field.
If we ever refactor probeservices.Client to take a pointer to
httpx.Client, we are now mutating the httpx.Client.
Of course, we don't want that to happen.
This diff attempts to address such a problem as follows:
1. we create a new APIClientTemplate type that holds the same
fields of an APIClient and allows to build an APIClient
2. we modify every user of APIClient to use APIClientTemplate
3. when we need an APIClient, we build it from the corresponding
template and, when we need to …
=> refactor(httpx): hide the real APIClient

internal/engine/experiment/webconnectivity/control.go, internal/engine/experiment/websteps/control.go, internal/engine/geolocate/avast.go, internal/engine/geolocate/ipconfig.go, internal/engine/geolocate/ipinfo.go, internal/engine/geolocate/ubuntu.go, internal/engine/httpx/httpx.go, internal/engine/httpx/httpx_test.go, internal/engine/probeservices/bouncer.go, internal/engine/probeservices/checkreportid.go, internal/engine/probeservices/collector.go, internal/engine/probeservices/measurementmeta.go, internal/engine/probeservices/urls.go
1. we want optionally to log the body (we don't want to log the body
when we're fetching psiphon secrets or tor targets)
2. we want body logging to _also_ happen on error since this is quite
useful to debug possible errors when accessing the API
This diff adds the above functionality, which were previously
described in https://github.com/ooni/probe/issues/1951.
This diff also adds comprehensive testing.
=> feat(httpx): implement optional body logging also on http error

internal/engine/experiment/tor/tor.go, internal/engine/experiment/tor/tor_test.go, internal/measurex/easy.go, internal/runtimex/runtimex.go, internal/runtimex/runtimex_test.go
This diff rewrites the tor experiment to use measurex "easy" API.
To this end, we need to introduce an "easy" measurex API, which basically
performs easy measurements returning two pieces of data:
1. the resulting measurement, which is already using the OONI
archival data format and is always non-nil
2. a failure (i.e., the pointer to an error string), which
is nil on success and points to a string on failure
With this change, we should now be able to completely dispose of
the original netx API, which was only used by tor.
Reference issue: https://github.com/ooni/probe/issues/1688.
=> refactor(tor): rewrite using measurex

internal/engine/experiment/dash/dash.go, internal/engine/experiment/dash/dash_test.go, internal/engine/experiment/dash/doc.go, internal/engine/experiment/dnscheck/dnscheck.go, internal/engine/experiment/example/example.go, internal/engine/experiment/ndt7/dial.go, internal/engine/experiment/ndt7/dial_test.go, internal/engine/experiment/ndt7/doc.go, internal/engine/experiment/ndt7/ndt7.go, internal/engine/experiment/ndt7/ndt7_test.go, internal/engine/experiment/psiphon/psiphon.go, internal/engine/experiment/psiphon/psiphon_test.go, internal/engine/experiment/run/dnscheck.go, internal/engine/experiment/run/doc.go, internal/engine/experiment/run/run.go, internal/engine/experiment/run/run_test.go, internal/engine/experiment/stunreachability/stunreachability.go, internal/engine/experiment/stunreachability/stunreachability_test.go, internal/engine/experiment/tlstool/tlstool.go, internal/engine/experiment/tor/tor.go, internal/engine/experiment/urlgetter/urlgetter.go, internal/engine/experiment/urlgetter/urlgetter_test.go, internal/engine/experiment/webconnectivity/doc.go, internal/engine/experiment/webconnectivity/webconnectivity.go, internal/model/experiment.go, internal/netxlite/http.go, internal/netxlite/http_test.go
Since https://github.com/ooni/probe-cli/pull/527, if an experiment
returns an error, the corresponding measurement is not submitted since
the semantics of returning an error is that something fundamental
went wrong (e.g., we could not parse the input URL).
This diff ensures that all experiments only return and error when
something fundamental was wrong and return nil otherwise.
Reference issue: https://github.com/ooni/probe/issues/1808.
=> fix: ensure experiments return nil when we want to submit

internal/cmd/jafar/uncensored/uncensored.go, internal/engine/experiment/urlgetter/configurer.go, internal/engine/netx/netx.go, internal/engine/netx/netx_test.go
The DNSClient type existed because the Resolver type did not
include CloseIdleConnections in its signature.
Now that Resolver includes CloseIdleConnections, the DNSClient
type has become unnecessary and can be safely removed.
See https://github.com/ooni/probe/issues/1956.
=> cleanup(netx): remove the DNSClient type

cmd/ooniprobe/internal/cli/list/list.go, cmd/ooniprobe/internal/database/actions.go, cmd/ooniprobe/internal/database/actions_test.go, cmd/ooniprobe/internal/database/models.go
With a dataset of 1489 test, the ooniprobe list command went from
taking 17.27s to run, to requiring 0.17s or a 100x speed boost
This fixes: https://github.com/ooni/probe/issues/1966
=> Refactor the list measurements function to make use of nested queries

go.mod, go.sum, internal/engine/experiment/torsf/torsf.go, internal/engine/experiment/torsf/torsf_test.go, internal/ptx/ptx.go, internal/ptx/snowflake.go, internal/ptx/snowflake_test.go
This diff contains the following changes and enhancements:
1. upgrade snowflake to v2
2. observe that we were not changing defaults from outside of snowflake.go, so remove code allowing to do that;
3. bump the timeout to 600 seconds (it seems 300 was not always enough based on my testing);
4. add useful knob to disable `torsf` progress (it's really annoying on console, we should do something about this);
5. ptx.go: avoid printing an error when the connection has just been closed;
6. snowflake: test AMP cache, see that it's not working currently, so leave it disabled.
Related issues: https://github.com/ooni/probe/issues/1845, https://github.com/ooni/probe/issues/1894, and https://github.com/ooni/probe/issues/1917.
=> feat(snowflake): upgrade to v2 (+ small tweaks)

cmd/ooniprobe/internal/nettests/groups.go, cmd/ooniprobe/internal/nettests/torsf.go, internal/engine/experiment/torsf/torsf.go, internal/engine/experiment/torsf/torsf_test.go
Reference issue: https://github.com/ooni/probe/issues/1917.
I needed to change the summary key type returned by `torsf` to be a value. It seems the DB layer assumes that. If we pass it a pointer, it panics because it's experiment a value rather than a pointer 🤷.
=> feat(ooniprobe): add torsf to experimental group

internal/engine/experiment/torsf/torsf.go
This commit message is the same across probe-cli, probe-desktop,
and probe-android. With the changes contained in the enclosed
diff, I'm starting to add support for torsf for android and for
desktop.
When smoke testing that torsf was WAI, I also noticed that its
progress messages in output are too frequent. We may want to do
better in a future version when we'll be able to read `tor`'s
output. In the meanwhile, make the progress messages less
frequent and indicated the maximum runtime inside of the messages
themselves. This improved message, albeit not so nice from the
UX PoV, should at least provide a clue that we're not stuck.
Reference issue: https://github.com/ooni/probe/issues/1917
=> feat: start adding torsf to desktop and mobile

internal/tunnel/config.go, internal/tunnel/tor.go, internal/tunnel/tordesktop.go, internal/tunnel/tormobile.go
While there, ensure that we print a warning if we cannot find
the correct tor binary.
Work part of https://github.com/ooni/probe/issues/1917.
=> fix(i/t/tor.go): show correct command line

internal/engine/internal/sessionresolver/resolvermaker.go
I have re-added to session resolver the lines of code that were telling it to speak DNS-over-HTTPS using QUIC and HTTP3 with dns.google. Inspected the resulting measurement and it works perfectly.
Also, the test coverage is 99.3% (same as before adding those lines)
=> fix(resolvermake): re-enable dns.google DoH HTTP3 resolutions

internal/cmd/jafar/uncensored/uncensored_test.go
I have tested this integration test locally and it's now WAI.
It may be that it will fail again when run on GitHub Actions, which will
indicate we cannot fully trust Actions for running _some_ tests.
Closes https://github.com/ooni/probe/issues/1913.
=> fix(jafar): re-enable previously broken integration test

Readme.md, pkg/oonimkall/task.go
The oonimkall package is only public for technical reasons. We
cannot use `go mobile` on a private package. We consider oonimkall
our private interface to our mobile apps, thus we reserve the
right to change its API without bumping the major number.
We'll bump the major number in case of breaking changes in the
cmd/ooniprobe CLI interface, or in case of other major improvements
that significantly modify cmd/ooniprobe.
=> doc: clarify semantic versioning policy

internal/engine/experiment/urlgetter/getter_integration_test.go, internal/engine/netx/httptransport/saver.go, internal/engine/netx/httptransport/saver_test.go, internal/engine/netx/netx.go, internal/engine/netx/netx_test.go
This diff forward ports b6db4f64dc83a2a27ee3ce6bba5ac93db922832d, whose
original log message is the following:
- - -
We're now using ooni/oohttp as our HTTP library in most cases.
A limitation of this library is that net/http/httptrace does not
work very well and reliably because (1) we need to use oohttp's
version of that code and (2) we cannot observe net events.
I noticed this fact because an integration test for collecting
HTTP performance metrics was broken.
The best solution here is to remove this functionality, since
it was basically unused in the repository. Only some integration
tests inside urlgetter bothered with these metrics.
A more clinical fix would have been to use ooni/oohttp/httptrace
instead of net/http/httptrace in the stdlib, but it does not
seem to be a good idea, …
=> [forwardport] fix(netx): stop collecting HTTP performance metrics

internal/cmd/jafar/iptables/iptables_integration_test.go
This commit forward ports 8f2d7945f806579af4d0495f4b8f5a6a01eefb0c, whose
commit message is as follows:
- - -
The discrepancy I was seeing between my local tests and tests run
in the CI is that my systemd is configured to use DoT.
Hence, it was bypassing iptables rules because the query was sent
over an encrypted tunnel. Using a pure Go resolver fixes since
that always uses UDP, so the filter works.
Also, reason that we want as minimal as possible tests, so refactor
a test so that we use just a resolver rather than an HTTP client, and,
while there, also enforce this resolver to be a pure Go resolver.
Reference issue: https://github.com/ooni/probe/issues/2016
This diff WILL need to be forward ported to master.
=> [forwardport] fix(jafar/iptables/test): force using pure Go resolver

.gitignore, QA/webconnectivity.py
This diff forward ports 36ba3630c9002db0bd79e3a7e49641ce6b665471,
whose original commit message follows:
- - -
This diff contains minimal changes to make webconnectivity QA
WAI with the new Web Connectivity test helper.
It seems we're currently doing round robin between the old and
the new implementation, so I needed to locally pin my probes
to use the new implementation by changing the code. But, obviously,
I don't want to commit this code.
Likewise, in my working environment, I need to build the docker
container using `docker buildx build --platform linux/amd64`, but
I am not sure whether to commit this code.
While there, I noticed there was a missing QA test for the case
in which we're passing through a transparent HTTP proxy. I noticed
as well that the test that said it was passing …
=> [forwardport] fix(qa): adapt to new wcth

internal/engine/allexperiments.go, internal/engine/experiment/quicping/crypto.go, internal/engine/experiment/quicping/quic.go, internal/engine/experiment/quicping/quicping.go, internal/engine/experiment/quicping/quicping_test.go
This experiment pings a QUIC-able host. It can be used to measure QUIC availability independently from TLS.
This is the reference issue: https://github.com/ooni/probe/issues/1994
- a QUIC Initial packet with a size of 1200 bytes (minimum datagram size defined in the [RFC 9000](https://www.rfc-editor.org/rfc/rfc9000.html#initial-size)),
- with a random payload (i.e. no TLS ClientHello),
- with the version string 0xbabababa which forces Version Negotiation at the server.
QUIC-able hosts respond to the QUIC PING with a Version Negotiation packet.
The input is a domain name or an IP address. The default port used by quicping is 443, as this is the port used by HTTP/3. The port can be modified with the `-O Port=` option.
The default number of repetitions is 10, it can be changed with `-O …
=> feat: add an experimental quicping experiment

CONTRIBUTING.md
There is no reference issue for this pull request, since this is an improvement for the `CONTRIBUTING.md`
Added golang resources, pointers to our Slack and IRC channels  in `CONTRIBUTING.md` which helps new contributors to understand golang better and reach out to us on the platforms mentioned for discussion.
=> doc(CONTRIBUTING.md): add golang resources and links to community channels

go.mod, internal/engine/experiment/ndt7/dial.go
This change should prevent old clients (e.g., Android 6) from
failing to perform a ndt7 experiment because their internal CA
bundle is now too old.
Reference issue: https://github.com/ooni/probe/issues/2031
While there, run `go mod tidy` to fix a minor inconsistence in
the current `go.mod` file.
This diff WILL require a backport to release/3.14.
=> fix(ndt7): force our bundled CA pool

internal/engine/experiment/hirl/hirl.go, internal/engine/experiment/urlgetter/multi.go, internal/engine/experiment/webconnectivity/control.go, internal/engine/experiment/webconnectivity/dnslookup.go, internal/engine/experiment/webconnectivity/httpget.go, internal/engine/internal/sessionresolver/sessionresolver.go
This PR aims to refactor and ensure "ok" is returned on success of an experiment rather than `<nil>` value.
=> cleanup: use ErrorToStringOrOK func in other tests that returns nil

go.mod, go.sum
See https://github.com/ooni/probe/issues/1996
This diff updates the ooni/go-libtor dependency to v1.1.5.
=> chore: use ooni/go-libtor v1.1.5

.github/workflows/alltests.yml, .github/workflows/android.yml, .github/workflows/coverage.yml, .github/workflows/generate.yml, .github/workflows/ios.yml, .github/workflows/jafar.yml, .github/workflows/macos.yml, .github/workflows/miniooni.yml, .github/workflows/netxlite.yml, .github/workflows/oohelperd.yml, .github/workflows/qafbmessenger.yml, .github/workflows/qahhfm.yml, .github/workflows/qahirl.yml, .github/workflows/qatelegram.yml, .github/workflows/qawebconnectivity.yml, .github/workflows/qawhatsapp.yml, .github/workflows/tarball.yml, .github/workflows/windows.yml, mk
See https://github.com/ooni/probe/issues/2076
They released go1.17.9 in the meanwhile, so upgrade to using it rather than using go1.17.8.
=> chore: use go1.17.9

cmd/ooniprobe/internal/cli/geoip/geoip_test.go
This is just a typo fix in the `TestMaybeLookupLocationSuccess` in `cmd/ooniprobe/internal/cli/geoip/geoip_test.go`. As a result it does not refer to any existing issues in `ooni/probe`
=> fix(cli/geoip): correct typos in tests

internal/engine/experiment/torsf/torsf.go
https://github.com/ooni/probe-cli/blob/85664f1e31de0844f444af7c690a57628ff79ff7/internal/engine/experiment/torsf/torsf.go#L200-L201
The regex fragment [a-zA-z]+ was matching strings with an underscore, like conn_pt and onehop_create. Look closely: the second z, which you would expect to be uppercase, is actually lowercase. The underscore character _ (ASCII 95) lies between A (ASCII 65) and z (ASCII 122), which is why the regex works for its intended purpose, despite containing an evident typo.
A small fix in regex to increase its readabliity and thus avoid extra characters like `[\]^_\``.
=> fix(torsf): ensure tor-logs-filtering regexp is correct

internal/engine/experiment/torsf/torsf.go
Added default timeout (set context timeout) to the torsf measurement results for better readability and understanding.
=> feat(torsf): add default_timeout test keys

internal/engine/experiment/urlgetter/getter.go, internal/engine/netx/archival/archival.go, internal/engine/netx/archival/archival_test.go, internal/engine/netx/tlsdialer/saver.go, internal/model/archival.go
- Added IP addresses to the tls_handshakes list
- Tested measurement outputs on webconnectivity, IM and riseupvpn experiments. 
We can track the tls_handshakes issue here. Although I have made some changes, we may come up with a better approach to handle this issue.
=> tls_handshakes: add endpoint addresses to handshake list

internal/engine/allexperiments.go, internal/engine/experiment/tlsping/tlsping.go, internal/engine/experiment/tlsping/tlsping_test.go
See https://github.com/ooni/probe/issues/2088.
=> feat: introduce the tlsping experiment

internal/httpx/httpx.go, internal/httpx/httpx_test.go
This PR ensures that given a BaseURL `https://example.com/example` and an URLPath of `/foo/bar`, the code in httpx should access `https://example.com/example/foo/bar`. Also, the documentation for the same.
=> fix(httpx): correctly combine paths

internal/engine/allexperiments.go, internal/engine/experiment/torsf/testdata/partial.log, internal/engine/experiment/vanillator/integration_test.go, internal/engine/experiment/vanillator/testdata/partial.log, internal/engine/experiment/vanillator/testdata/tor.log, internal/engine/experiment/vanillator/vanillator.go, internal/engine/experiment/vanillator/vanillator_test.go, internal/model/mocks/logger.go, internal/model/mocks/logger_test.go, internal/torlogs/testdata/tor.log, internal/torlogs/torlogs.go, internal/torlogs/torlogs_test.go
This diff re-implements the vanilla_tor experiment. This experiment was
part of the ooni/probe-legacy implementation.
The reference issue is https://github.com/ooni/probe/issues/803. We didn't
consider the possible improvements mentioned by the
https://github.com/ooni/probe/issues/803#issuecomment-598715694 comment,
which means we'll need to create a follow-up issue for them. We will
then decide whether, when, and how to implement those follow-up measurements
either into `vanilla_tor` or into the existing `tor` experiment.
This novel `vanilla_tor` implementation emits test_keys that are mostly
compatible with the original implementation, however:
1. the `timeout` is a `float64` rather than integer (but the default
timeout is an integer, so there are no JSON-visible changes);
2. the …
=> feat: re-implement the vanilla_tor experiment

internal/netxlite/parallelresolver.go, internal/netxlite/parallelresolver_test.go, internal/netxlite/serialresolver.go
This diff imports the parallel resolver from websteps winter 2022
edition, which was originally implemented here:
https://github.com/bassosimone/websteps-illustrated/commit/55231d73cd822a851f532dea1b8089694d58100e
See https://github.com/ooni/probe/issues/2096
=> feat(netxlite): implement parallel resolver

internal/netxlite/quirks.go, internal/netxlite/quirks_test.go
Originally https://github.com/bassosimone/websteps-illustrated/commit/966e7f7cdde534dca8beaf54dda08746660cc324
See https://github.com/ooni/probe/issues/2096
=> refactor(netxlite): consolidate IPv4/IPv6 checking code

internal/archival/quic.go, internal/archival/quic_test.go, internal/archival/quic_test_go118.go, internal/measurex/quic.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go
This diff moves the handshake completion logic inside netxlite. So every user of netxlite now can trust the fact that the handshake is complete when they receive a quic conn.
=> cleanup(quic): wait for handshake completion in netxlite

internal/engine/experiment/urlgetter/configurer_test.go, internal/engine/experiment/webstepsx/th.go, internal/engine/netx/netx.go, internal/engine/netx/netx_test.go, internal/engine/netx/resolver/integration_test.go, internal/measurex/resolver.go, internal/netxlite/classify.go, internal/netxlite/dnsoverhttps.go, internal/netxlite/dnsoverhttps_test.go, internal/netxlite/dnsovertcp.go, internal/netxlite/dnsovertcp_test.go, internal/netxlite/dnsoverudp.go, internal/netxlite/dnsoverudp_test.go, internal/netxlite/filtering/dns.go, internal/netxlite/resolver.go, internal/netxlite/resolver_test.go
This diff has been extracted from https://github.com/bassosimone/websteps-illustrated/commit/c2f7ccab0ec971d5c084ea4c571b76f7530b28ee
See https://github.com/ooni/probe/issues/2096
=> refactor(netxlite): add Transport suffix to DNS transports

internal/cmd/apitool/main_test.go, internal/cmd/jafar/uncensored/uncensored.go, internal/cmd/oohelper/internal/fake_test.go, internal/cmd/oohelperd/internal/webconnectivity/fake_test.go, internal/engine/internal/sessionresolver/sessionresolver.go, internal/engine/internal/sessionresolver/sessionresolver_test.go, internal/engine/netx/resolver/cache.go, internal/engine/netx/resolver/cache_test.go, internal/engine/netx/resolver/fake_test.go, internal/engine/netx/resolver/saver_test.go, internal/engine/probeservices/checkreportid_test.go, internal/model/mocks/dnsdecoder.go, internal/model/mocks/dnsdecoder_test.go, internal/model/mocks/resolver.go, internal/model/mocks/resolver_test.go, internal/model/netx.go, internal/netxlite/bogon.go, internal/netxlite/dnsdecoder.go, internal/netxlite/dnsdecoder_test.go, internal/netxlite/parallelresolver.go, internal/netxlite/parallelresolver_test.go, internal/netxlite/resolver.go, internal/netxlite/resolver_test.go, internal/netxlite/serialresolver.go, internal/netxlite/serialresolver_test.go, internal/ooapi/integration_test.go
This diff has been extracted from https://github.com/bassosimone/websteps-illustrated/commit/eb0bf38957e79fbad198fcdc9f9c7b36f61a8e2c.
See https://github.com/ooni/probe/issues/2096.
While there, skip the broken tests caused by issue
https://github.com/ooni/probe/issues/2098.
=> feat(netxlite): implements NS queries

internal/model/netx.go, internal/netxlite/dnsdecoder.go, internal/netxlite/dnsdecoder_test.go
Previously, the DNS decoder did not check whether it was parsing
a DNS query or a DNS response, which was wrong.
As a side note, it seems I am using "reply" in the codebase instead
of "response". The latter seems correct DNS terminology.
This diff has been extracted from https://github.com/bassosimone/websteps-illustrated/commit/9249d14f80b4c685234da8e344b36c8904ee69e9
See https://github.com/ooni/probe/issues/2096.
=> fix(netxlite): ensure we only accept DNS responses

internal/engine/experiment.go, internal/model/experiment.go
- Passed the `TestHelpers` field to `RunAsyc` and `MeasureAsync`. This reflects the `test_helpers` in the measurement.
- Spec already contains the correct output.
=> fix(webconnectivity): Add TH to measurement

mk
The one we were using previously does not work, so use the LTS
rather than using the latest non-LTS stable.
Part of https://github.com/ooni/probe/issues/2100
=> fix(mk): use NDK version that works with gomobile

internal/netxlite/dnsoverudp.go, internal/netxlite/dnsoverudp_test.go, internal/netxlite/filtering/dns.go, internal/netxlite/filtering/dns_test.go, internal/netxlite/filtering/doc.go, internal/netxlite/filtering/http.go, internal/netxlite/filtering/tls.go, internal/netxlite/integration_test.go, script/nocopyreadall.bash
This diff introduces support for observing additional DNS-over-UDP
responses in some censored environments (e.g. China).
After some uncertainty around whether to use connected or unconnected
UDP sockets, I eventually settled for connected.
Here's a recap:
|                         | connected | unconnected |
| ----------------------- | --------- | ----------- |
| see ICMP errors         | ✔️         | ❌          |
| responses from any server | ❌        | ✔️           |
Because most if not all DNS resolvers expect answers from exactly
the same servers to which they sent the query, I would say that
it's more important to have some limited ability of observing the
effect of ICMP errors (e.g., host_unreachable when we set a low
TTL and send out a query to a server).
Therefore, my choice was …
=> feat(netxlite): observe additional DNS-over-UDP responses

internal/netxlite/dnsoverudp.go, internal/netxlite/dnsoverudp_test.go
To this end, we need to refactor the implementation to give the
DNSOverUDPChannel owenership over the net.Conn.
Once this happens, DNSOverUDPChannel.Close closes the conn.
When the conn is closed, the background goroutine will terminate
immediately because any blocking I/O operation will be immediately
unblocked and return net.ErrClosed.
See https://github.com/ooni/probe/issues/2099#issuecomment-1139066946
=> fix(dnsoverudp): allow to cancel async round trip immediately

internal/model/netx.go, internal/netxlite/getaddrinfo_otherwise.go
In https://github.com/ooni/probe/issues/2029#issuecomment-1140805266, we
explained why calling it "netgo" would be incorrect.
In other words, we can get the platform's `getaddrinfo` as long as
we're not cross compiling. We do cross compile `ooniprobe`, actually
it's not even possible to cross compile it.
For increased accuracy, we should stop cross compiling `miniooni`
as well, so it would also directly use `getaddrinfo`.
This diff fixes at the same time ooni/probe-cli and ooni/spec
and we'll open two pull requests in parallel.
=> netxlite: do not call netgo the CGO_ENABLED=0 resolver

internal/engine/netx/dialer/dialer.go, internal/engine/netx/dialer/dialer_test.go, internal/netxlite/dialer.go, internal/netxlite/dialer_test.go, internal/netxlite/legacy.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go, internal/netxlite/resolver.go, internal/netxlite/resolver_test.go, internal/netxlite/tls_test.go
This diff modifies the construction of a dialer to allow one
to insert custom dialer wrappers into the dialers chain.
The point of the chain in which we allow custom wrappers is the
optimal one for connect, read, and write measurements.
This new design is better than the previous netx design since
we don't need to construct the whole chain manually now.
The work in this diff is part of the effort to make engine/netx
just a tiny wrapper around netxlite.
See https://github.com/ooni/probe/issues/2121.
=> refactor(netxlite): allow easy dialer chain customization

internal/engine/netx/netx.go, internal/netxlite/dialer.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go
Like the previous diff, but for creating QUIC dialers
See https://github.com/ooni/probe/issues/2121.
=> refactor(netxlite): allow easy QUIC dialer chain customization

internal/engine/experiment/urlgetter/configurer_test.go, internal/engine/netx/netx.go, internal/engine/netx/netx_test.go, internal/engine/netx/tracex/archival.go, internal/engine/netx/tracex/archival_test.go, internal/engine/netx/tracex/dialer.go, internal/engine/netx/tracex/doc.go, internal/engine/netx/tracex/event.go, internal/engine/netx/tracex/http.go, internal/engine/netx/tracex/http_test.go, internal/engine/netx/tracex/quic.go, internal/engine/netx/tracex/quic_test.go, internal/engine/netx/tracex/resolver.go, internal/engine/netx/tracex/resolver_test.go, internal/engine/netx/tracex/saver.go, internal/engine/netx/tracex/saver_test.go, internal/engine/netx/tracex/tls.go, internal/engine/netx/tracex/tls_test.go
The code that is now into the tracex package was written a long
time ago, so let's start to make it more in line with the coding
style of packages that were written more recently.
I didn't apply all the changes I'd like to apply in a single diff
and for now I am committing just this diff.
Broadly, what we need to do is:
1. improve documentation
2. ~always use pointer receivers (object receives have the issue
that they are not mutable by accident meaning that you can mutate
them but their state do not change after the call returns, which
is potentially a source of bugs in case you later refactor to use
a pointer receiver, so always use pointer receivers)
3. ~always avoid embedding (let's say we want to avoid embedding
for types we define and it's instead fine to embed types that are …
=> refactor(tracex): start applying recent code conventions

internal/engine/netx/dialer/dialer.go, internal/engine/netx/netx.go, internal/engine/netx/tracex/dialer.go, internal/engine/netx/tracex/saver.go, internal/engine/netx/tracex/tls_test.go, internal/model/netx.go, internal/netxlite/dialer.go, internal/netxlite/dialer_test.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go
Rather than passing functions to construct complex objects such
as Dialer and QUICDialer, pass interface implementations.
Ensure that a nil implementation does not cause harm.
Make Saver implement the correct interface either directly or
indirectly. We need to implement the correct interface indirectly
for TCP conns (or connected UDP sockets) because we have two
distinct use cases inside netx: observing just the connect event
and observing just the I/O events.
With this change, the construction of composed Dialers and
QUICDialers is greatly simplified and more obvious.
Part of https://github.com/ooni/probe/issues/2121
=> refactor(netxlite): better integration with tracex

internal/engine/experiment/urlgetter/configurer_test.go, internal/engine/netx/netx.go, internal/engine/netx/netx_test.go, internal/engine/netx/tracex/archival.go, internal/engine/netx/tracex/archival_test.go, internal/engine/netx/tracex/dialer.go, internal/engine/netx/tracex/dialer_test.go, internal/engine/netx/tracex/event.go, internal/engine/netx/tracex/http.go, internal/engine/netx/tracex/http_test.go, internal/engine/netx/tracex/quic.go, internal/engine/netx/tracex/quic_test.go, internal/engine/netx/tracex/resolver.go, internal/engine/netx/tracex/resolver_test.go, internal/engine/netx/tracex/saver_test.go, internal/engine/netx/tracex/tls.go, internal/engine/netx/tracex/tls_test.go
The exercise already allowed me to notice issues such as fields not
being properly initialized by savers.
This is one of the last steps before moving tracex away from the
internal/netx package and into the internal package.
See https://github.com/ooni/probe/issues/2121
=> refactor(tracex): convert to unit testing

internal/engine/experiment/dnscheck/dnscheck.go
This diff forward ports b606494db8a9293384efaf5c33a88601f6e1e2a6
to the main development branch.
Dnscheck is emitting progress and the experiment controller is
also emitting progress. This messes up the progress bar.
See https://github.com/ooni/probe/issues/2058#issuecomment-1141638067
=> [forwardport] fix(dnscheck): stop emitting progress

internal/tracex/archival.go, internal/tracex/archival_test.go, internal/tracex/dialer.go, internal/tracex/dialer_test.go, internal/tracex/event.go, internal/tracex/http.go, internal/tracex/http_test.go, internal/tracex/quic.go, internal/tracex/quic_test.go, internal/tracex/resolver.go, internal/tracex/resolver_test.go, internal/tracex/tls.go, internal/tracex/tls_test.go
There are two reasons why this is beneficial:
1. github.com/google/go-cmp is more annoying to use for comparing
data structures when there are interfaces to compare. Sure, there's
a recipe for teaching it to compare errors, but how about making
the errors trivially comparable instead?
2. if we want to send errors over the network, JSON serialization
works but we cannot unmarshal the resulting string back to an error,
so how about making this representation trivial to serialize (we
are not going this now, but we need this property for websteps and
it may be sensible to try to avoid to have duplicate code because
of that -- measurex currently duplicates many tracex functionality
and this is quite unfortunate because it slows development down)
Additionally, if an error is a string:
3. we can …
=> refactor(tracex): internally represent errors as strings

internal/tracex/archival.go, internal/tracex/archival_test.go, internal/tracex/event.go, internal/tracex/quic.go, internal/tracex/quic_test.go, internal/tracex/tls.go, internal/tracex/tls_test.go
By just storing the raw certificate we simplify the internal data
structure we use. In turn, this enables us to write better unit tests
using github.com/google/go-cmp where we can construct the expected
result and compare with that. (Yeah, in principle we could also
construct the full certificate but I'm not sure it's worth the effort
since we basically only care about the raw certificate.)
The general idea here is to make tracex more tested. Once it's more
tested, I will create separate structs for each event, which is
something that measurex also does. Once that is done, we can start
ensuring that the code in measurex and the code in tracex do the
same thing in terms of storing observations. When also this is done,
we can then rewrite measurex to use tracex directly.
The overall goal is …
=> refactor(tracex): internally store just the raw certificate

internal/cmd/jafar/README.md, internal/cmd/jafar/httpproxy/httpproxy_test.go, internal/cmd/jafar/iptables/iptables_integration_test.go, internal/cmd/jafar/main.go, internal/cmd/jafar/resolver/resolver_test.go, internal/cmd/jafar/tlsproxy/tlsproxy_test.go, internal/cmd/jafar/uncensored/uncensored.go, internal/cmd/jafar/uncensored/uncensored_test.go, internal/netxlite/filtering/dns.go, internal/netxlite/filtering/http.go, internal/netxlite/filtering/http_test.go, internal/netxlite/filtering/tls.go, internal/netxlite/filtering/tls_test.go, internal/netxlite/http.go, internal/netxlite/http_test.go, internal/netxlite/resolvercore.go, internal/netxlite/resolvercore_test.go, internal/tracex/http_test.go, script/nocopyreadall.bash
There's no point in doing that. Also, once this change is merged, it becomes easier to cleanup/simplify netx.
See https://github.com/ooni/probe/issues/2121
=> cleanup(jafar): do not depend on netx and urlgetter

internal/engine/netx/httptransport.go, internal/engine/netx/netx.go, internal/engine/netx/netx_test.go, internal/netxlite/http.go, internal/netxlite/http3.go, internal/netxlite/http3_test.go, internal/netxlite/legacy.go
1. Use the netxlite.NewHTTPTransport factory for creating a new
HTTP2 (and HTTP1) transport;
2. Recognize the netxlite.NewOOHTTPTransport has now become
an implementation detail so make it private;
3. Recognize that netxlite.NewHTTP3Transport should call
netxlite.WrapTransport so it returns the same typechain
returned by netxlite.NewHTTPTransport (modulo, of course,
the real underlying transport), so ensure that we are
calling netxlite.WrapTransport in NewHTTP3Transport;
4. Recognize that the table based constructor inside of
netx needs a logger to create HTTPTransport instances using
either netxlite.NewHTTP{,3}Transport so pass this argument
along and ensure it's not nil using a constructor inside
model that guarantees that;
5. Cleanup netx's tests to avoid type asserting on the …
=> fix(netx): ensure we create ~same HTTP3 and HTTP2 transports

internal/cmd/oohelperd/internal/webconnectivity/webconnectivity_test.go, internal/netxlite/dialer.go, internal/netxlite/dialer_test.go, internal/netxlite/legacy.go, internal/netxlite/resolvercore_test.go
Part of https://github.com/ooni/probe/issues/2121
=> cleanup(netxlite): drop the DefaultDialer legacy name

internal/bytecounter/conn.go, internal/bytecounter/conn_test.go, internal/bytecounter/context.go, internal/bytecounter/counter_test.go, internal/bytecounter/dialer.go, internal/bytecounter/dialer_test.go, internal/bytecounter/http.go, internal/bytecounter/http_test.go, internal/engine/experiment.go, internal/engine/experiment/ndt7/dial.go, internal/engine/netx/cacheresolver.go, internal/engine/netx/cacheresolver_test.go, internal/engine/netx/netx.go, internal/engine/netx/netx_test.go, internal/engine/session.go, internal/netxlite/bogon.go, internal/netxlite/bogon_test.go, internal/ptx/ptx.go, internal/tracex/http.go, internal/tracex/http_test.go
For testability, replace most if-based construction logic with
calls to well-tested factories living in other packages.
While there, acknowledge that a bunch of types could now be private
and make them private, modifying the code to call the public
factories allowing to construct said types instead.
Part of https://github.com/ooni/probe/issues/2121
=> refactor(netx): move construction logic outside package

internal/engine/netx/netx.go, internal/netxlite/bogon.go, internal/netxlite/bogon_test.go, internal/netxlite/resolvercache.go, internal/netxlite/resolvercache_test.go
Now that we have properly refactored the caching resolvers we can
move them into netxlite as optional resolvers created using the
proper abstract factories we just added.
This diff reduces the complexity and the code size of netx.
See https://github.com/ooni/probe/issues/2121.
=> cleanup: move caching resolvers from netx to netxlite

internal/engine/inputloader.go
This diff forward ports 261d1a4cdc88522f6a8f63d6c540f51054566b28 to master.
It's not working for me from a couple of places and also it does not
seem to be documented upstream, see:
https://docs.namebase.io/guides-1/resolving-handshake-1/hdns.io
This diff WILL need to be forwardported to master.
=> [forwardport] fix(dnscheck): remove apparently-broken static input

internal/engine/experiment/stunreachability/stunreachability.go, internal/engine/experiment/stunreachability/stunreachability_test.go
This diff forward ports 4fb5f7de69b900cfc2bd211f723108a67bda350d to master.
See https://github.com/ooni/probe/issues/2058#issuecomment-1145847069
This diff WILL need to be forwardported to master.
=> [forwardport] fix(stunreachability): don't emit spurious progress events

internal/cmd/oohelper/internal/client.go, internal/cmd/oohelper/oohelper.go, internal/netxlite/http.go
The oohelper does not need to use netx and it's enough to use
netxlite, hence let us apply this refactor.
The original code used DoT but the explanatory comment said we were
using DoT because of unclear issues inside GitHub actions.
We are now using DoH and this is fine as well. The comment implied
that any encrypted transport would do.
See https://github.com/ooni/probe/issues/2121
=> refactor(oohelper): use netxlite rather than netx

internal/engine/internal/sessionresolver/childresolver.go, internal/engine/internal/sessionresolver/childresolver_test.go, internal/engine/internal/sessionresolver/clientmaker.go, internal/engine/internal/sessionresolver/clientmaker_test.go, internal/engine/internal/sessionresolver/resolvermaker.go, internal/engine/internal/sessionresolver/resolvermaker_test.go, internal/engine/internal/sessionresolver/sessionresolver.go, internal/engine/internal/sessionresolver/sessionresolver_test.go
This diff addresses the following points of https://github.com/ooni/probe/issues/2135:
Subsequent diffs will address more points mentioned in there.
=> refactor: start refactoring session resolver

internal/cmd/oohelper/oohelper.go, internal/cmd/oohelperd/oohelperd.go, internal/engine/geolocate/iplookup.go
We can simplify code in a bunch of places using a useful factory.
Part of https://github.com/ooni/probe/issues/2121.
=> cleanup: use NewHTTPTransportWithResolver more often

DESIGN.md, docs/design/README.md, docs/design/dd-001-engine.md, docs/design/dd-001-oonimkall.md, docs/design/dd-002-netx.md, docs/design/dd-003-step-by-step.md, internal/engine/netx/doc.go, internal/netxlite/doc.go, pkg/oonimkall/doc.go
This pull request publishes the step-by-step design document that I have been discussing with @hellais and @DecFox recently. Compared to the document that was approved, this one has been edited for readability.
While there, I figured it was also be beneficial to publish the few ooni/probe-cli related design documents we produced in the past, because they probably help someone to get acquainted with the codebase.
=> doc: publish the step-by-step design document

.github/workflows/alltests.yml, .github/workflows/android.yml, .github/workflows/coverage.yml, .github/workflows/generate.yml, .github/workflows/gosec.yml, .github/workflows/ios.yml, .github/workflows/jafar.yml, .github/workflows/macos.yml, .github/workflows/miniooni.yml, .github/workflows/netxlite.yml, .github/workflows/oohelperd.yml, .github/workflows/qafbmessenger.yml, .github/workflows/qahhfm.yml, .github/workflows/qahirl.yml, .github/workflows/qatelegram.yml, .github/workflows/qawebconnectivity.yml, .github/workflows/qawhatsapp.yml, .github/workflows/tarball.yml, .github/workflows/windows.yml, Readme.md, mk
This diff changes all github actions and mk to use go1.18.3.
That's what I am using locally.
Also, both oohttp and oocrypto are on go1.18.3 already.
=> chore: use go1.18.3

pkg/oonimkall/taskrunner.go, pkg/oonimkall/taskrunner_test.go
This bug is one of these bugs that definitely help one to stay
humble and focused on improving the codebase.
Of course I `<facepalmed>` when I understood the root cause.
We did not move the annotations below the `if` which is checking
whether the measurement was successful when we refactored the
codebase to support returning multiple measurements per run, which
happened in https://github.com/ooni/probe-cli/pull/527.
While I am not going to whip myself too much because of this, it's
clearly a bummer that we didn't notice this bug back then. On top
of this, it's also quite sad it took us so much time to notice that
there was this bug inside the tree.
The lesson (hopefully) learned is probably that we need to be more
careful when we refactor and we should always ask the question of
whether, …
=> fix(oonimkall): only set annotations on success

.github/workflows/alltests.yml, .github/workflows/android.yml, .github/workflows/checks.yml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yml, .github/workflows/debianrepo.yml, .github/workflows/generate.yml, .github/workflows/ios.yml, .github/workflows/jafar.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/miniooni.yml, .github/workflows/netxlite.yml, .github/workflows/oohelperd.yml, .github/workflows/qafbmessenger.yml, .github/workflows/qahhfm.yml, .github/workflows/qahirl.yml, .github/workflows/qatelegram.yml, .github/workflows/qawebconnectivity.yml, .github/workflows/qawhatsapp.yml, .github/workflows/tarball.yml, .github/workflows/windows.yml
This diff backports 937f6e29043dbdab65fe663963e209afa66bddac from
the `master` branch. Original commit message follows:
- - -
I am not 100% sure I was able to fix all the cases in which we
need higher permissions than the strict default.
At least, I tried.
It may be reasonable to make an interim release to check whether I
successfully fixed all the cases.
Ref issue: https://github.com/ooni/probe/issues/2154
- - -
Conflicts:
.github/workflows/android.yml
.github/workflows/gosec.yml
.github/workflows/netxlite.yml
=> [backport] fix(workflows): elevate GITHUB_TOKEN permissions when needed

.github/workflows/alltests.yml, .github/workflows/android.yml, .github/workflows/checks.yml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yml, .github/workflows/debianrepo.yml, .github/workflows/generate.yml, .github/workflows/gosec.yml, .github/workflows/ios.yml, .github/workflows/jafar.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/miniooni.yml, .github/workflows/netxlite.yml, .github/workflows/oohelperd.yml, .github/workflows/qafbmessenger.yml, .github/workflows/qahhfm.yml, .github/workflows/qahirl.yml, .github/workflows/qatelegram.yml, .github/workflows/qawebconnectivity.yml, .github/workflows/qawhatsapp.yml, .github/workflows/tarball.yml, .github/workflows/windows.yml
I am not 100% sure I was able to fix all the cases in which we
need higher permissions than the strict default.
At least, I tried.
It may be reasonable to make an interim release to check whether I
successfully fixed all the cases.
Ref issue: https://github.com/ooni/probe/issues/2154
=> fix(workflows): elevate GITHUB_TOKEN permissions when needed

internal/cmd/oohelperd/internal/webconnectivity/dns.go, internal/cmd/oohelperd/internal/webconnectivity/dns_test.go, internal/cmd/oohelperd/internal/webconnectivity/http.go, internal/cmd/oohelperd/internal/webconnectivity/http_test.go, internal/cmd/oohelperd/internal/webconnectivity/measure.go, internal/cmd/oohelperd/internal/webconnectivity/tcpconnect.go, internal/cmd/oohelperd/internal/webconnectivity/webconnectivity.go, internal/cmd/oohelperd/internal/webconnectivity/webconnectivity_test.go, internal/cmd/oohelperd/oohelperd.go
This diff modifies the implementation of oohelperd in the master branch
to always use throw-away HTTPClient, Dialer, and Resolver.
The rationale of this change is to ensure we're not hitting limits of the
HTTPClient regarding the max number of connections per host.
This issue is described at https://github.com/ooni/probe/issues/2182.
While there, it feels more correct to use throw-away Dialer and Resolver.
We have a different patch for the release/3.15 branch because of
netx-related refactorings: https://github.com/ooni/probe-cli/pull/832.
=> fix(oohelperd): use throw-away HTTPClient, Dialer, Resolver

internal/engine/mockable/mockable.go, internal/engine/probeservices/probeservices.go, internal/engine/session.go, internal/engine/session_integration_test.go, internal/model/experiment.go
This diff makes the implementation of the engine package more
abstract by changing HTTPClient() to return a model.HTTPClient
as opposed to returning an *http.Client.
Part of https://github.com/ooni/probe/issues/2184
=> refactor(engine): *http.Client -> model.HTTPClient

internal/cmd/miniooni/libminiooni.go, internal/engine/experiment_integration_test.go, internal/engine/experimentbuilder.go, internal/engine/experimentbuilder_test.go
This diff refactors how we set options for experiments to accept
in input an any value or a map[string]any, depending on which method
we choose to actually set options.
There should be no functional change, except that now we're not
guessing the type and then attempting to set the value of the selected
field: now, instead, we match the provided type and the field's type
as part of the same function (i.e., SetOptionAny).
This diff is functional to https://github.com/ooni/probe/issues/2184,
because it will allow us to load options from a map[string]any,
which will be part of the OONI Run v2 JSON descriptor.
If we didn't apply this change, we would only have been to set options
from a map[string]string, which is good enough as a solution for the
CLI but is definitely clumsy when you have to …
=> refactor(engine): set options from any value

internal/measurexlite/tls_test.go
Bug reported by @DecFox and subsequently observed in several
CI builds. No need to create an issue.
=> measurexlite: fix flaky tls_test.go

internal/cmd/miniooni/libminiooni.go
This option has been disabled for a long time and we said in the
codebase we were going to remove it after 2021-11-01.
So, it feels okay to remove it.
This diff is a cleanup in preparation for https://github.com/ooni/probe/issues/2184.
=> cleanup(miniooni): remove --limit option

internal/engine/session.go, internal/model/experiment.go
This diff contains a fix that I come up with while working
on https://github.com/ooni/probe/issues/2184.
The integration test that was broken was:
```
--- FAIL: TestCreateInvalidExperiment (0.35s)
experiment_integration_test.go:192: expected a nil builder here
```
While there improve the documentation of the ExperimentSession
and acknowledge it contained a method that we are not using, so we
can safely remove such a method from ExperimentSession.
=> fix(engine): repair broken integration test

internal/cmd/miniooni/libminiooni.go, internal/oonirun/link.go, internal/oonirun/v1.go, internal/oonirun/v1_test.go
This diff adds support for running OONIRun v1 links.
Run with `miniooni` using:
```
./miniooni -i LINK oonirun
```
Part of https://github.com/ooni/probe/issues/2184
=> feat(oonirun): implement OONIRun v1

internal/netxlite/resolvercore.go, internal/netxlite/resolvercore_test.go, internal/netxlite/resolverparallel_test.go
This introduces context-based tracing to the system resolver in netxlite
=> feat: collect system resolver results using context

internal/engine/experiment/dnsping/dnsping.go, internal/measurexlite/dns.go, internal/measurexlite/dns_test.go, internal/measurexlite/trace.go, internal/measurexlite/trace_test.go
- This diff replaces the `DNSLookup` buffer to use a simple buffered channel instead of a query-based map
- It also replaces the anonymous resolver initializing functions to use a simpler, `wrapResolver`
=> feat: refactor dns implementation in measurexlite

internal/measurexlite/dns.go, internal/measurexlite/dns_test.go, internal/measurexlite/trace.go, internal/measurexlite/trace_test.go
This introduces a `NewStdlibResolver` in `measurexlite` allowing us to make use of the system resolver in the step-by-step methodology
=> feat: add support for system resolver in measurexlite

internal/cmd/miniooni/main.go, internal/registry/telegram.go, internal/registry/webconnectivity.go
I made a mistake while adapting code from an experimental branch thus
breaking these two experiments because of interface conversion.
This diff fixes it.
While there, remove the panic trap for miniooni. Because miniooni is
an experimental tool, we want to see the full panic text, which definitely
leads to a more pleasant and effective debugging experience.
See https://github.com/ooni/probe/issues/2216 for context on why we
were trying to change how we register experiments.
The broken commit is https://github.com/ooni/probe-cli/commit/6a0ae5c70b68a72206ff7ffb530c758661545cc4.
=> fix(registry): ensure we can run telegram and webconnectivity

.github/workflows/android.yml, .github/workflows/ios.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/miniooni.yml, .github/workflows/windows.yml, Makefile, Readme.md
While there, document what we need to document without mentioning too
many details about release builds, for which we have the Makefile.
See https://github.com/ooni/probe/issues/2218.
=> cleanup: chmod -x mk && mv mk Makefile

internal/oonirun/experiment.go, internal/oonirun/experiment_test.go, internal/oonirun/v2.go
Skip options that begin with the `Safe` prefix from appearing in the
serialization of a Measurement that will be submitted to the OONI
backend.
=> feat: avoid safe options to be serialized into the measurement

Makefile
It turns out the problem described in https://github.com/ooni/probe/issues/2122
only affects darwin/arm64, so we should be good to re-enable Android.
=> fix(Makefile): re-enable Android builds

MOBILE/android/ensure, MOBILE/android/home, MOBILE/android/setup, Makefile
This diff contains minor changes to make the build scripts in here
compatible with https://github.com/bassosimone/monorepo.
See https://github.com/bassosimone/monorepo/commit/5e4c7973801dbd1a582cd21d5000e09a2ee630a7
=> fix(MOBILE/android): make scripts monorepo compatible

internal/engine/experiment/simplequicping/simplequicping.go, internal/engine/experiment/tcpping/tcpping.go, internal/engine/experiment/tlsping/tlsping.go, internal/measurexlite/conn.go, internal/measurexlite/conn_test.go, internal/measurexlite/dialer.go, internal/measurexlite/dialer_test.go, internal/measurexlite/dns.go, internal/measurexlite/dns_test.go, internal/measurexlite/quic.go, internal/measurexlite/quic_test.go, internal/measurexlite/tls.go, internal/measurexlite/tls_test.go, internal/measurexlite/trace.go, internal/measurexlite/trace_test.go
This diff ensures that we only use the safe accessor functions to drain trace channels.
=> refactor(measurexlite): make buffered channels private

internal/engine/experiment/simplequicping/simplequicping.go, internal/engine/experiment/tlsping/tlsping.go, internal/measurexlite/conn.go, internal/measurexlite/conn_test.go, internal/measurexlite/quic.go, internal/measurexlite/quic_test.go, internal/model/mocks/trace.go, internal/model/mocks/trace_test.go, internal/model/netx.go, internal/netxlite/dialer.go, internal/netxlite/quic.go, internal/netxlite/trace.go
This diff exposes the `MaybeWrapNetConn` and `MaybeWrapUDPLikeConn` functions in the `model.Trace` interface allowing us to return a trace wrapped conn in `netxlite`. This allows us to record conn-based I/O events automatically. (without the need to wrap explicitly)
=> refactor: allow automatically wrap net/quic conn

.github/workflows/alltests.yml, .github/workflows/android.yml, .github/workflows/generate.yml, .github/workflows/go1.19.yml, .github/workflows/gosec.yml, .github/workflows/ios.yml, .github/workflows/jafar.yml, .github/workflows/macos.yml, .github/workflows/miniooni.yml, .github/workflows/oohelperd.yml, .github/workflows/qafbmessenger.yml, .github/workflows/qahhfm.yml, .github/workflows/qahirl.yml, .github/workflows/qatelegram.yml, .github/workflows/qawebconnectivity.yml, .github/workflows/qawhatsapp.yml, .github/workflows/tarball.yml, .github/workflows/windows.yml, Readme.md, internal/engine/experiment/urlgetter/getter_integration_test.go, internal/tunnel/config.go, internal/tunnel/psiphon.go, internal/tunnel/psiphon_go119.go, internal/tunnel/psiphon_integration_test.go, internal/tunnel/psiphon_test.go, internal/tunnel/tunnel_test.go
Part of https://github.com/ooni/probe/issues/2211.
See also https://github.com/ooni/probe/issues/2222, which
describes the issue we have with psiphon and go1.19.
=> fix: disable psiphon when building with go1.19

internal/model/mocks/dnsresponse.go, internal/model/mocks/dnsresponse_test.go, internal/model/netx.go, internal/netxlite/dnsdecoder.go, internal/netxlite/dnsdecoder_test.go, internal/netxlite/dnsovergetaddrinfo.go, internal/netxlite/dnsovergetaddrinfo_test.go, internal/netxlite/dnsoverudp.go, internal/netxlite/dnsoverudp_test.go, internal/netxlite/utls_test.go
Closes https://github.com/ooni/probe/issues/2225
=> feat(netxlite): support extracting the CNAME

internal/measurexlite/dns.go, internal/measurexlite/dns_test.go
When a DNSResponse contains a non-empty CNAME, we include it
into the related list of answers.
Closes https://github.com/ooni/probe/issues/2227
=> feat: save CNAME into archival data format

internal/measurexlite/conn.go, internal/measurexlite/conn_test.go, internal/measurexlite/dialer.go, internal/measurexlite/dns.go, internal/measurexlite/quic_test.go, internal/measurexlite/tls.go, internal/measurexlite/tls_test.go, internal/model/archival.go
The T0 field is the moment when we started collecting data, while T
is the moment when we finished collecting data.
The TransactionID field will be repurposed for step-by-step measurements
to indicate related observations collected as part of the same flow
(e.g., TCP+TLS+HTTP).
Note that, for now, this change will only affect measurexlite and we're
not planning on changing other libraries for measuring.
Part of https://github.com/ooni/probe/issues/2137
=> feat(measurexlite): add T0 and TransactionID

internal/measurexlite/http.go, internal/measurexlite/http_test.go, internal/model/archival.go
In a pure step-by-step model, we don't need to trace HTTP round trips like we did before. We _may_ want in the future to also have some form of HTTP tracing (see https://github.com/ooni/probe-cli/pull/868 for a prototype) but doing that is currently not in scope for moving forward the step-by-step design. For this reason, I only added a public convenience function for formatting an OONI spec compatible request. I also added new fields, which should be documented inside the ooni/spec repository (see https://github.com/ooni/probe/issues/2238).
Required by https://github.com/ooni/probe/issues/2237
=> feat(measurexlite): generate HTTP traces

internal/engine/experiment_integration_test.go, internal/experiment/webconnectivity/measurer.go, internal/measurex/dnsx.go, internal/measurex/dnsx_test.go, internal/measurex/resolver.go, internal/measurex/resolver_test.go, internal/measurexlite/dns_test.go, internal/netxlite/dnsovergetaddrinfo.go, internal/netxlite/doc.go, internal/netxlite/getaddrinfo.go, internal/netxlite/getaddrinfo_cgo.go, internal/netxlite/getaddrinfo_otherwise.go, internal/netxlite/resolvercore.go, internal/netxlite/resolvercore_test.go, internal/tracex/resolver.go, internal/tracex/resolver_test.go, internal/tutorial/netxlite/README.md, internal/tutorial/netxlite/chapter05/README.md, internal/tutorial/netxlite/chapter05/main.go
See what we documented at https://github.com/ooni/spec/pull/257
Reference issue: https://github.com/ooni/probe/issues/2238
See also the related ooni/spec PR: https://github.com/ooni/spec/pull/257
See also https://github.com/ooni/probe/issues/2237
While there, bump webconnectivity@v0.5 version because this change
has an impact onto the generated data format.
The drop in coverage is unavoidable because we've written some
tests for `measurex` to ensure we deal with DNS resolvers and transport
names correctly depending on the splitting policy we use.
(However, `measurex` is only used for the `tor` experiment and, per
the step-by-step design document, new experiments should use
`measurexlite` instead, so this is hopefully fine(TM).)
While there, fix a broken integration test that does not run …
=> feat: clearly indicate which resolver we're using

internal/cmd/oohelperd/main.go
Part of https://github.com/ooni/probe/issues/2183
=> fix(oohelperd): by default listen on localhost

internal/cmd/oohelperd/dns.go, internal/cmd/oohelperd/http.go, internal/cmd/oohelperd/tcpconnect.go
While working on https://github.com/ooni/probe/issues/2237, I noticed
there's no enforced timeout for measurement tasks.
So, this diff introduces the following timeouts:
1. use a 4 seconds timeout for the DNS lookup;
2. use a 10 seconds timeout for TCP;
3. use a 15 seconds timeout for HTTP.
They are a bit stricter than what we have on the probe because the TH
should supposedly have better bandwidth and connectivity.
=> fix(oohelperd): enforce timeout for each measurement step

internal/cmd/oohelperd/measure.go
This diff refactors oohelperd to make performing additional measurements easier. We need:
1. to run the DNS task _before_ other tasks such that we can measure both IP addresses returned by the TH and the ones returned by the probe. When we'll introduce TLS measurements, this will allow us to validate probe-provided IP addresses inside the TH call. If probe-provided addresses work with TLS, they are legitimate for the domain.
2. to tie the number of TCP measurements to a list of endpoints collected by the probe _or_ the TH rather than just to the one provided by the probe. Anticipating this change, let us refactor how we read the results of the TCP task to make it independent of the number of addresses provided by the probe.
This work is part of https://github.com/ooni/probe/issues/2237
=> refactor(oohelperd): make performing additional measurements easier

internal/cmd/oohelper/internal/client.go, internal/cmd/oohelperd/dns.go, internal/cmd/oohelperd/dns_test.go, internal/cmd/oohelperd/http.go, internal/cmd/oohelperd/ipinfo.go, internal/cmd/oohelperd/ipinfo_test.go, internal/cmd/oohelperd/measure.go, internal/cmd/oohelperd/tcpconnect.go, internal/engine/experiment/webconnectivity/control.go, internal/engine/experiment/webconnectivity/control_test.go, internal/engine/experiment/webconnectivity/dnsanalysis.go, internal/model/th.go
This commit moves the TH structs and definitions to model. We don't want
oohelperd to depend on web_connectivity@v0.4.
Part of https://github.com/ooni/probe/issues/2240
=> refactor: move TH structs and definitions to model

internal/cmd/oohelperd/dns.go, internal/cmd/oohelperd/dns_test.go, internal/cmd/oohelperd/handler.go, internal/cmd/oohelperd/handler_test.go, internal/cmd/oohelperd/http.go, internal/cmd/oohelperd/http_test.go, internal/cmd/oohelperd/logging.go, internal/cmd/oohelperd/logging_test.go, internal/cmd/oohelperd/main.go, internal/cmd/oohelperd/measure.go, internal/cmd/oohelperd/tcpconnect.go
We're using a request-specific logger where we also print the ID
of the request. This design helps to observe logs produced by
concurrent requests.
Part of https://github.com/ooni/probe/issues/2183
While there, fix https://github.com/ooni/probe/issues/2241
=> feat(oohelperd): log messages at info level

go.mod, go.sum, internal/cmd/oohelperd/handler.go, internal/cmd/oohelperd/main.go, internal/cmd/oohelperd/metrics.go, internal/measurexlite/logger_test.go, internal/model/th.go
Closes https://github.com/ooni/probe/issues/2183
While there, avoid exposing nil values for optional fields of the
THResponse struct (i.e., "ip_info" and "tls_handshake").
While there, fix `measurexlite`'s `OperationLogger` test
and make it deterministic rather than racy.
=> feat(oohelperd): add prometheus metrics

.github/workflows/miniooni.yml, CLI/check-mingw-w64-version, CLI/go-build-cross, CLI/go-build-windows
It seems several CI builds failed for [v3.16.0-alpha](https://github.com/ooni/probe-cli/releases/tag/v3.16.0-alpha). Let's aim to repair miniooni and ooniprobe-windows for now. The other failing builds seem more tricky. (Android fails with an unsupported NDK while Linux fails with issues accessing the git repository from Docker, probably because the  the user running inside Docker is not the user that owns the repository.)
=> fix: repair releasing miniooni and ooniprobe-windows

CLI/go-build-alpine
The issue here is that the repository is owned by the user who
runs the command and the container runs as root.
Part of https://github.com/ooni/probe/issues/2130
=> fix: repair broken linux-static build

.github/workflows/alltests.yml, .github/workflows/android.yml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yml, .github/workflows/debianrepo.yml, .github/workflows/generate.yml, .github/workflows/go1.19.yml, .github/workflows/gosec.yml, .github/workflows/ios.yml, .github/workflows/jafar.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/miniooni.yml, .github/workflows/netxlite.yml, .github/workflows/oohelperd.yml, .github/workflows/qafbmessenger.yml, .github/workflows/qahhfm.yml, .github/workflows/qahirl.yml, .github/workflows/qatelegram.yml, .github/workflows/qawebconnectivity.yml, .github/workflows/qawhatsapp.yml, .github/workflows/tarball.yml, .github/workflows/windows.yml, Makefile
Part of https://github.com/ooni/probe/issues/1753.
While there, introduce a rule by which, if the branch is named `fullbuild` we run all possible builds. It helps to test all the builds without creating a release branch. Because release branches are protected, they cannot be deleted easily. On the contrary, the `fullbuild` branch can easily be disposed of.
=> feat: build ooniprobe for armv6

internal/cmd/oohelperd/handler.go, internal/cmd/oohelperd/metrics.go
Make sure we don't say measurement in metrics.
See https://github.com/ooni/probe/issues/2183#issuecomment-1230327725
=> fix(oohelperd): measurement -> wctask

.github/workflows/android.yml, Makefile
After https://github.com/ooni/probe-cli/pull/908, the Android
build has become super slow, because we build serially.
Attempt to make it faster by building in parallel.
Still part of https://github.com/ooni/probe/issues/2119, because
I don't feel happy with a super slow build.
=> fix: attempt to make android builds faster

.github/workflows/alltests.yml, .github/workflows/android.yml, .github/workflows/generate.yml, .github/workflows/gosec.yml, .github/workflows/ios.yml, .github/workflows/jafar.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/oohelperd.yml, .github/workflows/qafbmessenger.yml, .github/workflows/qahhfm.yml, .github/workflows/qahirl.yml, .github/workflows/qatelegram.yml, .github/workflows/qawebconnectivity.yml, .github/workflows/qawhatsapp.yml, .github/workflows/tarball.yml, .github/workflows/windows.yml, script/ghpublish.bash, script/maketarball.bash
This diff modifies all the github actions that produce assets to
publish on a release called rolling when we are not building a tag.
If everything goes as planned, we should be able to provide
people with automatically generated fresh binaries for testing.
While there, introduce caching for all builds to make them
as fast as possible. I suspect gomobile based builds will not
see any speed up but other builds most likely will.
See https://github.com/ooni/probe/issues/2249
=> feat: implement rolling builds

internal/cmd/miniooni/consent.go, internal/cmd/miniooni/main.go
Most of miniooni panics on errors. We should not panic on error with
--repeat-every, rather we should try the next measurement.
See https://github.com/ooni/probe/issues/2250
=> fix(miniooni): handle panics with --repeat-every

internal/engine/experiment/dnscheck/dnscheck.go, internal/engine/experiment/dnscheck/dnscheck_test.go
I just changed the timeouts in https://github.com/ooni/probe/issues/2234, so I should also bump patch
=> dnscheck: bump patch version number

internal/engine/experiment/dnscheck/dnscheck.go, internal/engine/experiment/dnscheck/dnscheck_test.go
The residual censorship algorithm prevents dnscheck for checking the
same endpoint again in a short time frame under the assumption that a
previous measurement could have caused residual censorship.
In https://github.com/ooni/probe/issues/2234, we mentioned we probably
wanted to disable this algorithm because we didn't want to slow down
dnscheck too much and because we didn't detect this alleged source of
blocking in our previous measurements.
It turns out the algorithm was already disabled. I probably did this
after we published the paper on DNS censorship to make measurements
overall a bit faster.
So, just introduce a new extension field to the measurement telling us
that the residual censorship algorithm is disabled.
It's not super useful except as for the fact that the next time I …
=> fix(dnscheck): record whether residual is enabled

E2E/miniooni.bash, QA/webconnectivity.py, internal/cmd/apitool/main.go, internal/cmd/jafar/httpproxy/httpproxy_test.go, internal/cmd/jafar/tlsproxy/tlsproxy_test.go, internal/cmd/oohelper/internal/client_test.go, internal/cmd/oohelper/oohelper.go, internal/cmd/oohelperd/dns_test.go, internal/engine/probeservices/benchselect.go, internal/engine/probeservices/probeservices_test.go, internal/engine/sessionresolver/resolver_test.go, internal/netxlite/integration_test.go
See https://github.com/ooni/probe/issues/2147.
Note that this PR also tries to reduce usage of legacy names inside unit/integration tests.
=> fix(probeservices): use api.ooni.io

internal/experiment/webconnectivity/analysiscore.go, internal/experiment/webconnectivity/analysishttpcore.go, internal/experiment/webconnectivity/analysistcpip.go, internal/experiment/webconnectivity/analysistls.go, internal/experiment/webconnectivity/control.go, internal/experiment/webconnectivity/measurer.go, internal/experiment/webconnectivity/testkeys.go
This diff modifies webconnectivity@v0.5 to take decisions regarding
TLS blocking by using the response from the TH rather than using
questionable heuristics based on inspecting the TLSHandshake list
alone. This change should improve correctness _when_ we're using
the improved TH, which is currently used for 50% of the probes.
See https://github.com/ooni/probe/issues/2257
While there, modify `control.go` to specify which control is being used.
=> feat(webconnectivity@v0.5): use TLS info from TH 

internal/experiment/webconnectivity/control.go, internal/experiment/webconnectivity/dnscache.go, internal/experiment/webconnectivity/dnsresolvers.go, internal/experiment/webconnectivity/measurer.go, internal/logx/logx.go, internal/logx/logx_test.go
While there, change the emoji logger to emit whitespace on info logs. This makes warnings stand out even more.
Closes https://github.com/ooni/probe/issues/2258
=> fix(webconnectivity@v0.5): fetch HTTP only using system-resolver addrs

go.mod, go.sum
This is the last dependency we needed to update according to
the https://github.com/ooni/probe/issues/2130 checklist.
=> chore: update to ooni/go-libtor v1.1.6

internal/version/version.go
I've just branched off the `release/3.16` branch since we're really looking good for release modulo minor changes.
Hence, it's time to update `master`'s version.
=> chore: set version to 3.17.0-alpha

internal/experiment/webconnectivity/cleartextflow.go, internal/experiment/webconnectivity/secureflow.go, internal/experiment/webconnectivity/testkeys.go
Code based on urlgetter had this event and we would like to have this event with step-by-step code as well.
Because there's no tracing for HTTP when using step-by-step, we will need to include emitting these events inside the boilerplate.
By doing that, we emit events out of order, so make sure we sort them by T, which is "the moment when the event was collected".
Part of https://github.com/ooni/probe/issues/2238
=> fix(webconnectivity@v0.5): include http transaction start/done

internal/engine/netx/http.go, internal/measurex/endpoint.go, internal/measurex/measurement.go, internal/measurex/measurer.go, internal/measurex/quic.go, internal/measurex/utils.go, internal/measurexlite/http.go, internal/measurexlite/http_test.go, internal/measurexlite/quic.go, internal/measurexlite/quic_test.go, internal/model/mocks/http_test.go, internal/model/netx.go, internal/netxlite/http3.go, internal/netxlite/http3_test.go, internal/tracex/archival_test.go, internal/tutorial/measurex/chapter05/README.md, internal/tutorial/measurex/chapter05/main.go, internal/tutorial/measurex/chapter06/README.md, internal/tutorial/measurex/chapter06/main.go, internal/tutorial/measurex/chapter08/README.md, internal/tutorial/measurex/chapter08/main.go
This diff changes the data format to prefer "udp" to "quic" everywhere we were previously using "quic".
Previously, the code inconsistently used "quic" for operations where we knew we were using "quic" and "udp" otherwise (e.g., for generic operations like ReadFrom).
While it would be more correct to say that a specific HTTP request used "quic" rather than "udp", using "udp" consistently allows one to see how distinct events such as ReadFrom and an handshake all refer to the same address, port, and protocol triple. Therefore, this change makes it easier to programmatically unpack a single measurement and create endpoint stats.
Before implementing this change, I discussed the problem with @hellais who mentioned that ooni/data is not currently using the "quic" string anywhere. I know that …
=> refactor(datafmt): use "udp" instead of "quic"

internal/experiment/webconnectivity/analysisdns.go, internal/experiment/webconnectivity/measurer.go
See: https://github.com/ooni/probe/issues/2274
=> fix(webconnectivity@v0.5): DoH failure shouldn't set flags

internal/experiment/webconnectivity/analysishttpdiff.go, internal/experiment/webconnectivity/measurer.go
See https://github.com/ooni/probe/issues/2287
=> fix(webconnectivity@v0.5): status code always match with equal codes

internal/experiment/webconnectivity/analysisdns.go, internal/experiment/webconnectivity/measurer.go
See https://github.com/ooni/probe/issues/2284
=> fix(webconnectivity@v0.5): account for broken ipv6 in dnsdiff algorithm

internal/experiment/webconnectivity/analysiscore.go, internal/experiment/webconnectivity/dnsresolvers.go, internal/experiment/webconnectivity/measurer.go, internal/experiment/webconnectivity/priority.go, internal/experiment/webconnectivity/testkeys.go
See https://github.com/ooni/probe/issues/2290
While there, notice that in such a case the priority selector would hang because of the WaitGroup, so get rid of the WaitGroup and accept that the priority selector is going to hang around for the whole duration of the measurement in some cases. The cancellable `measurer.go`'s context will cause the priority selector to eventually exit when we return from `measurer.go`'s `Run` method.
=> feat(webconnectivity@v0.5): flag case where noone resolved any address

internal/experiment/webconnectivity/control.go
It's confusing to see
```
measuring additional addrs from TH: []
```
when actually nothing is going to be measured.
So, instead, let us log about the additional addrs discovered by the TH instead, which is less confusing.
Part of https://github.com/ooni/probe/issues/2237
=> fix(webconnectivity@v0.5): avoid confusing log message

internal/experiment/webconnectivity/analysiscore.go, internal/experiment/webconnectivity/measurer.go, internal/experiment/webconnectivity/testkeys.go
This diff introduces a special rule to avoid emitting null, null when all the connects failed in both the probe and the TH.
While there, recognize that the subset of null, null we're hunting actually deals with websites that are down, so change the internal naming to reflect that and make the code easier to read/understand.
See https://github.com/ooni/probe/issues/2299
=> feat(webconnectivity@v0.5): probe and TH can't connect => website down

.vscode/settings.json, internal/experiment/webconnectivity/analysiscore.go, internal/experiment/webconnectivity/iox.go, internal/experiment/webconnectivity/measurer.go, internal/experiment/webconnectivity/testkeys.go
This diff includes a rule to recover from the "measurement failed" state that kicks in when we have a chain of successful redirects from the client side leading to a webpage _and_ any URL in the chain uses HTTPS. See https://github.com/ooni/probe/issues/2307.
While there, fix `i/e/w/iox.go` to avoid triggering the `./script/nocopyreadall.bash` script.
=> webconnectivity@v0.5: handle successful https chains

internal/netxlite/dnsdecoder.go, internal/netxlite/dnsdecoder_test.go
The simplest fix is to wrap such errors in dnsdecoder.go.
Fixes https://github.com/ooni/probe/issues/2317.
=> fix(nextlite): wrap DNSDecoder errors

internal/experiment/webconnectivity/analysiscore.go, internal/experiment/webconnectivity/analysisdns.go, internal/experiment/webconnectivity/analysishttpcore.go, internal/experiment/webconnectivity/analysishttpdiff.go, internal/experiment/webconnectivity/analysistcpip.go, internal/experiment/webconnectivity/analysistls.go, internal/experiment/webconnectivity/dnsresolvers.go, internal/experiment/webconnectivity/measurer.go, internal/experiment/webconnectivity/testkeys.go
We're bumping the experiment's version number because we changed the name of the field used to contain late/duplicate DNS responses. We have also changed the algorithm to determine `#dnsDiff`. However, the change should only impact how we log this information. Overall, here the idea is to provide users with a reasonably clear explanation of how the probe maps observations to blocking and accessible using expected/unexpected as the conceptual framework.
Part of https://github.com/ooni/probe/issues/2237
=> refactor(webconnectivity@v0.5): improve logging clarity

internal/cmd/miniooni/main.go, internal/cmd/miniooni/oonirun.go, internal/oonirun/v2.go, internal/oonirun/v2_test.go
We introduce the -f, --input-file FILE option with which we are able to run an OONI Run v2 descriptor stored locally.
In this running mode, there are no checks related to whether the descriptor has changed, since we're dealing with a local file.
Closes https://github.com/ooni/probe/issues/2328
=> feat(miniooni): run local oonirun v2 descriptor

docs/design/dd-002-netx.md
This is minor typo fix in the documentation. 
=> Minor typo fixed in 'ssl_unknown_autority'

.github/workflows/debianrepo.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/windows.yml, CLI/go-build-alpine, E2E/debian.bash, E2E/debian.sh, E2E/miniooni.bash, E2E/ooniprobe.bash, internal/engine/probeservices/checkreportid_test.go, internal/engine/probeservices/measurementmeta_test.go
Closes https://github.com/ooni/probe/issues/2334.
While there, reinstate integration tests, which were also lost in a previous refactoring. However, only run those tests for linux/amd64 because we can be confident that the Go compiler is WAI for all archs we support.
While there, always use bash for running end-to-end tests.
H/T @ainghazal for discovering and reporting this bug.
=> fix(go-build-alpine): honour OONI_PSIPHON_TAGS

internal/cmd/ooporthelper/main.go, internal/cmd/ooporthelper/main_test.go
This diff fixes the `connection_refused` error we face with go1.19 for `ooporthelper`
=> fix: ooporthelper connection_refused

internal/engine/geolocate/cloudflare.go, internal/engine/geolocate/cloudflare_test.go, internal/engine/geolocate/geolocate.go, internal/engine/geolocate/invalid_test.go, internal/engine/geolocate/iplookup.go, internal/engine/geolocate/resolverlookup.go, internal/engine/geolocate/resolverlookup_test.go, internal/engine/geolocate/stun.go, internal/engine/geolocate/stun_test.go, internal/engine/geolocate/ubuntu.go, internal/engine/geolocate/ubuntu_test.go
This change ensures that, in turn, we're able to "remote" all the traffic generated by the `geolocate` package, rather than missing some bits of it that were still using the standard library and caused _some_ geolocations to geolocate as the local host rather than as the remote host.
Extracted from https://github.com/ooni/probe-cli/pull/969, where we tested this functionality.
Closes https://github.com/ooni/probe/issues/1383 (which was long overdue).
Part of https://github.com/ooni/probe/issues/2340, because it allows us to make progress with that.
=> fix(geolocate): always use netxlite functionality

internal/engine/experiment/signal/signal.go, internal/engine/experiment/signal/signal_test.go
All measurements collected since 2022-10-19 with previous versions of OONI Probe will wrongly report sfu.voip.signal.org as blocked as it switched to using a different root CA
This fixes: https://github.com/ooni/probe/issues/2344
=> Add new root CA to the signal test

CLI/go-build-generic, Makefile, cmd/ooniprobe/internal/cli/root/root.go, cmd/ooniprobe/internal/nettests/nettests_test.go, cmd/ooniprobe/internal/ooni/ooni.go, cmd/ooniprobe/internal/ooni/ooni_test.go
This implements the bare minimum needed to have circumvention proxy support in OONI Probe CLI.
The reference issue is https://github.com/ooni/probe/issues/1955. (Most of that issue is implemented, save for the fact that currently we do not have support for `http` and `https` proxies.)
While there, add to `Makefile` a rule for correctly building `ooniprobe` and `miniooni` for "this system" (i.e., the default `GOOS` and `GOARCH` on a system), because we needed this for testing this patch and we needed to figure out the commands instead.
=> cli: add support for passing proxy command line parameter

.github/workflows/qa.yml, QA/webconnectivity.py
Since https://github.com/ooni/probe-cli/pull/980, we fall back if the primary test helper fails. So, we need to update QA tests.
This diff is being forward ported from the release/3.16 branch.
=> [fwdport] fix(QA): reckon with TH fallback policies

internal/cmd/jafar/README.md, internal/cmd/jafar/main.go, internal/cmd/jafar/tlsproxy/tlsproxy.go, internal/cmd/jafar/tlsproxy/tlsproxy_test.go
While developing a SMTP/IMAP probe, it proved useful to use Jafar's evil TLS proxying features. However, outbound port 443 was hardcoded into it. In this PR, i introduce a tls-proxy-outbound-port flag for jafar to control which port requests are proxied to. It defaults to 443 as it did previously for usage as HTTPS mitm.
Example:
<code>jafar -tls-proxy-address "127.0.0.1:465" -tls-proxy-block "smtp" -tls-proxy-outbound-port "465"</code>
This will accept requests on localhost:465 and proxy those to whatever hostname is in the TLS SNI header on port 465... except when SNI contains "smtp" of course.
<details><pre><code>
go test -race ./...
?   	github.com/ooni/probe-cli/v3/GHGEN	[no test files]
?   	github.com/ooni/probe-cli/v3/cmd/ooniprobe	[no test files]
? …
=> feat(jafar): add -tls-proxy-outbound-port flag

internal/runtimex/runtimex.go, internal/runtimex/runtimex_test.go
This diff makes the behavior of the functions exported by runtimex slightly more consistent. Now all of them pass to panic an error type. Before, only PanicOnError passed an error type while other functions passed a string. Yet, having an uniform way of throwing error types is better because we also have a better way of catching errors.
=> runtimex: always pass to panic an error type

internal/engine/mockable/mockable.go, internal/engine/probeservices/bouncer_test.go, internal/engine/probeservices/checkin_test.go, internal/engine/probeservices/checkreportid_test.go, internal/engine/probeservices/collector_test.go, internal/engine/probeservices/login_test.go, internal/engine/probeservices/measurementmeta_test.go, internal/engine/probeservices/metadata_test.go, internal/engine/probeservices/orchestra_test.go, internal/engine/probeservices/probeservices_test.go, internal/engine/probeservices/psiphon_test.go, internal/engine/probeservices/register_test.go, internal/engine/probeservices/statefile_test.go, internal/engine/probeservices/tor_test.go, internal/engine/probeservices/urls_test.go
I was trying to (1) either move data types definitions inside probeservices to internal/model or (2) make them private to reduce the amount of exported definitions. However, I was severely limited in doing that by the fact that probeservices uses external testing.
To overcome this issue, I'm switching to internal testing first and then I will resume with the two points above, which are in line with my goal for today of moving https://github.com/ooni/probe/issues/2372 forward.
=> refactor(probeservices): use internal testing

internal/engine/probeservices/checkreportid.go, internal/engine/probeservices/statefile.go, internal/engine/probeservices/urls.go, internal/model/ooapi.go
This diff ensures that the definitions we're using are in sync with the model used by [v3.14.0's ooapi package](
https://github.com/ooni/probe-cli/tree/v3.14.0/internal/ooapi/apimodel), which was an experiment at autogenerating APIs and cross checking with ooni/api's swagger JSON file.
The only difference that remains pertains the name of the query string parameter for /api/v1/test-list/urls, which must be plural (as it is in the probeservices package) rather than singular (as it is in the ooapi/apimodel package).
So, after merging this diff, we can say we have done part of the work specified by https://github.com/ooni/probe/issues/2372. However, we want to also check with the _current_ swagger.
(Because we already had a model that was consistent with the swagger _at the time we wrote …
=> probeservices: sync up with v3.14.0 ooapi package

internal/engine/experiment/telegram/telegram.go, internal/engine/experiment/telegram/telegram_test.go
While there also stop processing the page that we get back when using https like we do for whatsapp.
Generally, this set of changes is proactive to reduce possible false positives in the future.
See https://github.com/ooni/probe/issues/2382.
=> fix(telegram): stop measuring http://web.telegram.org/

internal/engine/experiment/whatsapp/whatsapp.go, internal/engine/experiment/whatsapp/whatsapp_test.go
Like we did for whatsapp web, we care about doing a TLS handshake and getting an HTTP response but we don't care about the content because it may change and that would cause a false positive.
FWIW, it turns out probe-cli was not compliant with the spec which explicitly said we didn't care about status, so this change is a more proper fix than I imagined when I planned doing it.
Closes https://github.com/ooni/probe/issues/2384
=> fix(whatsapp): allow registration server to HTTP-fail

.github/workflows/go1.19.yml, internal/engine/experiment/webconnectivity/control.go, internal/experiment/webconnectivity/control.go, internal/httpapi/call.go, internal/httpapi/call_test.go, internal/httpapi/descriptor.go, internal/httpapi/descriptor_test.go, internal/httpapi/endpoint.go, internal/httpapi/endpoint_test.go, internal/httpapi/sequence_test.go
This diff changes httpapi Endpoint and Descriptor such that the logger field is part of the Endpoint rather than Descriptor.
This changes makes sense because the logger to use should be the same for every API call. What matters, instead, is whether to log bodies, which remains a property of the API Descriptor.
While I authored this diff originally as part of the work done in https://github.com/ooni/probe-cli/pull/997, it seems it's required in https://github.com/ooni/probe-cli/pull/1002 as well.
Hence, the reference issue is https://github.com/ooni/probe/issues/2379.
=> refactor(httpapi): logger belongs to endpoint

internal/engine/experiment/webconnectivity/control.go, internal/engine/probeservices/checkin.go, internal/experiment/webconnectivity/control.go, internal/httpapi/call.go, internal/httpapi/call_test.go, internal/httpapi/descriptor.go, internal/httpapi/sequence.go, internal/httpapi/sequence_test.go, internal/ooapi/checkin.go, internal/ooapi/checkin_test.go, internal/ooapi/th.go, internal/ooapi/th_test.go
This diff modifies httpapi to annotate the descriptor with the ResponseType, which also allows us to write code where we naturally call an API as follows:
```Go
resp, err := httpapi.Call(ctx, desc, epnt)
```
and where `resp` is of the correct response type and where `desc` has been configured to unmarshal using the JSON format.
In addition to this syntactic-sugar change, this diff matters because knowing the type of the request and of the response allows us to generate a swagger to compare to the server's swagger.
Part of https://github.com/ooni/probe/issues/2372.
=> feat(httpapi): annotate Descriptor with ResponseType

go.mod, go.sum, internal/engine/experiment/echcheck/config.go, internal/engine/experiment/echcheck/config_test.go, internal/engine/experiment/echcheck/doc.go, internal/engine/experiment/echcheck/generate.go, internal/engine/experiment/echcheck/handshake.go, internal/engine/experiment/echcheck/handshake_test.go, internal/engine/experiment/echcheck/measure.go, internal/engine/experiment/echcheck/measure_test.go, internal/engine/experiment/echcheck/utls.go, internal/registry/echcheck.go
Adds a new `echcheck` experiment that tests for interference of TLS handshakes with the Encrypted Client Hello (ECH) extension present.
=> feat: echcheck experiment

internal/netxlite/classify.go, internal/netxlite/classify_test.go
This value is a good initial value to initialize errors when failing early needs to cause an error. If we have a canonical value to represent that, we can reduce code duplication.
See bassosimone/oonidsl@9af837a2e7d23fc71477598c494bbace4e42b97d
=> feat(netxlite): introduce a generic unknown error

internal/engine/experiment.go, internal/engine/session.go, internal/runtimex/runtimex.go, internal/runtimex/runtimex_test.go, internal/version/version.go
We expose build information in the logs, when an engine.Session is being created as well as inside the annotations.
Part of https://github.com/ooni/probe/issues/2273
See https://github.com/ooni/spec/pull/272
=> feat: expose build information

MOBILE/android/template.pom, Readme.md, internal/experiment/README.md, internal/experiment/torsf/torsf.go, internal/experiment/torsf/torsf_test.go, internal/experiment/vanillator/vanillator.go, internal/experiment/vanillator/vanillator_test.go, internal/model/location.go, internal/tutorial/README.md, internal/tutorial/experiment/torsf/chapter01/README.md, pkg/oonimkall/doc.go
This diff includes some cleanups while we finish moving packages away from the internal/engine package.
With this diff, we have finally finished merging probe-engine into probe-cli, a process initiated in February 2021.
See https://github.com/ooni/probe/issues/1335.
Closes https://github.com/ooni/probe/issues/2115.
=> cleanup: finish moving packages away from engine

internal/engine/inputloader.go, internal/engine/inputloader_test.go, internal/engine/session.go, internal/engine/session_internal_test.go, internal/legacy/mockable/mockable.go, internal/model/mocks/session.go, internal/model/mocks/session_test.go, internal/model/ooapi.go, internal/probeservices/checkin.go
Specifically, name it ...ResultNettests such that it's clear by inspection that this structure belongs to the results.
Part of https://github.com/ooni/probe/issues/2396
=> refactor: rename check-in nettests results for clarity

internal/httpapi/call_test.go, internal/httpapi/descriptor.go, internal/ooapi/checkin.go, internal/ooapi/th.go
While working on https://github.com/ooni/probe/issues/2396, I noticed
that the httpapi code could return nil, nil when the input from the
server was the `null` UTF-8 string. In such a case, golang translates
the `null` string into a `nil` pointer. However, if we pass the
pointer to a struct rather than the pointer to a pointer, the code
returns an empty struct, which is much safer.
This reasoning works as long as we assume the caller wants to get
a struct by pointer or nil on error. If the caller for some reason
wants the code to return a `**T` type, we're back in the case where
the code can return `nil`, `nil`. But all our code always wants
a `*T` back and this seems the only case that makes sense.
=> fix(httpapi): don't return nil, nil with null JSON input

internal/experiment/echcheck/utls.go, internal/netxlite/utls.go, internal/netxlite/utls_test.go
This PR exposes the `netxlite.utlsConn` to the experiments by making it public (--> `UTLSConn`) `echcheck` can use `netxlite.UTLSConn` now so we don't need to re-implement utlsConn there any longer.
Note that `NewConnUTLSWithHelloID` returns `*UTLSConn` now, instead of `TLSConn`, to make it more convenient for experiment developers.
=> feat(engine): make netxlite.utlsConn public

CONTRIBUTING.md, internal/cmd/jafar/main.go, internal/shellx/shellx.go, internal/shellx/shellx_test.go, internal/shellx/testdata/checkenv.go
This diff introduces an explicit `shellx` dependency type. There is a also a singleton that by default implements the expected and reasonable behavior. Tests will change this singleton.
See https://github.com/ooni/probe/issues/2399
=> feat: simplify writing tests for code using shellx

CONTRIBUTING.md, internal/shellx/shellx.go, internal/shellx/shellx_test.go, internal/shellx/shellxtesting/shellxtesting.go, internal/shellx/shellxtesting/shellxtesting_test.go
Recent changes in https://github.com/ooni/probe-cli/pull/1042 made `shellx` better in terms of pretending we're running commands in tests. However, the work done there is not enough for https://github.com/ooni/probe/issues/2401. It turns out I also need a mechanism to incrementally construct commands. So, while keeping unchanged the external `shellx` API used by existing packages, let's try to use a better underlying API that meets these new needs.
While there, re-read Go 1.19 release notes and realize that I want to keep using `x/sys/execabs` everywhere. See the informative comment in the diff below explaining why I want to do that.
=> feat(shellx): support incremental command construction

internal/runtimex/runtimex.go, internal/runtimex/runtimex_test.go
These functions are syntactic sugar to wrote runtimex.PanicOnError code more compactly. This change is made possible by generics.
Part of https://github.com/ooni/probe/issues/2401
=> feat(runtimex): add the TryN functions

internal/cmd/buildtool/builddeps.go, internal/cmd/buildtool/cdeps.go, internal/cmd/buildtool/cdepslibevent.go, internal/cmd/buildtool/cdepsopenssl.go, internal/cmd/buildtool/cdepstor.go, internal/cmd/buildtool/cdepszlib.go, internal/cmd/buildtool/internal/buildtoolmodel/buildtoolmodel.go, internal/cmd/buildtool/internal/buildtooltest/buildtooltest.go, internal/cmd/buildtool/internal/buildtooltest/buildtooltest_test.go, internal/cmd/buildtool/linuxcdeps.go, internal/cmd/buildtool/linuxcdeps_test.go
It was a bit of annoying two have two structs to represent build dependencies when just one of them is good enough.
Part of https://github.com/ooni/probe/issues/2401
=> refactor(buildtool): unify C deps with other deps

internal/cmd/buildtool/android.go, internal/cmd/buildtool/cbuildenv.go, internal/cmd/buildtool/cbuildenv_test.go, internal/cmd/buildtool/cdeps.go, internal/cmd/buildtool/cdepslibevent.go, internal/cmd/buildtool/cdepsopenssl.go, internal/cmd/buildtool/cdepstor.go, internal/cmd/buildtool/cdepszlib.go, internal/cmd/buildtool/internal/buildtooltest/buildtooltest.go, internal/cmd/buildtool/linuxcdeps.go, internal/cmd/buildtool/linuxcdeps_test.go
At the end of the day, there's just a unique kind of build env that makes sense for both cdeps and android.
While there, write better code for merging global and local environment and make sure we have unit tests for that.
See https://github.com/ooni/probe/issues/2401
=> refactor(buildtool): merge cdeps and android build envs

internal/cmd/buildtool/android.go, internal/cmd/buildtool/cbuildenv.go, internal/cmd/buildtool/cbuildenv_test.go, internal/cmd/buildtool/cdepslibevent.go, internal/cmd/buildtool/cdepsopenssl.go, internal/cmd/buildtool/cdepstor.go, internal/cmd/buildtool/cdepszlib.go, internal/cmd/buildtool/linuxcdeps.go
I know this is a bit weird in the Go convention but using this naming helps me to read the code in this case.
See https://github.com/ooni/probe/issues/2401
=> refactor(buildtool): use naming reminding of bash variables

internal/cmd/buildtool/android.go, internal/cmd/buildtool/cbuildenv.go, internal/cmd/buildtool/cbuildenv_test.go, internal/cmd/buildtool/cdepslibevent.go, internal/cmd/buildtool/cdepsopenssl.go, internal/cmd/buildtool/cdepstor.go, internal/cmd/buildtool/cdepszlib.go, internal/cmd/buildtool/linuxcdeps.go
This diff continues refactoring how we set environment variables to approximate what we were doing in bash in https://github.com/ooni/probe-cli/pull/1024.
See https://github.com/ooni/probe/issues/2401
=> refactor(buildtool): improve how we set environment variables

go.mod, go.sum, internal/cmd/buildtool/android.go, internal/cmd/buildtool/android_test.go, internal/cmd/buildtool/cdepstor.go, internal/cmd/buildtool/linuxcdeps_test.go, internal/tunnel/tordesktop.go, internal/tunnel/torembed.go, internal/tunnel/tormobile.go
While there, improve docs and notice we could upgrade the tor version we're using on Linux. The code builds locally both for Android and iOS. We'll test the changes in the 3.17 cycle.
See https://github.com/ooni/probe/issues/2365
=> chore: update to ooni/go-libtor v1.1.7

.github/workflows/alltests.yml, .github/workflows/android.yml, .github/workflows/checks.yml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yml, .github/workflows/debianrepo.yml, .github/workflows/generate.yml, .github/workflows/ghpublish.yml, .github/workflows/gosec.yml, .github/workflows/ios.yml, .github/workflows/jafar.yml, .github/workflows/libtorlinux.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/netxlite.yml, .github/workflows/oohelperd.yml, .github/workflows/qa.yml, .github/workflows/tarball.yml, .github/workflows/windows.yml, internal/cmd/buildtool/windows.go, internal/cmd/ghgen/linux.go, internal/cmd/ghgen/utils.go
The check for the number of tokens was failing for Windows so relax the check to say "three or more".
There's a warning related to use the old checkout@v2, so upgrade to using checkout@v3 for all workflows in the repo.
The Linux action didn't set the correct version of Go, so it wasn't possible to start the build.
Everything else was WAI.
Part of https://github.com/ooni/probe/issues/2273.
=> fix: attempt to make all workflows green

internal/bytecounter/http.go, internal/bytecounter/http_test.go, internal/bytecounter/resolver.go, internal/bytecounter/resolver_test.go, internal/engine/session.go, internal/legacy/netx/http.go, internal/model/mocks/underlyingnetwork.go, internal/model/mocks/underlyingnetwork_test.go, internal/model/netx.go, internal/netxlite/dialer.go, internal/netxlite/dnsovergetaddrinfo.go, internal/netxlite/quic.go, internal/netxlite/tls.go, internal/netxlite/tproxy.go, internal/netxlite/tproxy_test.go, internal/sessionresolver/factory.go, internal/sessionresolver/factory_test.go, internal/sessionresolver/resolver.go, internal/sessionresolver/resolver_test.go, internal/sessionresolver/resolvermaker.go
This diff closes https://github.com/ooni/probe/issues/2121 because it removes the last unnecessary netx usage. All the other packages that currently use netx are network experiments. We will eventually convert them to not use netx as part of other tracked issues.
This diff closes https://github.com/ooni/probe/issues/2135 because now the sessionresolver does not depend on netx anymore.
We refactor the way in which we conditionally configure byte counting for HTTP such that we use a free function rather than a method (we can use methods with nil receiver in Go, but the free function seems to be a better choice in this case).
We introduce and use a new bytecounter specifically for the system resolver. This byte counter is very imprecise but seems still better than using the system resolver …
=> cleanup(sessionresolver): don't depend on netx

internal/netxlite/dialer_test.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go, internal/netxlite/tls.go, internal/netxlite/tls_test.go, internal/netxlite/tproxy_test.go
This diff tweaks https://github.com/ooni/probe-cli/pull/1068 to make sure overriding the default cert pool works.
In https://github.com/ooni/probe-cli/pull/1068 we introduced code to add this functionality but we never tested it was working as intended. It turns out it was not!
Because this diff amends the previous diff, we'll consider it part of https://github.com/ooni/probe/issues/2135.
=> fix(netxlite): allow overriding default cert pool

.github/workflows/libtorlinux.yml, internal/libtor/enabled.go
Discovered while trying to understand the reason why we have an abort caused by Android's fdsan.
This is not the reason why we abort, but it seems correct to fix this issue anyway.
While there, notice that stopping to run libtorlinux for every PR (which we just did in https://github.com/ooni/probe-cli/commit/5ebcca256c50e7b40d3141534627d151ab20e4bd) was wrong. We need to run this workflow for every PR because it runs tests for the libtor integration.
Part of https://github.com/ooni/probe/issues/2405
=> fix(libtor): don't leak a file descriptor

internal/experiment/hirl/hirl.go, internal/experiment/hirl/hirl_test.go
This patch teaches the hirl experiment to log its test helper, which is useful when debugging hirl-related issues.
Because this change is very minor, we don't need an issue for that.
=> hirl: log the test helper address

pkg/oonimkall/session.go
This diff ensures we remove in probe-cli all the functions we have removed in https://github.com/ooni/probe-android/pull/552.
Part of https://github.com/ooni/probe/issues/2273.
Tested by recompiling the AAR and linking it into the Android app.
=> cleanup(oonimkall): remove MaybeUpdateResources stub

internal/experiment/dash/collect.go, internal/experiment/dash/dash.go, internal/experiment/dash/dash_test.go, internal/experiment/dash/download.go, internal/experiment/dash/fake_test.go, internal/experiment/dash/locate.go, internal/experiment/dash/model.go, internal/experiment/dash/negotiate.go
Make sure we use model.HTTPClient rather than a bare *http.Client when applicable. Make sure we use `any` rather than using the `interface{}` type. Make sure we document all structs, functions, files, and struct fields, for extra clarity.
We implemented these changes as preliminary yak shaving before working on https://github.com/ooni/probe/issues/2398.
=> cleanup(dash): improve docs and modernize the implementation

internal/experiment/dash/measurer_test.go, internal/experiment/dash/runner_test.go
The mockable.Session struct has been deprecated. Rewrite tests to use the mocks.Session struct instead.
Yak shaving for https://github.com/ooni/probe/issues/2398.
=> cleanup(dash): avoid using mockable.Session

internal/experiment/dash/measurer.go, internal/experiment/dash/runner.go, internal/experiment/dash/runner_test.go
I don't like having struct method receivers because they may hide the side effects of mutating fields.
Instead, rewrite the code such that we are using pointer receivers or we are not using methods and we're using functions instead.
Final yak shaving for https://github.com/ooni/probe/issues/2398.
=> refactor(dash): avoid using struct method receivers

.gitignore, internal/cmd/oohelperd/main.go
There is a way to collect CPU profiles using HTTP. However, let's start with a simple diff that allows for performing local profiling, which seems to be enough to start understanding what's wrong with oohelperd.
See https://github.com/ooni/probe/issues/2413
=> feat(oohelperd): allow collecting CPU profiles

internal/cmd/oohelperd/main.go, internal/cmd/oohelperd/quic.go, internal/cmd/oohelperd/tcptls.go
This commit creates a private static cert pool to use in the oohelperd when issuing QUIC and TLS connections.
See https://github.com/ooni/probe/issues/2413 for context.
=> fix(oohelperd): use cached cert pool for quic and tls

internal/model/mocks/underlyingnetwork.go, internal/model/mocks/underlyingnetwork_test.go, internal/model/netx.go, internal/netxlite/quic.go, internal/netxlite/tls.go, internal/netxlite/tproxy.go, internal/netxlite/tproxy_test.go, internal/sessionresolver/resolver_test.go
This diff is slightly more complex than the naive diff that creates
a private static pool and uses it for quic and tls. The reason is
that we also need to support a mechanism allowing integration tests
to transparently override the default cert pool.
See https://github.com/ooni/probe/issues/2413 for context.
=> fix(netxlite): use private static default cert pool

internal/cmd/oohelperd/handler.go, internal/cmd/oohelperd/handler_test.go, internal/cmd/oohelperd/ipinfo.go, internal/cmd/oohelperd/logging.go, internal/cmd/oohelperd/logging_test.go, internal/cmd/oohelperd/main.go, internal/cmd/oohelperd/measure.go
This diff attempts to rewrite and steer handler_test.go such that it mostly contains unit tests. As part of this work, we create a single factory function for constructing the handler. While there, we also rename the indexLogger to prefixLogger (a more accurate name) and we deploy more comments and whitespaces.
Part of https://github.com/ooni/probe/issues/2413
=> refactor(oohelperd): improve handler tests

internal/cmd/oohelperd/main.go, internal/cmd/oohelperd/main_test.go
This diff increases the timeout used to await for pending requests and parallelizes the shutdown of servers.
While there, let's move all the flags at toplevel for clarity.
While there, recognize that we can use the channel's signal for shutting down the server in tests.
These changes are preliminary changes before making the oohelperd more capable of serving interesting metrics and debug info.
See https://github.com/ooni/probe/issues/2413
=> fix(oohelperd): allow pending requests to complete

.github/workflows/oohelperd.yml, CLI/.gitignore, internal/cmd/buildtool/main.go, internal/cmd/buildtool/oohelperd.go, internal/cmd/buildtool/oohelperd_test.go, internal/cmd/oohelperd/main.go, internal/cmd/oohelperd/main_test.go, internal/cmd/oohelperd/replace.go, internal/cmd/oohelperd/replace_test.go
* buildtool: add rules to build oohelperd
* .github/workflows: use buildtool to build oohelperd
* oohelperd: add `-replace` flag to replace an already running instance of the oohelperd
* oohelperd: add `-version` flag to get version
Part of https://github.com/ooni/probe/issues/2413
=> feat(oohelperd): make 0.th.ooni.org deployment easier

internal/cmd/oohelperd/handler_test.go, internal/cmd/oohelperd/measure.go, internal/model/th.go
I have been eyeballing the performance charts for a few days and it seems that enabling QUIC makes measurements slower.
The TH requires more time to complete. So, the probe can measure less target URLs per run, given finite runtime constraints.
Measuring QUIC in the TH when the probe also measures QUIC is fine because we obtain higher quality measurements.
However, now that most probes do not know about QUIC, it makes sense to avoid measuring QUIC for them, so they continue to measure the same number of URLs as before.
This diff belongs to the not-ever-small set of diffs authored when doing pre-release QA. See https://github.com/ooni/probe/issues/2273.
=> fix(oohelperd): disable QUIC by default

internal/dslx/quic.go, internal/dslx/quic_test.go, internal/dslx/tls_test.go
This PR fixes the QUIC SNI logic to be analogous to the SNI logic used in the TLS code. Respective unit tests are added.
Reference issue: https://github.com/ooni/probe/issues/2402.
=> fix(dslx): Use QUIC server name logic analogous to TLS code

MONOREPO/tools/gitconfig.bash, MONOREPO/tools/local.example.bash
These two repositories are the only ones we can manage through the monorepo scripts for integration testing.
Closes https://github.com/ooni/probe/issues/2432
=> cleanup(monorepo): only clone desktop and android

internal/dslx/http_test.go, internal/dslx/httpquic.go
This PR adds a utility function to dslx which composes a HTTP-over-QUIC operation by combining `HTTPTransportQUIC()` and `HTTPRequest()`. Similar composition functions exist for HTTP-over-TCP and HTTP-over-TLS and they are useful because in order to do the HTTP "step", we usually need to do both: Create an HTTP Transport and run the HTTP Request.
=> feat(dslx): Add HTTPRequestOverQUIC composition

internal/optional/optional.go, internal/optional/optional_test.go
This diff introduces the `optional` package to handle optional values
=> feat: introduce optional package

internal/experiment/signal/signal.go
The reference to the `api.directory.signal.org` domain was removed in signalapp/Signal-TLS-Proxy@461d2d1aeec601a4d62100949a227f0cef2f6154, so the check for Signal fails. This commit removes the reference to the domain in OONI Probe as well.
=> signal: remove check for api.directory.signal.org

cmd/ooniprobe/internal/log/handlers/cli/cli.go
Formatted remaining time in CLI (run websites) as standard time.Duration format, for example shows (1h7m19.018s) left instead of seconds for durations>=60 sec.  Propose rounding to time.Millisecond instead of "%.2f", for cleaner code;  only "time" package used, no extra dependencies.
=> show remaining time in CLI as h-m-s instead of seconds #2454

internal/dslx/httpcore.go, internal/dslx/observations.go
This diff introduces a `dslx.NewObservations` constructor to be used for initializing `Observations` with empty measurements
=> feat: introduce dslx Observations constructor

internal/dslx/dns.go, internal/dslx/dns_test.go, internal/dslx/endpoint.go, internal/dslx/endpoint_test.go, internal/dslx/http_test.go, internal/dslx/httpcore.go, internal/dslx/quic.go, internal/dslx/quic_test.go, internal/dslx/tcp.go, internal/dslx/tcp_test.go, internal/dslx/tls.go, internal/dslx/tls_test.go, internal/measurexlite/conn.go, internal/measurexlite/conn_test.go, internal/measurexlite/dialer.go, internal/measurexlite/dialer_test.go, internal/measurexlite/dns.go, internal/measurexlite/dns_test.go, internal/measurexlite/failure.go, internal/measurexlite/http.go, internal/measurexlite/http_test.go, internal/measurexlite/logger.go, internal/measurexlite/quic.go, internal/measurexlite/quic_test.go, internal/measurexlite/tls.go, internal/measurexlite/tls_test.go, internal/measurexlite/trace.go, internal/measurexlite/trace_test.go, internal/measurexlite/utls_test.go, internal/model/archival.go
Closes https://github.com/ooni/probe/issues/2483
While there, make sure we have 100% coverage in `dslx` and `measurexlite`.
See https://github.com/ooni/spec/pull/275.
=> feat(archival,dslx,measurexlite): tag all observations

internal/cmd/buildtool/android_test.go, internal/cmd/buildtool/cdepsopenssl.go, internal/cmd/buildtool/linuxcdeps_test.go
This diff forward ports 325a8412999b001f4913ab5c522ed6402c9d78fe from the release/3.17 branch to the master branch.
See https://github.com/Homebrew/homebrew-core/commit/8a9e8458399f7f9ca15948918ba5d003126dfa51
=> [forwardport] fix: use openssl-1.1.1u

internal/cmd/oohelperd/main.go, internal/netxlite/http3.go
See https://github.com/ooni/probe/issues/2488.
This patch needs to be backported to the release/3.17 branch.
=> fix(oohelperd): use cookiejar for HTTP measurements

MOBILE/android/ensure, go.mod, go.sum, internal/model/http.go
See https://github.com/ooni/probe/issues/2417
=> chore: minor changes before 3.18.0-alpha

CONTRIBUTING.md, internal/model/netx.go
We renamed it to NewMozillaCertPool in #1129.
=> fix: do not mention NewDefaultCertPool

.github/workflows/ios.yml, .github/workflows/windows.yml, internal/cmd/ghgen/ios.go, internal/cmd/ghgen/windows.go
This diff forward ports 8a85b6379ba5ad7c23d494158ea3a5d535b36587 to the master development branch.
We have updated the runners, so the versions have changed as well.
See https://github.com/ooni/probe/issues/2417
=> [forwardport] fix: use correct Xcode and mingw version

.github/workflows/alltests.yml, .github/workflows/android.yml, .github/workflows/coverage.yml, .github/workflows/generate.yml, .github/workflows/gosec.yml, .github/workflows/ios.yml, .github/workflows/jafar.yml, .github/workflows/libtorlinux.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/netxlite.yml, .github/workflows/oohelperd.yml, .github/workflows/tarball.yml, .github/workflows/windows.yml, internal/cmd/ghgen/utils.go
See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> fix(.github): avoid using deprecated ::set-output

internal/measurexlite/utls.go, internal/memoryless/memoryless.go, internal/memoryless/memoryless_test.go
The ndt7 server uses memoryless to avoid sampling the download speed at constant intervals, which provides PASTA properties (where PASTA means Poisson Arrivals See Time Averages).
In other words, ndt7 has a better download speed observation mechanism than one that samples at fixed intervals because the observation is independent of possibly cyclical events happening in the network that could synchronize with the download speed polling period.
We want to have the same properties for measuring the download speed inside of Web Connectivity LTE.
To this end, let us import the package m-lab uses for ndt7 server.
This work is part of https://github.com/ooni/probe/issues/2493.
=> chore: import memoryless from m-lab/go

internal/measurexlite/conn.go, internal/measurexlite/dialer.go, internal/measurexlite/dns.go, internal/measurexlite/http.go, internal/measurexlite/tls.go
I noticed this issue while working on https://github.com/ooni/probe/issues/2493
=> cleanup: measurexlite should not depend on tracex

internal/experiment/webconnectivitylte/cleartextflow.go, internal/experiment/webconnectivitylte/secureflow.go, internal/measurexlite/conn.go, internal/measurexlite/conn_test.go, internal/measurexlite/dialer.go, internal/measurexlite/dns.go, internal/measurexlite/doc.go, internal/measurexlite/quic.go, internal/measurexlite/trace.go, internal/throttling/throttling.go, internal/throttling/throttling_test.go
This diff implements a lightweight approach to throttling that takes advantage of the step-by-step design and should also be suitable to measure throttling using `dslx` (see https://github.com/ooni/probe/issues/2493).
Before discussing the approach implemented here, it is important to point out that:
1. if we're using step-by-step, we're collecting up to 64 network events for a single network connection;
2. with step-by-step, each trace is bound to a single network connection or DNS round trip;
3. both Web Connectivity v0.5 and dslx use the step-by-step approach;
4. therefore, for extreme throttling of a single connection, 64 I/O events are *a lot of events* to observe throttling;
5. additionally, we're currently limited at downloading `1<<19` bytes of the body, so there is not much room …
=> feat: lightweight throttling measurements

internal/experiment/webconnectivitylte/measurer.go
We should have done this in https://github.com/ooni/probe-cli/pull/1166.
We'll account this diff as part of https://github.com/ooni/probe/issues/2493.
=> fix(webconnectivitylte): bump to 0.5.24

internal/tutorial/experiment/torsf/chapter01/main.go, internal/tutorial/experiment/torsf/chapter03/torsf.go, internal/tutorial/experiment/torsf/chapter04/torsf.go
Following the tutorial code results in a broken pipe. This is a simple fixup that adds a call to tail so that jq is only given valid input.
=> fix(tutorial): avoid broken pipe caused by passing non-JSON to jq

internal/cmd/buildtool/android_test.go, internal/cmd/buildtool/cdepslibevent.go, internal/cmd/buildtool/cdepsopenssl.go, internal/cmd/buildtool/cdepstor.go, internal/cmd/buildtool/cdepszlib.go, internal/cmd/buildtool/linuxcdeps_test.go, pkg/oonimkall/xoonirun_test.go
Part of https://github.com/ooni/probe/issues/2524. Prompted by observing a failing Linux build test for zlib.
Upgrading to OpenSSL v3 is tracked by https://github.com/ooni/probe/issues/2498 and implemented by https://github.com/ooni/probe-cli/pull/1191.
While there, fix ./pkg/oonimkall integration tests as well.
=> chore: upgrade C dependencies

CDEPS/openssl/001.patch, internal/cmd/buildtool/android_test.go, internal/cmd/buildtool/cdepsopenssl.go, internal/cmd/buildtool/linuxcdeps_test.go
This diff modifies the build process such that we use OpenSSL 3.1.2 for the Android build which is the same OpenSSL version as used by [homebrew-core](https://github.com/Homebrew/homebrew-core/blob/master/Formula/openssl@3.rb).
=> chore(cdeps): upgrade to OpenSSL 3.1.2

internal/netemx/qaenv.go
This diff factors the function used for listening out of the loop where we create all the servers stacks. The same diff is part of the original PR that introduced these changes: https://github.com/ooni/probe-cli/pull/1185.
The intent of pushing this commit is to make sure the diff we're merging next is easier to understand because there's no refactoring noise.
Reference issue: https://github.com/ooni/probe/issues/2461.
---------
Co-authored-by: kelmenhorst <k.elmenhorst@mailbox.org>
=> refactor(netemx): factor function for listening

go.mod, go.sum, internal/netemx/scenario.go
This diff modifies the netemx scenario to avoid using a bit mask since it's not possible for a host to have multiple roles.
While there, upgrade github.com/ooni/netem to pull a fix that causes the start topology to return an error if you attempt to add the same host's IP address multiple times.
Part of https://github.com/ooni/probe/issues/2461
=> fix(netemx): avoid suggesting more than one role is possible

go.mod, go.sum, internal/experiment/webconnectivity/qa_test.go, internal/experiment/webconnectivityqa/dnsblocking.go, internal/experiment/webconnectivityqa/dnsblocking_test.go, internal/experiment/webconnectivityqa/testcase.go, internal/netemx/android.go, internal/netemx/qaenv.go, internal/netxlite/getaddrinfo.go, internal/netxlite/getaddrinfo_bsd.go, internal/netxlite/getaddrinfo_linux.go, internal/netxlite/getaddrinfo_test.go, internal/netxlite/getaddrinfo_windows.go
Part of https://github.com/ooni/probe/issues/2029. The general idea is to modify v0.4 in a subsequent PR to make it WAI for this test case. Currently v0.4 does not correctly support this case, which is why we're doing this work. (See also https://github.com/ooni/probe/issues/2499).
=> feat(webconnectivityqa): add test for android_dns_cache_no_data

QA/webconnectivity.py, internal/experiment/webconnectivityqa/testcase.go, internal/experiment/webconnectivityqa/websitedown.go
This diff imports the QA/webconnectivity.py integration test into the webconnectivityqa framework and removes it from Python. While there, remove other QA/webconnectivity.py tests that I have already converted.
Part of https://github.com/ooni/probe/issues/1803.
See also https://github.com/ooni/probe/issues/1536.
=> chore(webconnectivityqa): import webconnectivity_nonexistent_domain

.github/workflows/libtorlinux.yml, QA/webconnectivity.py, internal/experiment/webconnectivityqa/dnsblocking.go, internal/experiment/webconnectivityqa/dnsblocking_test.go, internal/experiment/webconnectivityqa/testcase.go
This diff imports the given QA/webconnectivity.py integration test into the webconnectivityqa framework and removes it from Python. While there, stop building libtorlinux.yml on pull requests, since currently there's no need.
Part of https://github.com/ooni/probe/issues/1803.
=> chore(webconnectivityqa): import webconnectivity_dns_blocking_nxdomain

QA/webconnectivity.py, internal/experiment/webconnectivityqa/dnsblocking.go, internal/experiment/webconnectivityqa/tcpblocking.go, internal/experiment/webconnectivityqa/tcpblocking_test.go, internal/experiment/webconnectivityqa/testcase.go, internal/experiment/webconnectivityqa/tlsblocking.go, internal/experiment/webconnectivityqa/websitedown.go, internal/mocks/underlyingnetwork.go, internal/mocks/underlyingnetwork_test.go, internal/model/netx.go, internal/netemx/adapter.go, internal/netxlite/dialer.go, internal/netxlite/dialer_test.go, internal/netxlite/netem.go, internal/netxlite/tproxy.go, internal/netxlite/tproxy_test.go, internal/sessionresolver/resolver_test.go
This diff imports the given QA/webconnectivity.py integration test into the webconnectivityqa framework and removes it from Python. To this end, we need to modify how we handle timeouts in netxlite such that it is possible to change the default timeout programmatically when using netemx. While there, document the flag magic numbers used in tests, so that each test makes much more sense when reading it.
Part of https://github.com/ooni/probe/issues/1803.
=> chore(webconnectivityqa): import ...tcpip_blocking_with_consistent_dns

internal/netxlite/dialer.go, internal/netxlite/dialer_test.go, internal/netxlite/dnsovergetaddrinfo.go, internal/netxlite/dnsovergetaddrinfo_test.go, internal/netxlite/netx.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go, internal/netxlite/tls.go, internal/netxlite/tls_test.go, internal/netxlite/tproxy.go, internal/netxlite/tproxy_test.go
If we want to make other OONI components use either the default model.UnderlyingNetwork or a custom one, we need to expose the related routing functionality from netxlite.
Having this functionality handy would be useful, for example, to write a resolver IP lookup package that would work as intended both when using the regular network and when using netem.
In turn, this functionality opens up the possibility of running the whole of ooniprobe inside of netem in an easier way.
Related to https://github.com/ooni/probe/issues/2461.
=> feat(netxlite): expose MaybeCustomUnderlyingNetwork

internal/experiment/webconnectivitylte/qa_test.go, internal/experiment/webconnectivityqa/tcpblocking.go, internal/experiment/webconnectivityqa/tcpblocking_test.go, internal/netemx/android_test.go, internal/netemx/example_test.go, internal/netemx/oohelperd_test.go, internal/netemx/qaenv.go, internal/netemx/scenario.go
As we learned in https://github.com/ooni/probe-cli/pull/1216, using the 130.192.91.x namespace for every IP address in netemx breaks mapping domain names to IP addresess in Web Connectivity. No IP address would ever, in fact, be inconsistent, because they all belong to AS137.
Initially, I thought about overriding the code that maps IP addresses to ASNs, to provide a custom implementation. But then I realized it was a more thorough test to use the default implementation (relying on maxminddb files) and using the correct IP addresses in the correct address space.
My original thought for using 130.192.91.x addresses was that they were not the right addresses for the domains we're testing, thus, in the event in which netem was not WAI, all tests would have failed. However, we have many tests …
=> fix: avoid using 130.192.91.x for most netemx addresses

internal/experiment/webconnectivitylte/qa_test.go, internal/experiment/webconnectivityqa/measurement.go, internal/experiment/webconnectivityqa/session.go, internal/experiment/webconnectivityqa/tcpblocking.go, internal/experiment/webconnectivityqa/tcpblocking_test.go, internal/netemx/adapter.go, internal/netemx/address.go, internal/netemx/doc.go, internal/netemx/example_test.go, internal/netemx/oohelperd_test.go, internal/netemx/qaenv.go, internal/netemx/qaenv_test.go, internal/netemx/scenario.go
I am trying to lift some netemx restrictions that make certain Web Connectivity integration tests a bit unrealistic. To progress towards this goal, I have determined that I need to (1) improve the construction for the  QAEnv and (2) make the scenario constructor a function that initialized a given QAEnv rather than rolling additional abstraction on top of it.
The current diff moves IP addresses around to create space for myself to attempt to implement the above changes.
The reference issue is https://github.com/ooni/probe/issues/1803.
=> refactor(netemx): move notable IP addrs in a separate file

internal/experiment/telegram/telegram_test.go, internal/experiment/whatsapp/whatsapp_test.go, internal/netemx/example_test.go, internal/netemx/netstack.go, internal/netemx/qaenv.go, internal/netemx/tcpecho.go
This diff starts refactoring netemx such that any kind of service we want to create for a given IP address uses the same interface, which is a generic factory to create a generic server working depending on a netstack.
The overall objective here is to enable the same IP address to serve DNS, HTTP/HTTPS/HTTP3, and possibly arbitrary other services. Currently, we can only choose one of these services per IP address. This limitation, for example, makes it impossible to have 8.8.8.8 handle both Do53 and DoH.
I will move towards this objective incrementally. This diff just refactors the way in which we manage the echo server to follow a model where there is a factory for creating a server, which is what HTTP code is using.
Once this diff lands, I will refactor HTTP and DNS to follow this …
=> refactor(netemx): move towards unified factory/server

internal/experiment/telegram/telegram_test.go, internal/netemx/http.go, internal/netemx/http_test.go, internal/netemx/web.go
The overall intent of this work is to unify how we manage HTTP, DNS, and ordinary netstacks for netemx, and allow the same IP address to host multiple servers rather than just one, as it's currently the case.
To this end, the current diff adapts code that used to be an integration test for telegram to become the cleartext HTTP NetStackServerFactory.
=> feat(netemx): adapt NetStackServerFactory from telegram

internal/netemx/https.go, internal/netemx/https_test.go
This diff continues improving and refactoring netemx with the objective of unifying how we create all kind of servers.
Here, specifically, we modify the HTTP server implementing NetStackServerFactory implemented in the previous commit and obtain an HTTPS server honouring NetStackServerFactory.
Crucially, this diff also adds support for overriding the TLS config passed to the server, which enables us to test for expired certificates, self-signed certificates, and so forth.
=> feat(netemx): HTTPS server implementing NetStackServerFactory

internal/netemx/http3.go, internal/netemx/http3_test.go
This diff continues improving and refactoring netemx with the objective of unifying how we create all kind of servers.
Here, specifically, we modify the HTTPS server implementing NetStackServerFactory implemented in the previous commit and obtain an HTTP3 server honouring NetStackServerFactory.
Crucially, this diff also adds support for overriding the TLS config passed to the server, which enables us to test for expired certificates, self-signed certificates, and so forth.
While working on this diff, I noticed a weird behavior with HTTP/3 tests using the same address, which is documented at https://github.com/ooni/probe/issues/2527. I modified the tests to make them pass. To this end, I changed the IP addresses used by HTTP/3 tests to avoid reusing www.example.com's IP address. It seems …
=> feat(netemx): HTTP3 server implementing NetStackServerFactory

internal/netemx/http.go, internal/netemx/http3.go, internal/netemx/https.go, internal/netemx/netstack.go, internal/netemx/qaenv.go, internal/netemx/tcpecho.go, internal/netemx/udpresolver.go, internal/netemx/udpresolver_test.go
This diff moves forward the work we're doing to try to unify the way in which all the possible servers in netemx are constructed.
The general idea is to enable configuring every kind of server using the QAEnvOptionNetStack option.
To this end, we need to implement NetStackServerFactory.
In this diff, in particular, we're implementing a NetStackServerFactory for constructing DNS-over-UDP servers. These servers would use:
1. the OtherResolversConfig for lookups (which makes sense because the [MustNewQAEnv] internally constructs the ISP resolver);
2. the logger configured for the QAEnv.
=> feat(netemx): implement NetStackServerFactory for DNS-over-UDP

internal/experiment/telegram/telegram_test.go, internal/netemx/geoip.go, internal/netemx/http.go, internal/netemx/http3.go, internal/netemx/http3_test.go, internal/netemx/http_test.go, internal/netemx/https.go, internal/netemx/https_test.go, internal/netemx/ooapi.go, internal/netemx/oohelperd.go, internal/netemx/scenario.go
With the changes we implemented so far, we're not able to start migrating part of scenario.go (probably the easiest part) to use QAEnvOptionNetStack for configuring servers.
=> refactor(netemx/scenario.go): start using QAEnvOptionNetStack

internal/netemx/dnsoverhttps.go, internal/netemx/example_test.go, internal/netemx/oohelperd.go, internal/netemx/oohelperd_test.go, internal/netemx/qaenv.go, internal/netemx/qaenv_test.go, internal/netemx/scenario.go, internal/netemx/web.go
This diff converts the ScenarioRoleWebServer case to using QAEnvOptionNetStack. While there, recognize that
https://github.com/ooni/probe/issues/2527 is really making all QUIC tests fragile, and scale them down a bit.
=> feat(netemx): ScenarioRoleWebServer using QAEnvOptionNetStack

internal/netemx/example_test.go, internal/netemx/http3.go, internal/netemx/http3_test.go, internal/netemx/oohelperd.go, internal/netemx/oohelperd_test.go, internal/netemx/qaenv_test.go, internal/netemx/scenario.go, internal/netemx/web.go
This diff fixes https://github.com/ooni/probe/issues/2527.
The comment I originally wrote in the code to explain the issue read:
> I am wondering whether I am not fully understanding how quic-go/quic-go works.
It turns out this comment was true. I was assuming http3.Server was closing the listener, however, that was not the case.
I noticed this issue when reading again netemx/qaenv.go.
So, it all boiled down to PEBCAK 😬.
=> fix(netemx): address issues with quic-go/quic-go

internal/experiment/telegram/telegram_test.go, internal/netemx/dnsoverhttps.go, internal/netemx/example_test.go, internal/netemx/geoip.go, internal/netemx/http.go, internal/netemx/http3.go, internal/netemx/http3_test.go, internal/netemx/http_test.go, internal/netemx/https.go, internal/netemx/https_test.go, internal/netemx/ooapi.go, internal/netemx/oohelperd.go, internal/netemx/qaenv.go, internal/netemx/scenario.go, internal/netemx/web.go, internal/netemx/web_test.go
This diff continues the refactoring of netemx to use a single mechanism to create all the possible kind of servers.
While there, this diff removes the limitation that we cannot create more than a single server per IP address, which was one of the reasons why we started this refactoring process.
While there, make sure we have full coverage of netemx.
=> refactor(netemx): use QAEnvOptionNetStack for ScenarioRoleDNSOverHTTPS

internal/experiment/dnsping/dnsping_test.go, internal/experiment/webconnectivitylte/qa_test.go, internal/experiment/webconnectivityqa/measurement.go, internal/experiment/webconnectivityqa/session.go, internal/netemx/address.go, internal/netemx/example_test.go, internal/netemx/netstack.go, internal/netemx/qaenv.go, internal/netemx/scenario.go, internal/netemx/udpresolver.go, internal/netemx/udpresolver_test.go
This diff removes code to init resolvers that does not use QAEnvOptionNetStack. This change allows us to drop duplicate code that we don't really need (in fact, removing this functionality does not produce a huge diff).
While there, we introduce more resolvers IP addresses, including 8.8.8.8, so we can simplify webconnectivitylte tests.
While there, rename the uncensored root resolver as the root resolver and use the F root resolver address for it.
While there, stop allowing to change the ISP resolver address or the root resolver address (there's no need).
=> cleanup(netemx): always init resolvers using QAEnvOptionNetStack

internal/experiment/webconnectivity/qa_test.go, internal/experiment/webconnectivitylte/qa_test.go, internal/experiment/webconnectivityqa/tcpblocking.go, internal/netemx/example_test.go, internal/netemx/qaenv.go, internal/netemx/scenario.go, internal/netemx/web.go
With all the changes implemented so far, we're now well positioned to futher cleanup netemx by implementing QAEnvOptionHTTPServer as just syntactic sugar for QAEnvOptionNetStack.
This change allows us to delete more code that is duplicating existing functionality and is not otherwise useful.
While there, introduce a role for a blockpage server and make sure that such a server only listens for HTTP, thus fixing a case in which the behavior of netemx was not consistent with the reality. After this change, we need to skip a QA test for LTE, because LTE is actually able to bypass the block and thus produces accurate webpage content.
Part of https://github.com/ooni/probe/issues/1803.
=> cleanup(netemx): QAEnvOptionHTTPServer is now syntactic sugar

QA/webconnectivity.py, internal/experiment/webconnectivityqa/control.go, internal/experiment/webconnectivityqa/control_test.go, internal/experiment/webconnectivityqa/testcase.go, internal/netemx/address.go, internal/netemx/scenario.go
This diff ports the tests where the control fails from Jafar to the new Web Connectivity QA framework.
=> chore(webconnectivityqa): port tests where the control fails

internal/model/archival_test.go, internal/testingx/httptestx.go, internal/testingx/httptestx_test.go, internal/testingx/tlsx.go, internal/testingx/tlsx_internal_test.go, script/nocopyreadall.bash
This diff adapts jafar HTTP proxy to be a testingx proxy.
We need this work to eventually get rid of jafar.
=> feat(testingx): adapt jafar HTTP proxy

internal/logx/handler_test.go, internal/logx/prefix_test.go, internal/testingx/tlssniproxy.go, internal/testingx/tlssniproxy_test.go, internal/testingx/tlsx.go, internal/testingx/tlsx_test.go, script/nocopyreadall.bash
This is the last bit of jafar we needed to import and adapt. What remains to be done now is finishing converting QA tests.
Then, we can remove jafar and QA.
While there, write missing netem tests for TLS servers.
=> feat(testingx): import and adapt jafar TLS SNI proxy

QA/webconnectivity.py, internal/experiment/webconnectivityqa/dnshijacking.go, internal/experiment/webconnectivityqa/testcase.go, internal/netemx/address.go, internal/netemx/scenario.go, internal/netemx/tlsproxy.go
This diff imports into webconnectivityqa test cases using proxies that are currently also implemented by ./QA/webconnectivity.py.
The ./QA/webconnectivity.py contains three test cases. Two of them deal with using transparent proxies without DNS lies, which was easy to do using iptables, and much harder now. However, it's doubtful whether those two cases are actually very useful, since there is no measurement feature which allows us to distinguish them from what we would otherwise get (perhaps, possibly latency?).
The third case, instead, is interesting and deals with the DNS serving to users the IP addresses of transparent HTTP and TLS proxies. To make this test case more similar to what it was in Python, and considering that LTE uses many resolvers, here I have chosen to use DNS …
=> webconnectivityqa: import test cases using proxies

QA/webconnectivity.py, go.mod, go.sum, internal/experiment/webconnectivityqa/dnshijacking_test.go, internal/experiment/webconnectivityqa/redirect.go, internal/experiment/webconnectivityqa/redirect_test.go, internal/experiment/webconnectivityqa/testcase.go, internal/netemx/example_test.go, internal/netemx/scenario.go, internal/netemx/web.go, internal/netemx/web_test.go
This diff starts adapting from QA/webconnectivity.py some of the test cases involding errors happening during HTTP redirects.
I am pleased to see that we've discovered LTE bugs thanks to these new test cases... well, let's say "pleased".
=> feat(webconnectivityqa): start adapting test cases with redirects

QA/webconnectivity.py, go.mod, go.sum, internal/experiment/webconnectivityqa/badssl.go, internal/experiment/webconnectivityqa/badssl_test.go, internal/experiment/webconnectivityqa/testcase.go, internal/netemx/address.go, internal/netemx/badssl.go, internal/netemx/badssl_test.go, internal/netemx/scenario.go
This diff imports the misconfigured-TLS test cases of the QA/webconnectivity.py test suite in webconnectivityqa.
The only QA/webconnectivity.py test case we're not merging is the one about self-signed certificate, which are equivalent enough to an unknown root certificate that it seems unimportant to merge them.
In other word, we have basically finished rewriting Jafar. Now it will be time to drop Jafar. 😅
=> feat(webconnectivityqa): import misconfigured-TLS test cases

internal/experiment/webconnectivityqa/badssl_test.go, internal/experiment/webconnectivityqa/control_test.go, internal/experiment/webconnectivityqa/dnsblocking_test.go, internal/experiment/webconnectivityqa/dnshijacking_test.go, internal/experiment/webconnectivityqa/httpdiff_test.go, internal/experiment/webconnectivityqa/redirect_test.go, internal/experiment/webconnectivityqa/tcpblocking_test.go, internal/experiment/webconnectivityqa/tlsblocking_test.go
This diff fixes the panics caused by the new quic-go API. 
We did not close the `QAEnv` in some of our webconnectivityqa tests. Therefore, the QUIC Server would not close the underlying UDP socket (`net.PacketConn`) and the local address of this socket would not be removed from the QUIC multiplexer. 
In the subsequent test case, the new quic-go API (see https://github.com/ooni/probe-cli/pull/1161) would panic because the local address of the server would still be registered in the global QUIC multiplexer.
=> fix(webconnectivityqa): Close the QAEnv

go.mod, go.sum, internal/dslx/dns.go, internal/dslx/httpcore.go, internal/dslx/quic.go, internal/dslx/tcp.go, internal/dslx/tls.go, internal/experiment/dnsping/dnsping.go, internal/experiment/portfiltering/tcpconnect.go, internal/experiment/simplequicping/simplequicping.go, internal/experiment/tcpping/tcpping.go, internal/experiment/tlsmiddlebox/connect.go, internal/experiment/tlsmiddlebox/dns.go, internal/experiment/tlsmiddlebox/tracing.go, internal/experiment/tlsping/tlsping.go, internal/experiment/webconnectivitylte/cleartextflow.go, internal/experiment/webconnectivitylte/control.go, internal/experiment/webconnectivitylte/dnsresolvers.go, internal/experiment/webconnectivitylte/secureflow.go, internal/logx/operation.go, internal/logx/operation_test.go, internal/measurex/logger.go, internal/oohelperd/dns.go, internal/oohelperd/http.go, internal/oohelperd/quic.go, internal/oohelperd/tcptls.go, internal/sessionresolver/resolver.go
I am starting to look into how to support beacons into the codebase as explained by https://github.com/ooni/probe/issues/2531.
The first issue that I stumbled upon is that there is excessive coupling between packages at the lower-levels, which we can reduce with easy refactoring, and which would help reasoning on what to do to address the underlying issue.
This diff is the first minor step towards cleaning up the code a bit: we are moving a functionality that pertains to logging from measurexlite to logx (which is where it should be).
While there, I noticed I needed to run `go mod tidy` to update the `go.mod` and `go.sum` files, which were outdated.
=> refactor(measurexlite): move OperationLogger to logx

internal/netemx/oohelperd.go, internal/netxlite/netx.go
I am reasoning about https://github.com/ooni/probe/issues/2531 and thus reading the codebase. I stumbled upon this inconsistency.
While there, I noticed some documentation also needed updating.
=> cleanup(netxlite): QUICListener -> UDPListener

internal/cmd/gardener/internal/dnsreport/dnsreport.go, internal/model/netx.go, internal/netxlite/dialer_test.go, internal/netxlite/dnsovergetaddrinfo.go, internal/netxlite/dnsoverhttps.go, internal/netxlite/dnstransport.go, internal/netxlite/dnstransport_test.go, internal/netxlite/netx.go, internal/netxlite/resolvercore.go, internal/netxlite/resolvercore_test.go, internal/testingx/tlssniproxy.go
This diff modifies how we construct netxlite's system resolver such that public functions use the *Netx equivalents.
While there, recognize that there wasn't enough testing for the optional wrappers provided by `model.DNSTransportWrapper` and that we are not using this functionality. So, rather than writing new tests for this functionality, we can actually just drop it and simplify the codebase.
While there, recognize that `netxlite.WrapDNSTransport` could easily become private.
While there, recognize that `./legacy/netx` needs lots of public function being exported by `netxlite` but we don't need to expose that many implementation details to new code that will be using `*Netx`. So, make sure all the new methods we create for `*Netx` are actually private methods. (Ideally, the API surface …
=> refactor(netxlite): use *Netx for the system resolver

internal/netxlite/dialer.go, internal/netxlite/dialer_test.go, internal/netxlite/netx.go, internal/netxlite/resolvercore.go, internal/netxlite/tls_test.go
This diff is like https://github.com/ooni/probe-cli/commit/7224984b36cae8b815006b240ded83a02c8a47b0 except that we are converting the system dialer constructors to use *Netx rather than converting the system resolver.
While there, realize that DialerSystem could become private.
=> refactor(netxlite): use *Netx for the system dialer

internal/netxlite/netx.go, internal/netxlite/quic.go, internal/netxlite/quic_test.go, internal/netxlite/udp.go, internal/netxlite/udp_test.go
This diff is similar to https://github.com/ooni/probe-cli/commit/07a048ce8e944ba68b3fd55faf6c1de9a9620485 but here we use *Netx to create UDP sockets.
While there, recognize that UDP code needs its own files and should not live inside quic{,_test}.go.
Part of https://github.com/ooni/probe/issues/2531.
=> refactor(netxlite): use *Netx for creating UDP sockets

internal/netxlite/netx.go, internal/netxlite/quic.go
This diff is like https://github.com/ooni/probe-cli/commit/8a5edc22e3fde71e412715e6f96797376252b0ce but here we use *Netx to create QUIC dialers.
While there, recognize that `WrapQUICDialer` could become a private function.
The general idea of this patchset is to ensure we're not using duplicate code for constructing netxlite types, which is good to do now, because we're about to introduce new netxlite types for the network with which we communicate with the OONI backend.
=> refactor(netxlite): use *Netx for creating QUIC dialers

internal/netxlite/netx.go, internal/netxlite/tls.go
This diff is like https://github.com/ooni/probe-cli/commit/50279a7f659d407c2dab6904227083087ae745e7 but uses *Netx to create TLS handshakers.
The general idea of this patchset is to ensure we're not using duplicate code for constructing netxlite types, which is good to do now, because we're about to introduce new netxlite types for the network with which we communicate with the OONI backend.
=> refactor(netxlite): use *Netx for creating TLS handshakers

internal/netxlite/dialer_test.go, internal/netxlite/http.go, internal/netxlite/netx.go
This diff is like https://github.com/ooni/probe-cli/commit/50279a7f659d407c2dab6904227083087ae745e7 but uses *Netx to create HTTP transports.
While there, annotate a test that is notoriously flaky on Windows.
The general idea of this patchset is to ensure we're not using duplicate code for constructing netxlite types, which is good to do now, because we're about to introduce new netxlite types for the network with which we communicate with the OONI backend.
=> refactor(netxlite): use *Netx for creating HTTP transports

internal/netxlite/http3.go, internal/netxlite/netx.go
This diff is like https://github.com/ooni/probe-cli/commit/50279a7f659d407c2dab6904227083087ae745e7 but uses *Netx to create HTTP3 transports.
The general idea of this patchset is to ensure we're not using duplicate code for constructing netxlite types, which is good to do now, because we're about to introduce new netxlite types for the network with which we communicate with the OONI backend.
=> refactor(netxlite): use *Netx for creating HTTP3 transports

internal/netxlite/resolvercore.go
While working on removing technical debt, as part of https://github.com/ooni/probe/issues/2531, it makes sense ensuring that there is a single way of constructing netxlite types by always using an instance of *Netx. This job is relatively easy because we are a couple of patches away from achieving this goal and, by doing this, we would avoid creating future technical debt. So, I am going to ahead and implement this.
Also, apparently, the oohelperd uses this functionality and somehow we missed
doing this when converting it to using netemx. We should fix this soon. (This issue
immediately validates what I was saying above about techdebt 😅)
=> feat(netxlite): use *Netx for creating DoH resolvers

internal/netxlite/utls.go
While working on removing technical debt, as part of https://github.com/ooni/probe/issues/2531, it makes sense ensuring that there is a single way of constructing netxlite types by always using an instance of *Netx. This job is relatively easy because we are a couple of patches away from achieving this goal and, by doing this, we would avoid creating future technical debt. So, I am going to ahead and implement this.
=> feat(netxlite): use *Netx for creating UTLS handshakers

internal/netxlite/resolvercore.go
The overall idea at this point is that we will have an interface containing the methods we currently have inside *Netx and we will sever the hard dependency between measurexlite and netxlite.
We will probably still need to import some contants from netxlite but, for all effects and purposes, measurexlite would become completely mockable (as it is now) with an explicit dependency on the related behavior.
In turn, this refactoring would clarify which netxlite functionality we use for measuring, which are legacy, and which we use for communicating with the OONI backend. That change would definitely make it obvious to modify netxlite and go in the overall direction defined by https://github.com/ooni/probe/issues/2531.
=> feat(netxlite): use *Netx for NewParallelUDPResolver

internal/mocks/measuringnetwork.go, internal/mocks/measuringnetwork_test.go, internal/mocks/quic.go, internal/mocks/quic_test.go, internal/mocks/udplistener.go, internal/mocks/udplistener_test.go, internal/model/netx.go, internal/netxlite/dialer.go, internal/netxlite/http3.go, internal/netxlite/netx.go, internal/netxlite/quic.go, internal/netxlite/resolvercore.go, internal/netxlite/tls.go, internal/netxlite/utls.go
This diff introduces the model.MeasuringNetwork interface that defines the factories required for implementing experiments.
By defining this interface, we can make measuring code depend on it rather than on the netxlite package.
While there, create specific files for `mocks.UDPListener`.
=> feat: introduce model.MeasuringNetwork

internal/mocks/measuringnetwork.go, internal/mocks/measuringnetwork_test.go, internal/model/netx.go, internal/netxlite/dialer.go, internal/netxlite/quic.go
I initially planned on defining only the dialers with resolver and explicitly passing `&NullResolver{}` to them.
But I have just realized that, instead, defining the dialers without resolvers (which is what measurexlite needs anyway) will allow me to rewrite the without-resolver case to be very simple and completely ignore resolvers.
Once I have done this rewrite, we can keep the existing implementation for legacy code, but we can also have:
1. the above-mentioned simple dialing implementation without resolvers that fullfills measurexlite needs;
2. another implementation tailored to the needs of beacons.
So, voila, I think I now have a reasonable way forward to introduce beacons support in netxlite.
=> refactor(MeasuringNetwork): define dialers without resolver

internal/measurexlite/dialer.go, internal/measurexlite/dialer_test.go, internal/measurexlite/dns.go, internal/measurexlite/quic.go, internal/measurexlite/quic_test.go, internal/measurexlite/tls.go, internal/measurexlite/tls_test.go, internal/measurexlite/trace.go, internal/measurexlite/trace_test.go, internal/measurexlite/utls.go, internal/measurexlite/utls_test.go
With this diff, we detach measurexlite from netxlite. It was already quite detached through functions used for testing. However, the changes we implement are allow us to test measurexlite code by changing the .Netx field of a *Trace, which means we can avoid using netxlite's singleton for new code.
Another benefit of this diff is that we have clearly spelled out and packaged into an interface the dependencies required to perform measurements with measurexlite. Therefore, we can gracefully continue separating the code used for measuring from the code for contacting the backend, as detailed in https://github.com/ooni/probe/issues/2531.
=> refactor(measurexlite): depend on model.MeasuringNetwork

internal/measurexlite/dialer.go, internal/measurexlite/dns.go, internal/measurexlite/quic.go, internal/measurexlite/trace.go, internal/measurexlite/udp.go, internal/measurexlite/udp_test.go
This diff is still yak shaving for https://github.com/ooni/probe/issues/2531 but produces some nice side effects. Now, we can either use netxlite.Netx or measurexlite.Trace as a dependency for measuring code.
The cost of this change is (1) switching some functions to use a `model.DebugLogger`, which is not an issue, and (2) adding some optional wrappers to other functions. I made these functions to ignore the wrappers and documented this limitation, because measurexlite code does not need this functionality. It is a bit debateable whether this is the best way to implement this change, but I am doing this because I would like to see these wrappers gone when we stop using legacy/netx in the codebase, so I think it's fine to ignore them, to better signal they're deprecated stuff.
This change …
=> feat(measurexlite): Trace now implements MeasuringNetwork

internal/engine/session.go, internal/engineresolver/doc.go, internal/engineresolver/errwrapper.go, internal/engineresolver/errwrapper_test.go, internal/engineresolver/factory.go, internal/engineresolver/factory_test.go, internal/engineresolver/integration_test.go, internal/engineresolver/jsoncodec.go, internal/engineresolver/jsoncodec_test.go, internal/engineresolver/lookup.go, internal/engineresolver/lookup_test.go, internal/engineresolver/resolver.go, internal/engineresolver/resolver_test.go, internal/engineresolver/resolvermaker.go, internal/engineresolver/resolvermaker_test.go, internal/engineresolver/state.go, internal/engineresolver/state_test.go
I am soon going to start addressing the underlying issue described by https://github.com/ooni/probe/issues/2531.
But, before doing that, I have noticed that the packages I need to edit to this end are the following:
```
./internal/engine
./internal/geolocate
./internal/sessionresolver
```
Now, these three packages work in unison to provide an `engine.Session` and they should *sort* together. However, I would like also to avoid nesting because I think each of them serves an ~independent purpose, and geolocate and sessionresolver are possibly building blocks to refactor or reimplement the engine.
For this reason, I have chosen to rename them such that it is clear they are the engine and supporting packages.
This diff addresses the second half of the change by renaming the sessionresolver …
=> refactor: rename sessionresolver engineresolver

internal/engine/experiment.go, internal/engine/session.go, internal/enginenetx/doc.go, internal/enginenetx/http.go, internal/enginenetx/http_test.go
It would be a *partial* deatch where we would override what we need for implementing https://github.com/ooni/probe/issues/2531.
To this end, I have created a new package called `enginenetx` (i.e., the engine network extensions), which will contain engine-specific code.
For now, I am just forwarding calls to netxlite. More changes will come as part of subsequent pull requests.
=> feat: prepare to partially detach engine from netxlite

internal/enginenetx/http.go, internal/netxlite/http.go, internal/netxlite/http_test.go
This diff inlines the original implementation of the netxlite.NewHTTPTransportWithLoggerResolverAndOptionalProxyURL function inside the enginex package.
With this diff, we continue to partially detach the engine networking from netxlite, to implement the beacons as described by https://github.com/ooni/probe/issues/2531.
=> cleanup: inline NewHTTPTransportWithLoggerResolverAndOptionalProxyURL

internal/netxlite/httpfactory.go, internal/netxlite/httpfactory_test.go, internal/netxlite/httpquirks.go
Now that we've clearly labeled and packaged technical debt, we can copy existing technical-debt-ridden code and modify it to obtain a flexible factory for creating HTTP transports, `NewHTTPTransportWithOptions`.
In particular, this factory uses sensible defaults for measuring and there are options that you can pass it to customize details such as the backend proxy that we previously unconditionally configured.
More in detail, this is a side-by-side comparison between new code's defaults and old code:
| Setting Name        | httpquirks.go (old code) | httpfactory.go  (new code) |
| ------------------- | ------------------------ | -------------------------- |
| .Proxy              | nil                      | nil                        |
| .MaxConnsPerHost    | 1                        | …
=> feat(netxlite): add flexible HTTP transport factory

internal/mocks/underlyingnetwork.go, internal/mocks/underlyingnetwork_test.go, internal/model/measurement_test.go, internal/model/netx.go, internal/netxlite/dialer_test.go, internal/netxlite/dnsovergetaddrinfo_test.go, internal/netxlite/netem.go, internal/netxlite/netem_test.go, internal/netxlite/netx_test.go, internal/netxlite/tproxy.go, internal/netxlite/tproxy_test.go
The lack of this support already created some difficulties inside the testingx package and I am increasinglty sick of it.
While there, see to increase the testing coverage of the netxlite package.
While there acknowledge and commit workaround for https://github.com/ooni/probe/issues/2537.
Added while looking into moving forward with making beacons fully testable using netem, per https://github.com/ooni/probe/issues/2531.
=> feat(UnderlyingNetwork): add support for ListenTCP

internal/netemx/tlsproxy.go, internal/netxlite/netx.go, internal/netxlite/netx_test.go, internal/testingx/httptestx.go, internal/testingx/tlssniproxy.go, internal/testingx/tlssniproxy_test.go
This diff adds the ListenTCP function to the *Netx struct.
With this addition, based on https://github.com/ooni/probe-cli/pull/1278, we can remove some techdebt inside the testingx package.
This is yak shaving while trying to add support for testing socks5 in the context of https://github.com/ooni/probe/issues/2531.
=> feat(netxlite): add (*Netx).ListenTCP

internal/legacy/netx/integration_test.go, internal/netemx/oohelperd_test.go, internal/testingproxy/hosthttp.go, internal/testingproxy/hosthttps.go, internal/testingproxy/netemhttp.go, internal/testingproxy/netemhttps.go, internal/testingproxy/qa_test.go, internal/testingproxy/sockshost.go, internal/testingproxy/socksnetem.go, internal/testingproxy/testcase.go, internal/testingsocks5/LICENSE, internal/testingsocks5/auth.go, internal/testingsocks5/client.go, internal/testingsocks5/client_test.go, internal/testingsocks5/doc.go, internal/testingsocks5/internal_test.go, internal/testingsocks5/qa_test.go, internal/testingsocks5/request.go, internal/testingsocks5/request_test.go, internal/testingsocks5/server.go, internal/testingx/httpproxy_test.go, internal/testingx/tlssniproxy_test.go, internal/testingx/tlsx_test.go, script/nocopyreadall.bash
This diff imports a fork of github.com/armon/go-socks5 that has been adapted to use netem and simplified to suit our testing needs.
With this functionality in tree, we can start thinking about writing better netem based tests for the ooniprobe bootstrap.
The overall idea is to be well positioned to improve the bootstrap and introduce dynamic support for beacons.
While there, discover that we were using `log.SetLevel(log.DebugLevel)` in a racy way in tests, so remove all the instances of this call from tests given that we can always add it when needed and we don't want to keep commented out code as a general policy anyway.
=> feat: support for testing socks5 clients

internal/enginenetx/http.go, internal/enginenetx/http_test.go, internal/netemx/qaenv.go, internal/netxlite/maybeproxy.go
This diff completes the work we have been doing for a few days now and provides HTTP and HTTPS proxy support, in addition to SOCKS5 support, for the engine-specific network.
We did this work in the context of https://github.com/ooni/probe/issues/2531 and https://github.com/ooni/probe/issues/1955.
BTW, the fact that tests used `measurexlite` and tracing is very nice here. It means the idea to write `measurexlite` based on context and tracing was good and could be used beyond its original design goals.
=> feat(enginenetx): support HTTP and HTTPS proxies

internal/enginenetx/httpsdialer.go, internal/enginenetx/httpsdialer_internal_test.go, internal/enginenetx/httpsdialer_test.go
This commit introduces a configurable HTTPS dialer that we will use for implementing beacons, and possibly also other functionality.
We need to perform TCP connect and TLS handshake as part of the same goroutine, because we cannot consider a dialing attempt successful after a successful TCP connect. Due to network interference, the dialing may also fail later during the TLS handshake.
To support several possible HTTPS dialing strategies, we need to extend what happens during a LookupHost operation. Generally, one would like to have addresses to dial. Rather, here we have tactics, where a single IP address MAY be included into more than a single tactic, if we need to try different tricks with the same address.
Also, tactics include a delay, which is useful to (a) avoid performing all …
=> feat(enginenetx): add configurable HTTPS dialer

internal/enginenetx/httpsdialer_internal_test.go, internal/enginenetx/httpsdialer_test.go
This uses the code introduced in the previous commit, i.e., https://github.com/ooni/probe-cli/commit/ac13e53521a4317d35239e8c7bf969f738816cf4.
I think it's good to have additional confidence that the `HTTPSDialer` does not leak connections. (Ideally, we would like to verify that we're not leaking connections everywhere, but for now just doing it for new code would do okay.)
While there, repair a test that was flaky because of nondeterministic channel selection.
Part of https://github.com/ooni/probe/issues/2531.
=> feat(enginenetx): make sure HTTPSDialer closes all connections

internal/enginenetx/httpsdialer.go
This diff modifies the tactics callbacks to take in input a context.
We need the context to know whether the operation failed in itself or was canceled externally through the context.
With this information, we can store better statistics about which tactics are working and which tactics are not working.
While there, fix a couple of typos (thanks @robertodauria!)
=> fix(enginenetx): pass context to tactics callbacks

internal/enginenetx/httpsdialer_internal_test.go, internal/enginenetx/httpsdialer_test.go, internal/enginenetx/httpsdialercore.go, internal/enginenetx/httpsdialernull.go
We cannot evaluate tactics on an IP address basis because different ports may cause tactics to fail. In principle we will probably only use port 443/tcp here, though it is better to avoid keeping lame code around.
While there, start preparing for inserting the tactics into a map to keep statistics.
=> fix(enginenetx): store endpoint into the tactic

CONTRIBUTING.md, internal/engine/experiment.go, internal/engine/session.go, internal/enginenetx/network.go, internal/enginenetx/network_internal_test.go, internal/enginenetx/network_test.go, internal/kvstore/memory.go
The HTTPTransport model only offers a CloseIdleConnections callback, which semantics is obviously that of closing idle connections (unsurprisingly).
However, the struct I am slowly building inside the enginenetx package soon will need to write back statistics to disk using a key-value store.
I don't think we should overload the CloseIdleConnections semantics to do this job, since the resulting code would be quite surprising.
Therefore, I have decided to rename HTTPTransport to Network and make it represent all the network abstractions required by the OONI engine.
In time, I will move extra functionality in there. For now, let us be happy that we can easily define a Close method (currently empty) for this type having the usual io.Closer semantics, i.e., that any resource opened by the type …
=> refactor(enginenetx): rename HTTPTransport to Network

internal/hujsonx/hujsonx.go, internal/hujsonx/hujsonx_test.go
The hujson is a JSON package from tailscale allowing JSON files to contain comments that is also more liberal with respect to commas.
We want to slowly upgrade all user-facing JSON-parsing code to use this more relaxed standard for parsing JSONs, because that would make our user's life significantly simpler in terms of writing and updating those files.
In the short term, I would like the configuration file driving the usage of beacons to use this relaxed parsing.
To this end, I am adding handy wrappers that combine using hujson with using the standard library parser to have a single hujson aware parsing function that behaves like the standard library's json.Unmarshal.
=> feat: add github.com/tailscale/hujson extensions

internal/enginenetx/httpsdialer_internal_test.go, internal/enginenetx/httpsdialer_test.go, internal/enginenetx/httpsdialercore.go, internal/enginenetx/network.go, internal/enginenetx/network_test.go, internal/model/netx.go, internal/netxlite/dialer.go, internal/netxlite/dnsovergetaddrinfo.go, internal/netxlite/netx.go, internal/netxlite/quic.go, internal/netxlite/resolvercore.go, internal/netxlite/resolvercore_test.go, internal/netxlite/tls.go, internal/netxlite/udp.go, internal/netxlite/utls.go, pkg/oonimkall/session_integration_test.go
This commit refactors how we construct the *Network used by the OONI engine so that the HTTPSTransport we use relies on the new HTTPSDialer as opposed to using netxlite's TLS dialing facilities.
This new HTTPSDialer has been specifically written to integrate TCP and TLS dialing and facilitate circumvention.
The current implementation uses a "null" policy which makes it roughly equivalent to the previous behavior, at least functionally, tough we are now doing a variation of happy eyeballs where to try to ~aggressively dial more connections as we see that previous connections fail to dial.
Specifically, if a TLS connection has not succeded within 300 milliseconds (probably a low value?), then we attempt dialing with another available IP address.
The new code documents extensively what we …
=> feat(enginenetx): use the new HTTPSDialer

internal/enginenetx/happyeyeballs.go, internal/enginenetx/happyeyeballs_test.go, internal/enginenetx/httpsdialernull.go
We want to pack attempts in parallel, which we also did before when the interval between attempts was linear.
We need to take into account possible congestion, so we should push back exponentially, even though the common case for us is probably censorship (but it is better to do the right thing anyway).
So, let's scale exponentially until we reach 30s. After that, it's fine to keep attempts evenly spaces, because 30s is quite definitely a huge interval if we're reasoning in internet time.
Also, change the base value used for TLS handshaking to be 900ms rather than 300ms, because a TLS handshake is ~3 round trips.
=> fix(enginenetx): refine the happy-eyeballs algorithm

internal/enginenetx/httpsdialer_test.go, internal/enginenetx/httpsdialercore.go, internal/enginenetx/httpsdialernull.go, internal/enginenetx/httpsdialerstats.go, internal/enginenetx/httpsdialerstats_internal_test.go, internal/enginenetx/httpsdialerstats_test.go, internal/enginenetx/network.go, internal/enginenetx/network_internal_test.go
This diff modifies the enginenetx package such that we track the results of operations we perform and collect statistics.
The statistics will be saved in the `StateDir` where we already save other statistics, e.g., the ones related to DoH.
While there, realize that we should also count the number of interrupted operations. Also, realize that the TLS verification cannot be interrupted, so there's no point in passing a `ctx` to the related stats manager callback.
=> feat(enginenetx): track operations and collect stats

internal/enginenetx/httpsdialer_internal_test.go, internal/enginenetx/httpsdialer_test.go, internal/enginenetx/httpsdialercore.go, internal/enginenetx/httpsdialernull.go, internal/enginenetx/httpsdialerstatic.go, internal/enginenetx/httpsdialerstatic_test.go, internal/enginenetx/network.go, internal/enginenetx/network_internal_test.go
Rather than waiting for LookupTactics to complete, make it async and let it stream the tactics back to the caller. This design allows us to start connecting while DNS lookups are still in progress when we have configured beacons for specific hosts. In turn, this means we could perform more operations in the same unit of time, by overalapping some DNS lookups and TCP+TLS dials. Additionally, the new design would also work quite well with a DNS resolver that awaits for additional responses after the first one and returns all of them as tactics.
While there, recognize that the HTTPSDialer code and the code in the related structs was a bit more complex than it should be. We don't need to explicitly honor the context when moving data between goroutines as long as the writer goroutines write …
=> refactor(enginenetx): make LookupTactics async

internal/enginenetx/happyeyeballs.go, internal/enginenetx/happyeyeballs_test.go, internal/enginenetx/httpsdialercore.go, internal/enginenetx/httpsdialernull.go, internal/enginenetx/httpsdialerstats.go, internal/enginenetx/network_internal_test.go
* Use 1s as the base delay (which leads to simpler computations)
* Acknowledge that with very large indexes we still need to produce reasonable positive values, while the current algorithm breaks for indexes large than `63`
* Acknowledge that, after incrementing exponentially for a while, it makes sense to continue in a flat fashion, where we increment linearly, while the current algorithm was aiming to always return 30s, which means several attempts would actually run in parallel
* Acknowledge that we should use the same zero for all timings rather than having a goroutine dependent zero
* Acknowledge that for now we don't need to mock `time.Now`
=> fix(enginenetx): stabilize happy eyeballs algorithm

internal/enginenetx/beacons.go, internal/enginenetx/beacons_test.go, internal/enginenetx/httpsdialernull.go, internal/enginenetx/httpsdialernull_test.go, internal/enginenetx/network.go
The beacons policy generates tactics sending on the wire SNI values that should be okay for specific domains.
This policy also uses a fallback policy to generate more standard tactics using the DNS, but those tactics have lower priority meaning that we try using beacons first.
When there is no beacon for a domain, this policy immediately falls back to the underlying fallback policy.
=> feat(enginenetx): introduce beacons policy

internal/enginenetx/beacons.go, internal/enginenetx/beacons_test.go, internal/enginenetx/network.go
Now that we've more or less reached the point where we wanted to be with https://github.com/ooni/probe/issues/2531, let's spend some time to refactor the implementation, now that we know very well how to works, such that modifying it in the future would be easier.
The first order of business here seems to hide implementation details and get rid of too many HTTPSDialer prefixes which only cause confusion when looking at the available structs.
=> refactor(enginenetx): make beacons API private

internal/enginenetx/network_internal_test.go, internal/enginenetx/stats.go, internal/enginenetx/stats_test.go
If an entry is older than one week ago, we remove it from the stats.
This helps ensuring the stats cache does not grow too large.
Additionally, this helps ensuring we are not going to try tactics that worked long time ago and it may be pointless trying now.
=> feat(enginenetx): prune old entries from stats

internal/enginenetx/beacons.go, internal/enginenetx/beacons_test.go, internal/enginenetx/httpsdialer_test.go, internal/enginenetx/httpsdialercore.go, internal/enginenetx/httpsdialernull.go, internal/enginenetx/httpsdialernull_test.go, internal/enginenetx/httpsdialerstatic.go, internal/enginenetx/httpsdialerstatic_test.go, internal/enginenetx/network_test.go, internal/enginenetx/stats.go, internal/enginenetx/stats_test.go
This diff modifies the `HTTPSDialerTactic` struct to store the address and port separately rather than storing the endpoint as the concatenation of the address and the port.
By storing these two fields separately, we're more flexible as we will soon see with subsequent diffs.
=> refactor(enginenetx): store address and port separately

internal/enginenetx/httpsdialercore.go, internal/enginenetx/httpsdialerstatic.go, internal/enginenetx/httpsdialerstatic_test.go, internal/enginenetx/network_test.go, internal/enginenetx/stats.go, internal/enginenetx/stats_test.go
There's no point in grouping tactics by "www.example.com" for stats stored on disk and user-provided static policies. By grouping by domain alone, we'll end up with mixed tactics for different ports all being together. Which means that, code that needs to filter, needs to explicitly filter by port. If we used "www.example.com:443" as the group-by key, conversely, we would not need to write specialized filtering code to only get data for the correct port. So, let's do that and let's simplify future code that will need to get tactics known for work for a given domain _and_ port.
=> refactor(enginenetx): group by domain's endpoint

internal/enginenetx/beacons.go, internal/enginenetx/network.go, internal/enginenetx/network_internal_test.go, internal/enginenetx/network_test.go, internal/enginenetx/static.go, internal/enginenetx/static_test.go, internal/enginenetx/stats.go, internal/enginenetx/stats_test.go
Now that we've more or less reached the point where we wanted to be with https://github.com/ooni/probe/issues/2531, let's spend some time to refactor the implementation, now that we know very well how it works, such that modifying it in the future would be easier.
The first order of business here seems to hide implementation details and get rid of too many HTTPSDialer prefixes which only cause confusion when looking at the available structs.
Here, in particular, we deal with the static-policy API. To this end, we also need to more some tests around because they need internals.
Also, while there, add a top-level description to some files, so that newcomers have an idea of what each file is about.
=> refactor(enginenetx): make static-policy API private

internal/enginenetx/beacons.go, internal/enginenetx/dnspolicy.go, internal/enginenetx/dnspolicy_test.go, internal/enginenetx/httpsdialer.go, internal/enginenetx/httpsdialer_test.go, internal/enginenetx/network.go, internal/enginenetx/network_internal_test.go, internal/enginenetx/static.go, internal/enginenetx/static_test.go, internal/enginenetx/stats.go, internal/enginenetx/stats_test.go
What needs to be public is the network API, while all the rest can and should instead be private.
=> refactor(enginenetx): make https-dialer API private

internal/enginenetx/network.go, internal/enginenetx/statsmanager.go, internal/enginenetx/statsmanager_test.go, internal/enginenetx/statspolicy.go
This commit modifies the https-dialer policy we create to take into account stats to generate tactics. As of this commit, the overall policy is as follows:
1. if `$OONI_HOME/$engine_dir/httpsdialerstatic.conf` exists and contains entries for the endpoint's domain (e.g., "www.example.com:443"), then we unconditionally use it to generate tactics, otherwise;
2. we generate tactics using existing stats and filter only the tactics that are less than one week old (filtering done when loading from the kvstore) and have worked at least once, otherwise;
3. we generate tactics using known beacons and candidate SNIs with the extra caveat that we're not going to generate a tactic we have generate already in the previous step, otherwise;
4. we use whatever resolver is configured to lookup for the …
=> feat(enginenetx): enable the stats-based policy

internal/enginenetx/beaconspolicy.go, internal/enginenetx/dnspolicy.go, internal/enginenetx/httpsdialer.go, internal/enginenetx/httpsdialer_test.go, internal/enginenetx/network.go, internal/enginenetx/staticpolicy.go, internal/enginenetx/staticpolicy_test.go, internal/enginenetx/statsmanager.go, internal/enginenetx/statsmanager_test.go, internal/enginenetx/statspolicy.go, internal/enginenetx/statspolicy_test.go
This diff attempts to improve the code quality of enginenetx by identifying cases where the code could be made to crash with specially written input and adds regress tests and checks to avoid these kind of crashes to happen.
While there, perform a code review and improve comments and naming.
=> chore(enginenetx): more tests and robustness checks

internal/enginenetx/httpsdialer.go, internal/enginenetx/network.go, internal/enginenetx/network_internal_test.go, internal/enginenetx/statsmanager_test.go, internal/enginenetx/userpolicy.go, internal/enginenetx/userpolicy_test.go
This diff modifies how we construct a `*Network` to use a very simple DNS-only policy when using a proxy.
We don't need to try anything fancy when we're using a proxy because we assume the proxy knows how to do circumvention and we don't to get in the proxy way.
While there, recognize that the static policy was named very similarly to the stats policy, so rename the former user policy, such that there is more lexicographical difference.
=> fix(enginenetx): use dns policy with proxy (+renames)

internal/enginenetx/statsmanager.go, internal/enginenetx/statsmanager_test.go, internal/enginenetx/statspolicy.go, internal/enginenetx/statspolicy_test.go
This diff adjusts code inside the enginenetx package such that we gracefully deal with nil values in more cases.
=> fix(enginenetx): gracefully handle more nil cases

internal/enginenetx/network.go, internal/enginenetx/network_internal_test.go, internal/enginenetx/statsmanager.go, internal/enginenetx/statsmanager_test.go, internal/enginenetx/statspolicy.go, internal/enginenetx/statspolicy_test.go
If we're running the enginenetx code inside an environment that sprays ~random IP addresses during DNS lookup, we're going to end up using quite a large amount of statistics. While this amount of statistics could potentially be great in general, we need to be mindful of memory and disk occupation as well as of the overhead of serializing and deserializing.
To address these concerns, add the arbitrary rule that we don't want more than ten domain-endpoint entries and implement code to zap old and/or always-failing entries. The code will run when loading the entries, when serializing them, and periodically while the `*Network` is up and running.
See https://github.com/ooni/probe/issues/2531
=> fix(enginenetx): periodically trim statistics

internal/experiment/tor/tor.go, internal/logx/scrubber.go, internal/netxlite/classify.go, internal/scrubber/scrubber.go, internal/scrubber/scrubber_test.go
This set of changes is the continuation of what I started doing in https://github.com/ooni/probe-cli/commit/4a86c542913a2633bc5a9742a0abc703e5f4071e to revamp out scrubbing capabilities.
Reorganizing tests is pure refactoring. Exposing ScrubBytes is because I think we can rationalize a bit what we scrub on the fly in the `internal/model/archival.go` file and we need to indeed start scrubbing byte arrays.
I'm doing this work as part of https://github.com/ooni/probe/issues/2531
=> refactor(scrubber): reorganize tests and expose ScrubBytes

internal/model/archival.go, internal/model/archival_test.go
There are cases where we know we have binary data in input and we want the output to be binary data using the dictionary encoding like `{"format":"base64","data":"..."}`.
Such cases are, for example, DNS messages bodies.
There is no need for us to pass through the MaybeArchivalBinaryData in such cases. Additionally, this makes MaybeArchivalBinaryData a bit more complex than it probably needs to be.
What's more, ArchivalBinaryData is for when you do not require to scrub the data. I want to introduce new data types that automatically perform scrubbing when they're used.
But this puts even more pressure on MaybeArchivalBinaryData, and hence this commit, to start differentiating between:
1. always binary data vs maybe binary data
2. no scrubbing required vs scrubbing required
The rationale …
=> feat(model): introduce ArchivalBinaryData

internal/model/archival.go, internal/model/archival_test.go
It did not originally occur to me, but now it's clear that we can avoid using a struct to wrap the data type.
It just suffices to use the new type.
I think this is better in terms of writing code because the only two things we need to do are:
1. make sure we have serialization and unserialization tests;
2. use the correct data type in the struct.
For all intents and purposes the ArchivalBinaryData is just a special kind of []byte attached to custom marshal/unmarshal rules.
=> refactor(model): simplify using ArchivalBinaryData

internal/model/archival.go, internal/model/archival_test.go
This type is ~equivalent to ArchivalMaybeBinaryData but designed to hold a string, do less type conversions, and be easier to use.
The intent is to replace the ArchivalMaybeBinaryData type with this type.
For now, let us introduce the new type and its tests.
=> feat: add ArchivalMaybeBinaryString type

internal/model/archival_test.go
My aim here is to have marshal/unmarshal tests for all the toplevel data structures inside the internal/model/archival.go file.
Once I have done that, I can have additional confidence about changing the structure fields and simplifying the code.
All of this is preparatory work to automatically scrub HTTP measurements which is something we should really do before continuing to improve the boostrap process in light of https://github.com/ooni/probe/issues/2531.
I have also added currently skipped tests for other structures as placeholder, but I did not want to submit a too large PR, hence for now we will just have tests for ArchivalDNSLookupResult. More PRs will follow and they will add additional unit tests.
=> chore: write tests for ArchivalDNSLookupResult

internal/model/archival_test.go
My aim here is to have marshal/unmarshal tests for all the toplevel data structures inside the internal/model/archival.go file.
Once I have done that, I can have additional confidence about changing the structure fields and simplifying the code.
All of this is preparatory work to automatically scrub HTTP measurements which is something we should really do before continuing to improve the boostrap process in light of https://github.com/ooni/probe/issues/2531.
=> chore: write tests for ArchivalTCPConnectResult

internal/model/archival_test.go
My aim here is to have marshal/unmarshal tests for all the toplevel data structures inside the internal/model/archival.go file.
Once I have done that, I can have additional confidence about changing the structure fields and simplifying the code.
All of this is preparatory work to automatically scrub HTTP measurements which is something we should really do before continuing to improve the boostrap process in light of https://github.com/ooni/probe/issues/2531.
=> chore: write tests for ArchivalHTTPRequestResult

internal/model/archival_test.go
My aim here is to have marshal/unmarshal tests for all the toplevel data structures inside the internal/model/archival.go file.
Once I have done that, I can have additional confidence about changing the structure fields and simplifying the code.
All of this is preparatory work to automatically scrub HTTP measurements which is something we should really do before continuing to improve the boostrap process in light of https://github.com/ooni/probe/issues/2531.
=> chore: write tests for ArchivalNetworkEvent

internal/model/archival_test.go
We want the tests w/ binary data to make sure we can safely replace model.ArchivalMaybeBinaryData.
We want the tests w/ IP addresses because once we replace the above mentioned type, we'll implement aggressive scrubbing.
=> feat(ArchivalHTTPRequestResult): add tests w/ binary data and IP addrs

internal/experiment/hhfm/hhfm.go, internal/experiment/hhfm/hhfm_test.go, internal/experiment/riseupvpn/riseupvpn.go, internal/experiment/riseupvpn/riseupvpn_test.go, internal/experiment/urlgetter/getter.go, internal/experiment/webconnectivity/httpanalysis.go, internal/experiment/webconnectivity/httpanalysis_test.go, internal/experiment/webconnectivitylte/analysishttpdiff.go, internal/legacy/tracex/archival.go, internal/legacy/tracex/archival_test.go, internal/measurexlite/http.go, internal/measurexlite/http_test.go, internal/model/archival.go, internal/model/archival_test.go
This diff modifies the model for HTTP requests and responses to use the ArchivalBinaryString type to represent bodies.
The tests I have introduced in previous commits are still passing, so we can have good confidence that this change is actually WAI.
=> cleanup(model): use ArchivalMaybeBinaryString for HTTP bodies

internal/experiment/hhfm/hhfm.go, internal/experiment/hhfm/hhfm_internal_test.go, internal/legacy/tracex/archival.go, internal/measurexlite/http.go, internal/model/archival.go, internal/model/archival_test.go
I was trying to make sure the code was using a new definition of headers based on ArchivalMaybeBinaryString, but I stumbled upon a roadblock where there were too many code paths settings headers.
I did not feel comfortable changing multiple code paths, so here is instead a diff that unifies setting headers.
The slightly tricky part of this diff has been the requirement that we preserve headers' capitalization for hhfm. The catch seems to be that we should not use http.Header for setting the headers in hhfm, but rather pass through map[string][]string, which is not attached case normalization setters. I think we're fine in this department because we already had test cases and I added a bunch more test cases.
After this diff is merged, I can resume with my plan to make headers use …
=> cleanup: common funcs for setting headers

internal/experiment/hhfm/hhfm_test.go, internal/experiment/webconnectivity/httpanalysis_test.go, internal/legacy/tracex/archival_test.go, internal/measurexlite/http.go, internal/measurexlite/http_test.go, internal/model/archival.go, internal/model/archival_test.go
This diff modifies the headers-as-a-map representation such that we use ArchivalMaybeBinaryString instead of ArchivalMaybeBinaryData.
The overall idea is to migrate all users of the latter to the former, such that we can remove the latter and implement extra scrubbing for all ArchivalMaybeBinaryString users.
=> cleanup: headers map now uses ArchivalMaybeBinaryString

internal/experiment/hhfm/hhfm_test.go, internal/legacy/tracex/archival.go, internal/legacy/tracex/archival_test.go, internal/measurexlite/http_test.go, internal/model/archival.go, internal/model/archival_test.go
This commit changes the list representation of HTTP headers to use the ArchivalMaybeBinaryString type.
Now that we have migrated most representations of HTTP headers to use this new type, we can finally implement scrubbing.
As a reminder, we still need to migrate the ./legacy/measurex implementation, however that one is a bit annoying because there are no tests at all for measurex 🤦🤦🤦🤦🤦🤦🤦.
That said, given that ./legacy/measurex is deprecated and it is only used by the tor experiment, I think leaving it untouched would probably be the right thing to do here.
=> refactor: use ArchivalMaybeBinaryString for headers list

internal/experiment/hhfm/hhfm.go, internal/experiment/hhfm/hhfm_test.go, internal/experiment/riseupvpn/riseupvpn_test.go, internal/experiment/webconnectivity/httpanalysis_test.go, internal/legacy/tracex/archival.go, internal/legacy/tracex/archival_test.go, internal/measurexlite/http.go, internal/measurexlite/http_test.go, internal/model/archival.go, internal/model/archival_test.go
This commit modifies ArchivalMaybeBinaryData to unconditionally scrub IP addresses and endpoints. It also renames the struct ArchivalScrubbedMaybeBinaryData to underline that it's scrubbing now.
We're using ArchivalScrubbedMaybeBinaryData to represent HTTP headers and bodies collected by OONI measurements.
With this commit merged, I am now much less concerned about the potential unintended effects of aggressively using happy eyeballs, which we started introducing as part of https://github.com/ooni/probe/issues/2531.
In other words, the rest of the refactoring of the OONI bootstrap could proceed a bit faster.
=> feat(archival): unconditionally scrub HTTP headers and bodies

internal/model/http.go, internal/stuninput/stuninput.go
While there, make sure there are no changes in STUN servers.
Part of https://github.com/ooni/probe/issues/2524
=> chore: update the user agent we use

internal/enginenetx/bridgespolicy.go, internal/enginenetx/bridgespolicy_test.go, internal/enginenetx/network.go, internal/enginenetx/statspolicy_test.go, internal/enginenetx/userpolicy.go, internal/enginenetx/userpolicy_test.go
They're quack like bridges, OONI bridges. Also, name the config file from the PoV of the user.
Part of https://github.com/ooni/probe/issues/2531.
=> fix: rename beacons to bridges

internal/logx/operation.go, internal/logx/operation_test.go
Not logging when an operation is starting complicates reasoning about how much time it took to fail, which is something that caused issues investigating https://github.com/ooni/probe/issues/2544.
=> fix(logx): log when an operation is starting

internal/engineresolver/factory.go
By using netxlite.NewHTTPTransportWithOptions in `./internal/engineresolver/factory.go`:
1. we remove an unnecessary usage of the quirky HTTP transport used for measuring by ./legacy/netx et al (removing such unnecessary usages is https://github.com/ooni/probe/issues/2534);
2. we enable using HTTP/HTTPS proxies in miniooni and ooniprobe.
Closes https://github.com/ooni/probe/issues/1955.
=> fix(engineresolver): support HTTP/HTTPS proxies

pkg/oonimkall/taskrunner_test.go
I have ran the test several times locally with `go test -race -count 1` and it was working as intended. Either the CI run issue was just temporary or it's something fundamental of the CI that I can't reproduce.
For this reason, I am going to re-enable the test and see what happens.
Closes https://github.com/ooni/probe/issues/2541
=> chore(oonimkall): re-enable TestTaskRunnerRun

cmd/ooniprobe/internal/nettests/echcheck.go, internal/experiment/echcheck/handshake.go, internal/experiment/echcheck/handshake_test.go, internal/experiment/echcheck/measure.go, internal/registry/factory.go
While there, emit some logs while running it.
While there, make the warning emitted when a nettest is disabled much more specific and informative for the user.
Part of https://github.com/ooni/probe/issues/2547
Part of https://github.com/ooni/probe/issues/2553
=> fix(ooniprobe): make sure we actually run echcheck

internal/experiment/echcheck/handshake.go, internal/registry/factory_test.go, internal/registry/torsf.go
There may be upcoming changes in torsf which may cause it to fail consistently as it occurred during the 3.18 cycle.
Therefore, be defensive and make it disabled by default.
Part of https://github.com/ooni/probe/issues/2553
While there, use slightly better naming for an echcheck function.
=> fix(registry): mark torsf as disabled by default

internal/experiment/riseupvpn/riseupvpn.go, internal/experiment/riseupvpn/riseupvpn_test.go
Removing the summary keys was discussed in https://github.com/ooni/probe-cli/pull/1125 and I'm extracting this diff form such a pull request.
While there, bump the version number for this and other upcoming changes.
---------
Co-authored-by: cyBerta <cyberta@riseup.net>
=> cleanup(riseupvpn): remove summary keys

internal/experiment/riseupvpn/riseupvpn.go, internal/experiment/riseupvpn/riseupvpn_test.go
This diff renames some structs, changes the code emitting the progress, and bumps the experiment version. In my previous commit, I said I did bump the version number but that was not actually the case.
This diff has been extracted from https://github.com/ooni/probe-cli/pull/1125.
This diff is part of https://github.com/ooni/probe/issues/1432
---------
Co-authored-by: cyBerta <cyberta@riseup.net>
=> refactor(riseupvpn): rename structs, change progress, bump version

internal/experiment/riseupvpn/riseupvpn.go, internal/experiment/riseupvpn/riseupvpn_test.go
This diff incorporates part of what has been implemented by @cyBerta in https://github.com/ooni/probe-cli/pull/1125 in response to my review as well as additional changes based on my own feelings about what is correct to do here.
Compared to the original diff, these are the changes that I implemented:
1. I have omitted the work to fetch from riseup geo service and figure out the correct gateways to test. The main reason for not including this body of work has been to reduce the size of the diff and the amount of code to deal with.
2. I modified the logic related to failures in fetching the CA and communicating with riseup services. The test fails immediately if we cannot fetch the proper CA or we cannot contact riseup services. I did not feel comfortable disabling the CA to access riseup …
=> refactor(riseupvpn): handle failing API and simplify test keys

internal/experiment/riseupvpn/riseupvpn.go, internal/progress/progress.go, internal/progress/progress_test.go
This diff modifies riseupvpn to include bootstrap in progress.
We define as riseupvpn's bootstrap the process of fetching the CA and the various JSON files needed to find out the gateways to measure.
I previously stopped including bootstrap in progress in https://github.com/ooni/probe-cli/pull/1363, which I did because the progress was not monotonic.
This diff introduces helpers that make it very obvious to emit monotonic bootstrap through the ./internal/progress package.
This work is part of https://github.com/ooni/probe/issues/1432.
=> feat(riseupvpn): include bootstrap in progress

cmd/ooniprobe/internal/nettests/groups.go
Concludes riseupvpn work for release 3.19.
Reference issue: https://github.com/ooni/probe/issues/2524.
=> chore(ooniprobe): add riseupvpn to experimental test suite

internal/cmd/buildtool/android.go, internal/cmd/buildtool/internal/buildtooltest/buildtooltest.go, internal/cmd/buildtool/ios.go, internal/cmd/buildtool/ios_test.go
We needed to move the runtimex.Assert for darwin, otherwise we cannot run unit tests on linux 😅. While there, be consistent and make sure we avoid panicking on Windows if one runs unit tests there.
Part of https://github.com/ooni/probe/issues/2564
=> chore(buildtool): add ios-build unit tests

internal/registry/factory_test.go, internal/registry/vanillator.go
The reference issue is https://github.com/ooni/probe/issues/2553.
When I implemented the disabled-by-default functionality, I missed that we should also disable-by-default vanilla_tor.
The reason for doing that is that the experiment crashes on Android and possibly iOS due to https://github.com/ooni/probe/issues/2406.
=> fix(registry): disable vanilla_tor by default

internal/dslx/dns.go, internal/dslx/dns_test.go, internal/dslx/quic.go, internal/dslx/quic_test.go, internal/dslx/runtimemeasurex.go, internal/dslx/runtimemeasurex_test.go, internal/dslx/runtimeminimal.go, internal/dslx/runtimeminimal_test.go, internal/dslx/tcp.go, internal/dslx/tcp_test.go, internal/dslx/tls.go, internal/dslx/tls_test.go
Closes https://github.com/ooni/probe/issues/2582
=> cleanup(dslx): use model.UnderlyingNetwork for testing

internal/dslx/http_test.go, internal/dslx/httpcore.go
- avoid storing state for creating an http.Request in httpRequestFunc
- avoid using methods for constructing an http.Request where we can use pure functions instead
- update and adapt the unit test suite
Reference issue: https://github.com/ooni/probe/issues/2612
=> refactor(dslx): prepare for making HTTPRequest stateless

internal/dslx/http_test.go, internal/dslx/httpcore.go, internal/dslx/httpquic.go, internal/dslx/httptcp.go, internal/dslx/httptls.go, internal/dslx/integration_test.go
This diff completes the work described by and closes https://github.com/ooni/probe/issues/2612.
We make the HTTPRequest stateless (use `git diff -w` to avoid noise caused by whitespace changes).
We rename HTTPTransport to HTTPConnection since that is a better name.
We make HTTPConnection adapters stateless as well.
=> refactor(dslx): finish making funcs stateless

internal/dslx/dns.go, internal/dslx/dns_test.go, internal/dslx/fxasync.go, internal/dslx/fxasync_test.go, internal/dslx/fxcore.go, internal/dslx/fxcore_test.go, internal/dslx/fxgen.go, internal/dslx/http_test.go, internal/dslx/httpcore.go, internal/dslx/httpquic.go, internal/dslx/httptcp.go, internal/dslx/httptls.go, internal/dslx/integration_test.go, internal/dslx/quic.go, internal/dslx/quic_test.go, internal/dslx/tcp.go, internal/dslx/tcp_test.go, internal/dslx/tls.go, internal/dslx/tls_test.go, internal/tutorial/dslx/chapter02/README.md, internal/tutorial/dslx/chapter02/main.go
Closes https://github.com/ooni/probe/issues/2613
=> refactor(dslx): pass Maybe[T] to Func.Apply

internal/dslx/dns.go, internal/dslx/fxcore.go, internal/dslx/fxcore_test.go, internal/dslx/httpcore.go, internal/dslx/httpquic.go, internal/dslx/httptcp.go, internal/dslx/httptls.go, internal/dslx/quic.go, internal/dslx/tcp.go, internal/dslx/tls.go
This diff contains cleanups in dslx after we modified Func.Apply to take a Maybe[T] as input:
- we don't need anymore to record the failed operation because we can compute that inline, given that now we can write post-operation filters that observe whether the operation failed or succeeded;
- likewise, we don't need to use counters anymore;
- likewise, we can remove functions to inspect the first error, because we can compute that inline.
The reference issue is https://github.com/ooni/probe/issues/2613.
=> dslx: post-Func.Apply(Maybe[T])-introduction cleanups

internal/dslx/dns.go, internal/dslx/fxcore.go, internal/dslx/fxcore_test.go, internal/dslx/httpcore.go, internal/dslx/httpquic.go, internal/dslx/httptcp.go, internal/dslx/httptls.go, internal/dslx/quic.go, internal/dslx/tcp.go, internal/dslx/tls.go, internal/tutorial/dslx/chapter02/README.md, internal/tutorial/dslx/chapter02/main.go
I forgot to commit this diff as part of https://github.com/ooni/probe-cli/pull/1383.
Doing it now.
Reference issue: https://github.com/ooni/probe/issues/2614.
=> fix(dslx): remove Observations from Maybe

internal/dslx/dns.go, internal/dslx/dns_test.go, internal/dslx/fxcore.go, internal/dslx/http_test.go, internal/dslx/httpcore.go, internal/dslx/httpquic.go, internal/dslx/httptcp.go, internal/dslx/httptls.go, internal/dslx/quic.go, internal/dslx/quic_test.go, internal/dslx/tcp.go, internal/dslx/tcp_test.go, internal/dslx/tls.go, internal/dslx/tls_test.go
Closes https://github.com/ooni/probe/issues/2615
=> refactor(dslx): type Operation func(context, A) (B, error)

internal/dslx/address.go, internal/dslx/dns.go, internal/dslx/dns_test.go, internal/dslx/qa_test.go
Closes https://github.com/ooni/probe/issues/2617
While there: there's no need to return the Trace used for DNS lookup and there's no meaning in aggregating traces when running DNSLookupParallel, because we have multiple traces, so let's just drop ResolvedAddresses.Trace.
=> feat(dslx): implement DNSLookupParallel

internal/experiment/signal/signal.go, internal/experiment/signal/signal_test.go
Signal has made changes to their endpoints. In this PR we drop a legacy endpoint and add more of the endpoints communicated to us by the signal devs.
=> Update signal test endpoints fixes probe/2627

internal/experiment/webconnectivitylte/cleartextflow.go, internal/experiment/webconnectivitylte/secureflow.go, internal/experiment/webconnectivitylte/testkeys.go
The new name is more accurate because we need to prepend to requests such that the last request ends up being first in the list.
Part of https://github.com/ooni/probe/issues/2634
=> refactor(webconnectivitylte): {Append,Prepend}Requests

internal/experiment/webconnectivitylte/cleartextflow.go, internal/experiment/webconnectivitylte/secureflow.go
We're not saving "connect" network events when TCP connect fails. This diff fixes the codebase so that we always save these events.
Fix extracted from https://github.com/ooni/probe-cli/pull/1392.
Reference issue https://github.com/ooni/probe/issues/2634.
=> fix(webconnectivitylte): always save "connect" network events

internal/experiment/webconnectivitylte/cleartextflow.go, internal/experiment/webconnectivitylte/secureflow.go
Extracted from https://github.com/ooni/probe-cli/pull/1392.
Part of https://github.com/ooni/probe/issues/2634.
=> chore(webconnectivitylte): sync {cleartext,secure}flow.go

internal/minipipeline/analysis.go, internal/minipipeline/httpdiff.go, internal/minipipeline/utils.go
Part of https://github.com/ooni/probe/issues/2634
=> cleanup(minipipeline/analysis): move utilities in other files

internal/experiment/signal/signal.go, internal/experiment/signal/signal_test.go
This diff trims down the endpoints tested by signal to avoid the possibility of future churn.
=> fix(signal): trim down tested endpoints

internal/ooapi/checkin.go, internal/ooapi/checkin_test.go, pkg/oonimkall/session.go
While there, make sure we log the check-in request and response with `-v`, because otherwise 🤌🤌🤌🤌. (On this note, we did not want to log psiphon and tor configs, but we're not using check-in for them anymore, so this switch from not logging to logging seems indeed to be reasonably okay to do. We need /api/v1/register and /api/v1/login before serving config. Additionally, it seems having experiment-specific APIs is actually more flexible anyway.)
Part of https://github.com/ooni/probe/issues/2644.
=> fix(oonimkall): make sure SoftwareName is set

internal/cmd/miniooni/oonirun.go, internal/registry/factory.go, internal/registry/factory_test.go
This commit ensures we can parse integer values provided using OONI Run v2 descriptors into actual integers.
Values are originally parsed as float64, so we need to add a specific conversion case for that scenario.
Diff extracted from: https://github.com/ooni/probe-cli/pull/1423
Closes https://github.com/ooni/probe/issues/2645
=> fix: make sure we can parse integers from JSON

internal/oohelperd/dns.go, internal/oohelperd/handler.go, internal/oohelperd/handler_test.go, internal/oohelperd/http.go, internal/oohelperd/metrics.go, internal/oohelperd/tcptls.go
This diff makes oohelperd more robust against overload and introduces additional prometheus metrics.
=> feat(oohelperd): protect against overload and add metrics

.github/workflows/libtorlinux.yml, internal/libtor/enabled.go, internal/libtor/enabled_test.go
This PR is about preventing concurrent `./internal/libtor` instances. The `./internal/libtor` package links with `libtor.a` and runs `tor_run_main`. The expectation of such a function is that a single thread can execute within the same process. If we attempt to invoke `tor_run_main` while another instance is running, this is most likely going to cause memory corruption because the two instances try to operate on the same static data structures.
To address this issue, we use atomic compare and swap and atomic set to make sure there is just a single thread inside the "critical section" consisting of calling `tor_run_main`. All the other threads would fail with an error.
To test this branch on Linux, you need to run:
```sh
go run ./internal/cmd/buildtool linux cdeps zlib openssl libevent tor …
```
=> fix(libtor): prevent concurrent instances

internal/minipipeline/analysis.go, internal/minipipeline/analysis_test.go, internal/minipipeline/httpdiff_test.go, internal/minipipeline/observation_test.go, internal/minipipeline/utils.go, internal/minipipeline/utils_test.go
I spent some time increasing code coverage for `internal/minipipeline`.
This is KTLO work as part of https://github.com/ooni/probe/issues/2640.
=> chore(minipipeline): increase code coverage

internal/experiment/webconnectivitylte/analysisclassic.go, internal/experiment/webconnectivitylte/analysisext.go, internal/experiment/webconnectivitylte/analysishttpdiff.go, internal/experiment/webconnectivitylte/testkeys.go
Use a single algorithm for determining whether there's HTTP diff. We can do this by migrating the HTTP diff flags to use `optional.Value` and then we can always use code written for the "ext" sub-engine to do that.
Part of https://github.com/ooni/probe/issues/2640
=> cleanup(webconnectivitytle): avoid code duplication

internal/experiment/webconnectivitylte/analysisclassic.go, internal/experiment/webconnectivitylte/analysisext.go, internal/experiment/webconnectivityqa/badssl.go, internal/experiment/webconnectivityqa/dnsblocking.go, internal/experiment/webconnectivityqa/ghost.go, internal/experiment/webconnectivityqa/testcase.go, internal/experiment/webconnectivityqa/websitedown.go
This commit modifies webconnectivitylte to handle ghost DNS censorship.
We define ghost DNS censorship the case where the original domain does not exist anymore but the censor continues to return an IP address for the original domain nonetheless.
We used to have null-null handling for this case in the "orig" engine and a reference issue as https://github.com/ooni/probe/issues/2307.
With this commit, we modify the "classic" engine to correctly handle this case.
To this end, we need to:
1. mark DNS inconsistency when we have successful probe lookups and no IP address has been resolved by the test helper, which is indeed the case of ghost DNS censorship.
2. specific handling on the case in which the website seems down where we also ask ourselves the question of whether the culprit could be …
=> feat(webconnectivitylte): handle ghost DNS censorship

internal/cmd/oohelper/oohelper.go, internal/enginelocate/iplookup.go, internal/netemx/example_test.go, internal/netemx/http3_test.go, internal/netemx/oohelperd.go, internal/netxlite/http3.go, internal/netxlite/http3_test.go, internal/netxlite/httpquirks.go, internal/netxlite/httpquirks_test.go, internal/oohelperd/handler.go
This diff modifies netxlite such that the oohelperd only depends on a netxlite.Netx instance.
The overall goal here is to refactor `oohelperd` to only depend on `netxlite.Netx` such that we can remove the code duplication between how we instantiate `oohelperd.Handler` in `oohelperd` and how we instantiate it inside `netemx`.
In turn, by doing this, we would ensure we have the same `oohelperd` behavior for QA and production.
In turn, with this guarantee, we can write QA tests that ensure we're correctly dealing with 127.0.0.1.
The reference issue is https://github.com/ooni/probe/issues/1517.
=> refactor(oohelperd): depend on netxlite.Netx only

internal/cmd/oohelperd/main.go, internal/netemx/oohelperd.go, internal/oohelperd/handler.go, internal/oohelperd/handler_test.go
This diff modifies how we construct oohelperd.Handler inside the oohelperd package and inside the netemx package such that we're now constructing using equivalent code. We know that construction is equivalent for HTTP clients because previosuly we made sure it was the case in https://github.com/ooni/probe-cli/pull/1464.
So, the next step would be removing the custom construction code inside of netemx and always use oohelperd.NewHandler.
In turn, by doing this, we would ensure we have the same `oohelperd` behavior for QA and production.
In turn, with this guarantee, we can write QA tests that ensure we're correctly dealing with 127.0.0.1.
The reference issue is https://github.com/ooni/probe/issues/1517.
=> refactor(oohelperd,netmx): reduce construction diff to zero

internal/netemx/oohelperd.go, internal/oohelperd/handler.go, internal/oohelperd/handler_test.go, internal/oohelperd/measure.go
In https://github.com/ooni/probe-cli/pull/1467 we made the netemx constructor for oohelperd.Handler equivalent to oohelperd.NewHandler.
So, now it becomes possible to always use oohelperd.NewHandler.
While there, notice that we can make all the Handler fields private because there's no need to share them anymore, so do that.
Having done this, we are now sure we have the same `oohelperd` behavior for QA and production.
In turn, with this guarantee, we can write QA tests that ensure we're correctly dealing with 127.0.0.1.
The reference issue is https://github.com/ooni/probe/issues/1517.
=> refactor(netemx,oohelperd): use oohelperd.NewHandler constructor

internal/cmd/buildtool/android_test.go, internal/cmd/buildtool/cdepszlib.go, internal/cmd/buildtool/ios_test.go, internal/cmd/buildtool/linuxcdeps_test.go
Bump to the latest zlib published version. Fixes `cmd/buildtool` tests at https://github.com/ooni/probe-cli/actions/runs/7644312040/job/20828352810
Closes https://github.com/ooni/probe/issues/2660
=> chore: use latest zlib version published (1.3.1)

Readme.md
It seems better to have a direct link. Based on a discussion with @agrabeli.
=> doc(Readme.md): add link to miniooni

internal/experiment/webconnectivityqa/redirect.go, internal/experiment/webconnectivityqa/testcase.go, internal/netemx/address.go, internal/netemx/httpbin.go, internal/netemx/httpbin_test.go, internal/netemx/scenario.go, internal/netemx/yandex.go
This PR improves webconnectivityqa to reproduce the https://github.com/ooni/probe/issues/2628 issue.
We model the v0.4 behavior as the correct behavior. We need to extend webconnectivitylte to correctly handle this case.
=> chore(webconnectivityqa): reproduce ooni/probe#2628 issue

internal/logmodel/logmodel.go, internal/logx/operation.go, internal/logx/prefix.go, internal/logx/scrubber.go, internal/model/logger.go, internal/must/must.go, internal/shellx/shellx.go, internal/shellx/shellx_test.go, script/nocopyreadall.bash
See https://github.com/ooni/probe/issues/2664
=> chore(buildtool): support go1.18+

.github/workflows/gofixpath.yml, internal/cmd/buildtool/gofixpath.go, script/go.bash, script/internal/go.bash
This wrapper invokes buildtool's gofixpath to ensure we end up executing the correct version of golang.
Part of https://github.com/ooni/probe/issues/2664.
=> feat(buildtool): introduce script/go.bash wrapper

internal/database/actions_test.go, internal/experiment/webconnectivitylte/analysisclassic.go, internal/experiment/webconnectivitylte/summary.go, internal/experiment/webconnectivitylte/summary_test.go, internal/experiment/webconnectivitylte/testkeys.go
Closes https://github.com/ooni/probe/issues/2667.
While there, repair flaky unit test and explain why it was flaky.
=> feat(webconnectivitylte): wire-in SummaryKeys

internal/experiment/webconnectivitylte/cleartextflow.go, internal/experiment/webconnectivitylte/secureflow.go, internal/x/dslvm/quic.go, internal/x/dslvm/tcp.go, internal/x/dslx/quic.go, internal/x/dslx/tcp.go
There's no need to use the older NewHTTPTransport factory for creating a new HTTP transport, because this codebase doesn't need to use any quirk implemented by such a transport.
While there, move TODOs around the codebase.
Part of https://github.com/ooni/probe/issues/2669.
=> refactor(webconnectivitylte): use NewHTTPTransportWithOptions

internal/experiment/webconnectivitylte/cleartextflow.go, internal/experiment/webconnectivitylte/secureflow.go
Part of https://github.com/ooni/probe/issues/2669
=> doc(webconnectivitylte): clarify http_transaction_{start,end} semantics

go.mod, go.sum, internal/experiment/webconnectivitylte/dnswhoami.go, internal/webconnectivityalgo/dnswhoami.go, internal/webconnectivityalgo/dnswhoami_test.go
Part of https://github.com/ooni/probe/issues/2669
=> feat(webconnectivityalgo): test DNSWhoamiService

internal/webconnectivityalgo/dnswhoami.go, internal/webconnectivityalgo/dnswhoami_test.go
Because the singleton is always active, we need to expire the cache otherwise we don't catch changes in the client network.
Part of https://github.com/ooni/probe/issues/2669
Closes https://github.com/ooni/probe/issues/2671
=> fix(DNSWhoamiService): implement cache expiration

internal/experiment/webconnectivitylte/dnsresolvers.go, internal/experiment/webconnectivitylte/measurer.go, internal/experiment/webconnectivitylte/summary.go, internal/netemx/address.go, internal/netemx/example_test.go, internal/netemx/scenario.go, internal/webconnectivityalgo/dnsoverudp.go, internal/webconnectivityalgo/dnsoverudp_test.go, internal/x/dslx/qa_test.go
Using one resolver at random from a pool of some has been requested by users.
While there link all the remaining TODOs to existing open issues.
Closes https://github.com/ooni/probe/issues/2669.
Here are three measurements showcasing this new feature:
1. [using 1.0.0.1:53](https://explorer.ooni.org/m/20240208153440.990674_IT_webconnectivity_646b76338342a1a8)
2. [using 1.1.1.1:53](https://explorer.ooni.org/m/20240208154552.863516_IT_webconnectivity_97c3ed1a6bbebd5e)
3. [using 9.9.9.9:53](https://explorer.ooni.org/m/20240208154616.549959_IT_webconnectivity_2515d794df2ebd34)
=> feat(webconnectivitylte): use random DNS-over-UDP resolver

CDEPS/tor/004.patch, internal/cmd/buildtool/android_test.go, internal/cmd/buildtool/cdepstor.go, internal/cmd/buildtool/ios_test.go, internal/cmd/buildtool/linuxcdeps_test.go
Closes https://github.com/ooni/probe/issues/2651
=> fix(CDEPS/tor): allow compiling under ArchLinux

internal/experiment/webconnectivitylte/cleartextflow.go, internal/experiment/webconnectivitylte/secureflow.go, internal/webconnectivityqa/badssl.go, internal/webconnectivityqa/checker.go, internal/webconnectivityqa/checker_test.go, internal/webconnectivityqa/cloudflare.go, internal/webconnectivityqa/control.go, internal/webconnectivityqa/dnsblocking.go, internal/webconnectivityqa/dnshijacking.go, internal/webconnectivityqa/dnshijacking_test.go, internal/webconnectivityqa/ghost.go, internal/webconnectivityqa/ghost_test.go, internal/webconnectivityqa/httpblocking.go, internal/webconnectivityqa/httpdiff.go, internal/webconnectivityqa/idna.go, internal/webconnectivityqa/largefile.go, internal/webconnectivityqa/localhost.go, internal/webconnectivityqa/localhost_test.go, internal/webconnectivityqa/redirect.go, internal/webconnectivityqa/run.go, internal/webconnectivityqa/run_test.go, internal/webconnectivityqa/success.go, internal/webconnectivityqa/tcpblocking.go, internal/webconnectivityqa/testcase.go, internal/webconnectivityqa/testkeys.go, internal/webconnectivityqa/throttling.go, internal/webconnectivityqa/tlsblocking.go, internal/webconnectivityqa/websitedown.go, internal/webconnectivityqa/websitedown_test.go
While there, notice that we can increase the coverage in webconnectivityqa.
Closes https://github.com/ooni/probe/issues/2674
=> fix(webconnectivitylte): include network events

internal/cmd/gardener/internal/dnsreport/dnsreport.go, internal/cmd/gardener/internal/sync/sync.go, internal/cmd/gardener/internal/sync/sync_test.go, internal/cmd/gardener/main.go, internal/fsx/fsx.go
We use a database to keep measurements results to allow to interrupt and resume the work, given that we have thousands or URLs to vet. However, after a week, the database is most likely stale, so let's just avoid trusting and start afresh in such a case. It's reasonable to assume that the database is stale after such an interval because the URL's status may have changed (e.g., some URLs could have stopped working).
Additionally, every time we run `gardener sync` we most likely have new URLs, so we need to do one of the following:
1. merge new URLs into the database;
2. just zap the database and start afresh.
Because doing 1. would be a bit time consuming, for now I am opting for doing 2. and we'll implement 1. if needed.
Closes https://github.com/ooni/probe/issues/2684.
=> fix(gardener): avoid issues caused by stale databases

Dockerfile.oonith, internal/cmd/oohelperd/main.go, oonith/Makefile, oonith/buildspec.yml
We implement the following changes:
* Move prometheus metric behind HTTP basic auth
* Read the prometheus password from the `PROMETHEUS_METRICS_PASSWORD` environment variable like we do for ooniapi-services
* Add Dockerfile to build oohelpderd
* Add codepipeline buildspec for oonihelpderd
=> oohelperd: move prometheus metrics behind HTTP basic auth + docker image build + codepipeline buildspec

internal/experiment/tlsmiddlebox/measurer.go, internal/experiment/tlsmiddlebox/measurer_test.go, internal/experiment/tlsmiddlebox/syscall_unix.go, internal/experiment/tlsmiddlebox/syscall_windows.go
To set Hop Limit (IPv6) , we should set `IPV6_UNICAST_HOPS` option instead of `IP_TTL`.
=> fix(tlsmiddlebox): if RemoteAddr is IPv6 set IPV6_UNICAST_HOPS

.github/workflows/go1.22.yml, .github/workflows/gobash.yml, pkg/gobash/version.go
See https://github.com/ooni/probe-cli/security/code-scanning/12
While there, make sure we run tests using go1.22, which has been released in February while I was on leave.
=> fix(pkg/gobash/version.go): validate zip files content

CONTRIBUTING.md, docs/releasing.md
Closes https://github.com/ooni/probe/issues/2698
=> doc: document the release process

cmd/ooniprobe/internal/cli/geoip/geoip.go, cmd/ooniprobe/internal/nettests/run.go, cmd/ooniprobe/internal/ooni/ooni.go, cmd/ooniprobe/internal/oonitest/oonitest.go, internal/engine/inputloader.go, internal/engine/session.go, internal/engine/session_integration_test.go, internal/experiment/webconnectivity/webconnectivity_test.go
Let's just always use MaybeLookupLocationContext and MaybeLookupBackendsContext. This change simplifies the interaction graph related to using the probeservices and more generally the engine.
Part of https://github.com/ooni/probe/issues/2700
=> cleanup(engine): remove redundant APIs

internal/engine/session.go, pkg/oonimkall/session.go, pkg/oonimkall/session_integration_test.go
Potentially, this code would cause a behavioral change in that once the probe location has been found, it would not change again and it might be a problem for very-long-running sessions.
However:
1. the Android codebase does not keep a reference to a session for a very long time and anyway the longest-running sessions are those used for running experiments;
2. the correct behavior would be for MaybeLookupLocationContext to cache the results only for a limited amount of time.
Because of all these considerations, it actually makes sense to say that replacing LookupLocationContext with MaybeLookupLocationContext and engine.Session accessors is the ~same.
The net benefit for us is that we can further reduce the surface of interaction between clients and the engine code. A simpler API surface …
=> cleanup(engine): do not expose LookupLocationContext

internal/engine/inputloader.go, internal/engine/inputloader_test.go, internal/engine/session.go, internal/engine/session_integration_test.go, internal/engine/session_internal_test.go, internal/engine/session_nopsiphon.go, internal/mocks/session.go, internal/mocks/session_test.go, pkg/oonimkall/session.go
We don't need an indirect call through (*Session).NewProbeServicesClient as long as we modify the value returned by CheckIn to be the full check-in response rather than being just the response's .Test field.
Part of https://github.com/ooni/probe/issues/2700
=> cleanup(oonimkall): use (*Session).CheckIn directly

internal/oohelperd/handler.go, internal/oohelperd/handler_test.go
This diff adds a `GET` response for the oohelperd service which passes as a health check in the AWS codepipeline while spinning up targets
=> feat: add health check response for oohelperd

pkg/oonimkall/httpx.go, pkg/oonimkall/httpx_test.go
Closes: https://github.com/ooni/probe/issues/2701
=> fix(oonimkall.HTTPRequest): `URL` => `Url` to fix iOS

internal/experiment/webconnectivitylte/analysisclassic.go, internal/experiment/webconnectivitylte/cleartextflow.go, internal/experiment/webconnectivitylte/measurer.go, internal/experiment/webconnectivitylte/redirects.go, internal/experiment/webconnectivitylte/redirects_test.go, internal/experiment/webconnectivitylte/secureflow.go, internal/netemx/httpbin.go, internal/netemx/httpbin_test.go, internal/webconnectivityqa/redirect.go, internal/webconnectivityqa/testcase.go
Closes https://github.com/ooni/probe/issues/2685
=> fix(webconnectivitylte): handle too many redirects

internal/measurexlite/conn.go, internal/measurexlite/conn_test.go
Closes https://github.com/ooni/probe/issues/2707
=> fix(measurexlite): add robust RemoteAddr accessors

docs/releasing.md, internal/experiment/tlsmiddlebox/syscall_unix.go, internal/experiment/tlsmiddlebox/syscall_windows.go, internal/webconnectivityalgo/calltesthelpers_test.go
Part of https://github.com/ooni/probe/issues/2722
=> chore: minor changes before alpha release

cmd/ooniprobe/internal/cli/rm/rm.go
I manually tested the cli and concluded that it's too easy to reach the panic caused by runtimex.Try0 over there and it would expose panics to users too frequently.
Let's just convert those into normal error checks. Here is what we would previously get:
```
% ./ooniprobe rm
? Are you sure you wish to delete the result #0  [Use arrows to move, type to filter]
true
> false
panic: Try0: interrupt
[...]
```
So, here I just pressed ^D and got a panic. Ouch!
After the diff, we have this:
```
% ./ooniprobe rm
? Are you sure you wish to delete the result #0 false
⨯ failure in main command   error=canceled by user
```
and:
```
% ./ooniprobe rm --all
? Are you sure you wish to delete ALL results false
⨯ failure in main command   error=canceled by user
```
It seems much better, isn't it?
Part of the …
=> fix(cli/rm/rm.go): using panic is not user friendly

internal/engine/experiment.go, internal/experiment/dnscheck/dnscheck_test.go, internal/experiment/dnsping/dnsping_test.go, internal/experiment/psiphon/psiphon_test.go, internal/experiment/quicping/quicping_test.go, internal/experiment/simplequicping/simplequicping_test.go, internal/experiment/sniblocking/sniblocking.go, internal/experiment/sniblocking/sniblocking_test.go, internal/experiment/stunreachability/stunreachability_test.go, internal/experiment/tcpping/tcpping_test.go, internal/experiment/tlsmiddlebox/measurer_test.go, internal/experiment/tlsping/tlsping_test.go, internal/inputparser/inputparser.go, internal/inputparser/inputparser_test.go, internal/model/experiment.go, internal/model/measurement.go, internal/model/measurement_test.go, internal/oonirun/inputprocessor_test.go, internal/webconnectivityqa/measurement.go
While starting to work on richer input, I realised that it would be very handy to reserve the name "target" to describe a richer input target as the tuple containing options and some input.
However, using such a naming would ~clash with the definition of MeasurementTarget, which is a string definition that is only there to say semantically that the Input field of a measurement is the "thing" that we measure, as well as to apply a specific JSON serialization policy that is consistent with the historical behavior of OONI Probe.
Therefore, for making semantic space for a richer input target, I am going to refactor MeasurementTarget to be MeasurementInput.
No functional change.
Part of https://github.com/ooni/probe/issues/2607.
=> refactor: MeasurementTarget -> MeasurementInput

CODEOWNERS
This commit adds @DecFox as a code owner for the probe-cli repository.
=> CODEOWNERS: add @DecFox

internal/engine/experiment.go
This diff refactors *engine.experiment to make the report field goroutine safe. It also moves at the bottom of experiment.go code that was intermixed with *engine.experiment methods.
Part of https://github.com/ooni/probe/issues/2607
=> refactor(experiment): make report goroutine safe

internal/engine/experiment.go, internal/mocks/experiment.go, internal/mocks/experiment_test.go, internal/model/experiment.go, internal/oonirun/experiment.go, internal/oonirun/experiment_test.go, internal/oonirun/inputprocessor.go, internal/oonirun/inputprocessor_test.go, internal/oonirun/v1_test.go, internal/oonirun/v2_test.go
We originally developed asynchronous experiments as a mean to support websteps, a nettest that returned more than one measurement per invocation of its Measure method.
Since then, we removed websteps. Therefore, this code is currently technically unused. Additionally, this code further complicates implementing richer input, because it is another way of performing measurements.
As such, in the interest of switfly moving forward with richer input _and_ of simplifying the engine, we are now removing this unused functionality from the tree.
While there, better the documentation of OnProgress and undeprecate functions to open/close reports since it's clear that, for now, using a submitter in cmd/ooniprobe is a bit of a stretch given our current goals. So, it feels best to avoid deprecating …
=> cleanup: remove asynchronous experiments

docs/design/dd-008-richer-input.md, internal/experiment/dnscheck/dnscheck.go, internal/experiment/dnscheck/dnscheck_test.go, internal/targetloading/targetloading.go
Closes https://github.com/ooni/probe/issues/2753
=> fix(dnscheck): gracefully cast to Target

pkg/oonimkall/taskrunner_test.go
This diff, which is part of https://github.com/ooni/probe/issues/2752, prints the event occurring when testing, which is useful for me to better understand what is going on while changing the package.
Extracted from https://github.com/ooni/probe-cli/pull/1620.
=> chore(oonimkall): log the events when testing

internal/engine/session.go, internal/experiment/dnscheck/dnscheck_test.go, internal/experiment/openvpn/endpoint.go, internal/experiment/openvpn/endpoint_test.go, internal/experiment/openvpn/openvpn.go, internal/experiment/openvpn/openvpn_test.go, internal/experiment/openvpn/richerinput.go, internal/experiment/openvpn/richerinput_test.go, internal/model/experiment.go, internal/registry/openvpn.go, internal/targetloading/targetloading.go, internal/targetloading/targetloading_test.go
This commit:
1. modifies `./internal/registry` and its `openvpn.go` file such that `openvpn` has its own private target loader;
2. modifies `./internal/experiment/openvpn` to use the richer input targets to merge the options for the openvpn experiment.
3. removes cache from session after fetching openvpn config
=> feat(openvpn): implement richer input

internal/engine/experimentbuilder.go, internal/engine/experimentbuilder_test.go, internal/mocks/experimentbuilder.go, internal/mocks/experimentbuilder_test.go, internal/model/experiment.go, internal/oonirun/experiment.go, internal/oonirun/experiment_test.go, internal/oonirun/v1_test.go, internal/oonirun/v2.go, internal/oonirun/v2_test.go, internal/registry/factory.go, internal/registry/factory_test.go, internal/registry/portfiltering.go, internal/registry/telegram.go, internal/registry/webconnectivity.go
Closes https://github.com/ooni/probe/issues/2759
=> feat(oonirun): allow true JSON richer input

pkg/oonimkall/taskrunner_test.go
This diff contains a trivial rename of fakeSuccessfulRun back to fakeSuccessfulDeps. I made the rename from Deps to Run in a previous commit, but now I realize it was a mistake.
Because this is a trivial patch generated with a tool, I am going to self merge it w/o review.
Part of https://github.com/ooni/probe/issues/2752.
=> refactor(oonimkall): fakeSuccessful{Run => Deps}

.github/workflows/build_docs.yml, .gitignore, script/build_docs.sh
This diff moves assets used in docs to `src/assets` in `ooni/docs` and also replaces the doc references in markdown files to the appropriate location.
=> Start working on fixing image paths

internal/experiment/openvpn/openvpn.go, internal/experiment/openvpn/openvpn_test.go, internal/experiment/openvpn/richerinput_test.go, internal/model/archival.go
Add `bootstrap_time` as a top-level test-key, making OpenVPN nettest conforming to `df-009-tunnel`. It also adds  `tunnel` and `failure` keys with the semantics declared in that spec.
=> feat(openvpn): add a top-level test key with bootstrap time and handshake failure

docs/design/dd-008-richer-input.md, internal/registry/dnscheck.go
This diff refactors the dnscheck factory to use the default target loader
=> refactor: remove dnscheck loader

internal/experiment/openvpn/endpoint.go, internal/experiment/openvpn/openvpn.go, internal/experiment/openvpn/openvpn_test.go, internal/experiment/openvpn/richerinput.go, internal/experiment/openvpn/richerinput_test.go, internal/experiment/openvpn/targets.go, internal/experiment/openvpn/targets_test.go
changing the experiment as per request, to satisfy reqs for shipping the experiment in time for Aug 2024 release.
Initially I had some concerns about this approach, but it seems to work as long it's ensured that the server has `duplicate-cn` key in its config.
For what we saw from real-data, the order of magnitude of expected probes executing the experimental card is in the range of 100 per period of 5 minutes.
=> hardcode openvpn endpoints under ooni infra

go.mod, go.sum
This diff updates the `go.mod` file to point to the latest [staging-client](https://github.com/Psiphon-Labs/psiphon-tunnel-core/tree/staging-client) commit for psiphon
=> chore: updated psiphon dependency to latest commit

internal/testingx/oonibackendwithlogin.go
This diff addresses gosec warnings and tries to minimise them as much as possible. The gosec warnings for the current `master` branch can be found here: https://github.com/ooni/probe-cli/actions/runs/10286957901/job/28468879578#step:6:1153.
=> chore: address gosec warnings

internal/version/version.go
This diff sets the engine version to the latest `3.23.0` version in the `release/3.23` branch
=> chore: set engine version to v3.23.0

internal/experiment/dnscheck/richerinput.go, internal/registry/dnscheck.go
This re-instates the richer input loader for dnscheck which was disabled as part of `release v3.23`. It also updates the dnscheck input list to include all experiment targets. In the future, we'll be serving these targets using a backend API.
Fixes https://github.com/ooni/probe/issues/2799
=> fix(dnscheck): reinstate richer input loader

internal/registry/echcheck.go, internal/registry/factory_test.go
Closes: https://github.com/ooni/probe/issues/2807
=> Fix missing enabledByDefault in echcheck

internal/experiment/echcheck/handshake.go, internal/experiment/echcheck/measure.go, internal/experiment/echcheck/measure_test.go, internal/model/archival.go
Changes to the ECHCheck experiment.
* Replace default URL with cloudflare-ech.com
* Add support for performing an additional ECH handshake with a different ClientHelloOuter SNI
* Randomize the order of the handshakes
=> Switch to using cloudflare-ech.com as the target for the ech test

pkg/oonimkall/session.go
This diff exposes the `Session.Close` call for the geoip session we initialize in the mobile app. This is required to close the circumvention tunnel before we use start another tunnel as part of the async tasks to run the experiments.
=> refactor(oonimkall): expose the session close call

internal/experiment/dnscheck/richerinput.go
Trim down the dnscheck list.
Keep only 2 addresses per providers (http3 enabled and not), since measuring the ads or malware blocking endpoints is less important (we only query example.com). The main difference for the malware blocking endpoints would be that the SNI is different, but we can probably generate similar telemetry without doing a full DoH measurement.
=> Simplify the dnscheck list

go.mod, go.sum, internal/experiment/openvpn/endpoint.go, internal/experiment/openvpn/openvpn.go, internal/experiment/openvpn/openvpn_test.go, internal/experiment/openvpn/richerinput.go, internal/experiment/openvpn/richerinput_test.go, internal/experiment/openvpn/targets.go, internal/experiment/openvpn/targets_test.go
while working on this, I also gave more priority to possible oonirun descriptors passed in the command line.
- Related: #2805
Add fallback domains for openvpn default endpoints to be probed.
=> feat: add fallback domain names for openvpn experiment

internal/experiment/dnscheck/richerinput_test.go
This fixes the dnscheck default input test observed failing here: https://github.com/ooni/probe-cli/actions/runs/12016869033/job/33497976676#step:5:536.
=> fix: dnscheck default input test

internal/experiment/echcheck/measure_test.go
Bring the measure_test.go version in line with measure.go version.
This should make *unit tests* green again.
=> fix(echcheck): bump version number in tests

cmd/ooniprobe/internal/nettests/nettests.go, internal/cmd/oonireport/oonireport.go, internal/engine/experiment.go, internal/engine/experiment_integration_test.go, internal/mocks/experiment.go, internal/mocks/experiment_test.go, internal/mocks/submitter.go, internal/mocks/submitter_test.go, internal/model/experiment.go, internal/oonirun/experiment.go, internal/oonirun/experiment_test.go, internal/oonirun/inputprocessor.go, internal/oonirun/inputprocessor_test.go, internal/oonirun/submitter.go, internal/oonirun/submitter_test.go, internal/oonirun/v2_test.go, internal/probeservices/collector.go, internal/probeservices/collector_test.go, pkg/oonimkall/session.go, pkg/oonimkall/taskmodel.go, pkg/oonimkall/taskrunner.go, pkg/oonimkall/taskrunner_test.go
Implements: https://github.com/ooni/probe/issues/2521
=> Add support for returning measurement_uid as part of oonimkall API

Dockerfile.oonith, Readme.md
This diff upgrades to use go1.22.3 in all areas in the engine
=> chore: upgrade to go1.22.3 in all areas

internal/stuninput/stuninput.go
This diff syncs stuninputs with the TPO's snowflake
=> chore: update stuninput to latest TPO snowflake

.github/workflows/alltests.yml, .github/workflows/android.yml, .github/workflows/build_docs.yml, .github/workflows/checks.yml, .github/workflows/codeql-analysis.yml, .github/workflows/coverage.yml, .github/workflows/debianrepo.yml, .github/workflows/generate.yml, .github/workflows/go1.22.yml, .github/workflows/gobash.yml, .github/workflows/gosec.yml, .github/workflows/ios.yml, .github/workflows/libtorlinux.yml, .github/workflows/linux.yml, .github/workflows/macos.yml, .github/workflows/netxlite.yml, .github/workflows/oohelperd.yml, .github/workflows/tarball.yml, .github/workflows/windows.yml, internal/cmd/ghgen/utils.go
This upgrades the github upload-artifact action to v4 since v3 has been deprecated: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/ 
We also upgrade the gh checkout action.
=> fix: upgrade upload-artifact gh action to v4

.github/workflows/ios.yml, .github/workflows/macos.yml, .github/workflows/netxlite.yml, internal/cmd/ghgen/config.go
macos-12 has been deprecated and it seems, our workflows are taking quite long in the queue. This should fix it since a macos-13 runner should be more available.
=> fix: upgrade to using macos-13 for mac workflows

.github/workflows/ios.yml
It seems the upgrade for the macos github runner requires the expected xcode version to be 15.2. This diff fixes the issue
=> fix: upgrade XCODE version for ios gh action

internal/checkincache/checkincache.go, internal/checkincache/checkincache_test.go, internal/probeservices/checkin_test.go, internal/registry/factory.go, internal/registry/torsf.go
This diff allows disabling default enabled tests in the engine using the checkin api. The summary of changes are: 
- if a nettest is enabled by the engine but disabled by checkin and the web_connectivity experiment was run in the last 24 hours, the nettest would throw an error and not run 
- if the checkin cache has expired and web_connectivity was not called in the last 24 hours, the nettest will run and switch to default behaviour
Apart from this, the running should WAI i.e., if the nettest is disabled by default in the engine, we will check the `OONI_FORCE_ENABLE_EXPERIMENT` env variable and also the checkin cache. However, if a checkin cache is not found at this point, the test will fail to run and throw an error. It is only when we find an explicit permission from the checkin cache …
=> feat: allow disabling tests enabled tests using checkin

internal/version/version.go
We are now hacking on 3.26.0-alpha
=> chore: bump internal version to 3.26.0-alpha

MOBILE/android/template.pom, Makefile, internal/cmd/buildtool/android.go
Add flags for android `16k` page size.
See alignment script on how to verify https://developer.android.com/guide/practices/page-sizes#alignment-use-script
=> chore: add flags for android 16k page size

cmd/ooniprobe/internal/nettests/echcheck.go
This diff changes the targets for the echcheck experiment in ooniprobe CLI to use the default targets set in the experiment
=> fix: use experiment target as default for ooniprobe cli

.github/workflows/debianrepo.yml, E2E/debian.bash
This diff fixes issues with the e2e checks failing to ensure that ooniprobe can be installed on debian.
=> fix: e2e checks for debian installs

internal/version/version.go
We are now hacking on `v3.28.0-alpha`
=> chore: upgrade internal version to 3.28.0-alpha
